/**
 * The sample sentences a Script round shows.
 *
 * Server only, and that is a rule rather than a habit: if the browser
 * held the whole corpus it could match the text on screen against it and
 * read off the answer before the guess. The round endpoint sends one
 * sentence and a sealed token, the same way the panorama game sends a
 * panorama id and never the coordinate.
 *
 * **Two sources.** The first sentences in each list were written for the
 * game: a cold morning, hot tea, walking to work, the same few meanings
 * in every language so the content could not leak the answer. There
 * were two or three of them per language and that was the whole corpus,
 * which meant anybody who played twice had read all of it.
 *
 * The rest come from **Tatoeba** (CC-BY 2.0 FR), which this file named
 * as the upgrade it wanted before anybody had fetched it: real
 * sentences written by speakers, tagged with the same ISO 639-3 codes
 * the game uses. `scripts/build-script-corpus.js` fetches and filters
 * them, and the filtering is most of the work, because a crowdsourced
 * corpus is not a curated one:
 *
 * - every character has to be in the language's own script, so a
 *   transliteration filed under the wrong code cannot get in;
 * - no digits in any script, no currency, no URLs, no quotes;
 * - every word has to be among the commonest few hundred its language
 *   has, which strips names in scripts with no capital letters to spot
 *   them by, and strips the unusual vocabulary a crowdsourced corpus
 *   collects along with it;
 * - Tatoeba's stock cast, Tom and Mary and the rest, is named and
 *   refused: they are the commonest words in the corpus rather than
 *   rare ones, so frequency alone never catches them;
 * - nothing may name a place, a language or a number, checked against
 *   the same list __tests__/geo/script.test.js checks against;
 * - and it has to carry one of the language's own markers and none of
 *   a rival's, so every sentence still teaches something on the reveal
 *   and no sentence hands a feature to the wrong language.
 *
 * What survives all of that is 461 sentences across 75 languages, on
 * top of the 415 that were here. The other 84 keep what they had:
 * Tatoeba is thin in Wolof and Tetum, and a filter loose enough to find
 * something there would be loose enough to let a place name through
 * somewhere else.
 *
 * **A third source, from 2026-09-25: the Universal Declaration of Human
 * Rights.** It is translated into more languages than any other text,
 * and the Unicode UDHR project keeps the translations as plain text
 * (NLTK distributes that corpus as public domain). The languages added
 * that day take their sentences from it, copied exactly, and it has the
 * property the first sentences were written to have: every language says
 * the same things, so the content cannot give the answer away. A language
 * with no translation of the declaration has Tatoeba sentences instead,
 * picked one by one.
 *
 * **The curation rule, which matters more than the size of the pool:**
 * strip proper nouns. A sentence containing a city name answers itself,
 * and so does a digit, a currency symbol or a flag. Nothing here names a
 * place, a person or a number, and __tests__/geo/script.test.js checks
 * that rather than trusting it.
 */

export const SAMPLES = {
  hin: [
    'आज सुबह बहुत ठंड थी, इसलिए मैंने गरम चाय पी।',
    'वह हर रोज़ पैदल ही दफ़्तर जाता है।',
    'मुझे नहीं पता कि यह रास्ता कहाँ जाता है।',
    'उसके पास बहुत सारी इतिहास की किताबें हैं।',
    'मेरे पास एक कुत्ता है।',
    'यह मेरा कुत्ता है।',
    'मेरे पास ज़्यादा पैसे नहीं हैं।',
    'मेरी बीवी डॉक्टर है।',
    'उसे टीवी पर टेनिस देखना बहुत पसंद है।',
    'कल का मौसम कैसा होगा कहना मुश्किल है।',
  ],
  mar: [
    'आज सकाळी खूप थंडी होती, म्हणून मी गरम चहा घेतला.',
    'तो दररोज चालत ऑफिसला जातो.',
    'मला माहीत नाही की हा रस्ता कुठे जातो.',
    'टॉम काय विचार करत होता मला माहीत नाही.',
    'त्याला ते माहीत नव्हतं.',
    'टॉमला माहीत आहे का?',
    'माझा चहा कुठे आहे?',
    'कोणालाही माहीत नाही.',
    'काय करायचं मला माहीत आहे.',
    'ते मला माहीत नाही.',
  ],
  npi: [
    'आज बिहान धेरै जाडो थियो, त्यसैले मैले तातो चिया खाएँ।',
    'उनी हरेक दिन हिँडेरै कार्यालय जान्छन्।',
    'मलाई थाहा छैन यो बाटो कहाँ जान्छ।',
    'मेरो किताब यहाँ छैन।',
    'म पनि चिया पिउँछु ।',
    'यो काम गाह्रो छैन।',
    'मलाई टम मेरीको प्रेमी थियो भन्ने लाग्यो।',
    'भित्र ठाउँ खाली थियो ।',
    'टम बाहिर कसैलाई पर्खिरहेको थियो।',
    'म धेरै ठाउँ घुम्न चाहन्छु तर मसँग पैसा छैन।',
  ],
  bho: [
    'आज भोरे बहुते जाड़ा रहे, ओहसे हम गरम चाह पिअनी।',
    'ऊ रोज पैदले दफ्तर जाला।',
  ],
  mai: [
    'आइ भोरमे बड़ ठंढ छल, तेँ हम गरम चाह पिलहुँ।',
    'ओ रोज पएरे कार्यालय जाइत छथि।',
  ],
  ben: [
    'আজ সকালে খুব ঠান্ডা ছিল, তাই আমি গরম চা খেয়েছি।',
    'সে প্রতিদিন হেঁটেই অফিসে যায়।',
    'আমি জানি না এই রাস্তা কোথায় যায়।',
    'আমি বুঝতে পারছি না।',
    'এটি গুরুত্বপূর্ণ না।',
    'তোমাকে আমার অনেক কিছু বলার ইচ্ছে আছে।',
    'আমি একজন শিক্ষক ছিলাম।',
    'আমার ঘুমাতে যাওয়া উচিৎ।',
    'আমার থেকে তোমার অবস্থা অনেক ভালো।',
    'এর কারণ তুমি একলা হতে চাও না।',
  ],
  asm: [
    'আজি ৰাতিপুৱা বৰ ঠাণ্ডা আছিল, সেয়েহে মই গৰম চাহ খালোঁ।',
    'তেওঁ প্ৰতিদিনে খোজ কাঢ়িয়েই কাৰ্যালয়লৈ যায়।',
    'মই চিগাৰেট খাব পাৰোঁ নে?',
    'মোৰ কোনো সঁচা পছন্দ নাই।',
    'মই তোমাক ভাল পাওঁ।',
    'মই তোমাক ভাল পাইছিলোঁ।',
    'মই তোমাক বেয়া পাওঁ।',
    'মই আপোনাক বেয়া পাওঁ।',
    'মই তোমাক বেয়া পাওঁ!',
  ],
  pan: [
    'ਅੱਜ ਸਵੇਰੇ ਬਹੁਤ ਠੰਢ ਸੀ, ਇਸ ਲਈ ਮੈਂ ਗਰਮ ਚਾਹ ਪੀਤੀ।',
    'ਉਹ ਹਰ ਰੋਜ਼ ਪੈਦਲ ਹੀ ਦਫ਼ਤਰ ਜਾਂਦਾ ਹੈ।',
  ],
  guj: [
    'આજે સવારે ખૂબ ઠંડી હતી, તેથી મેં ગરમ ચા પીધી.',
    'તે દરરોજ ચાલીને જ ઓફિસ જાય છે.',
  ],
  ory: [
    'ଆଜି ସକାଳେ ବହୁତ ଥଣ୍ଡା ଥିଲା, ତେଣୁ ମୁଁ ଗରମ ଚା ପିଇଲି।',
    'ସେ ପ୍ରତିଦିନ ଚାଲି ଚାଲି ଅଫିସ ଯାଆନ୍ତି।',
  ],
  urd: [
    'آج صبح بہت سردی تھی، اس لیے میں نے گرم چائے پی۔',
    'وہ ہر روز پیدل ہی دفتر جاتا ہے۔',
    'ابھی بہت سارے کام رہتے ہیں۔',
    'میرا خیال ہے کہ ہم نہ ہی کوشش کرے تو بہتر ہے۔',
    'مگر بہت بہت مشکل ہے۔',
    'بہت کم جاپانی صحیح انگریزی بول سکتے ہیں۔',
    'ٹام نے مریم کو بتایا کہ وہ صحیح تھی۔',
    'مجھے اپنی زندگی اور پیسے سے بہت پیار ہے۔',
    'بہت خوبصورت نام ہے تمہارا۔',
  ],
  snd: [
    'اڄ صبح جو تمام سردي هئي، ان ڪري مون گرم چانهه پيتي.',
    'هو هر روز پيدل ئي آفيس ويندو آهي.',
  ],
  tam: [
    'இன்று காலை மிகவும் குளிராக இருந்தது, அதனால் நான் சூடான தேநீர் குடித்தேன்.',
    'அவர் தினமும் நடந்தே அலுவலகத்திற்குச் செல்கிறார்.',
  ],
  tel: [
    'ఈ రోజు ఉదయం చాలా చలిగా ఉంది, అందుకే నేను వేడి టీ తాగాను.',
    'అతను ప్రతిరోజూ నడిచే ఆఫీసుకు వెళ్తాడు.',
  ],
  kan: [
    'ಇಂದು ಬೆಳಿಗ್ಗೆ ತುಂಬಾ ಚಳಿ ಇತ್ತು, ಆದ್ದರಿಂದ ನಾನು ಬಿಸಿ ಚಹಾ ಕುಡಿದೆ.',
    'ಅವನು ಪ್ರತಿದಿನ ನಡೆದುಕೊಂಡೇ ಕಚೇರಿಗೆ ಹೋಗುತ್ತಾನೆ.',
  ],
  mal: [
    'ഇന്ന് രാവിലെ വളരെ തണുപ്പായിരുന്നു, അതുകൊണ്ട് ഞാൻ ചൂടുള്ള ചായ കുടിച്ചു.',
    'അവൻ എല്ലാ ദിവസവും നടന്നാണ് ഓഫീസിൽ പോകുന്നത്.',
  ],
  sin: [
    'අද උදේ හරිම සීතලයි, ඒ නිසා මම උණුසුම් තේ එකක් බිව්වා.',
    'ඔහු හැම දාම පයින්ම කාර්යාලයට යනවා.',
  ],
  arb: [
    'كان الجو باردا جدا هذا الصباح، لذلك شربت شايا ساخنا.',
    'يذهب إلى المكتب سيرا على الأقدام كل يوم.',
    'لا أعرف إلى أين يؤدي هذا الطريق.',
  ],
  pes: [
    'امروز صبح هوا خیلی سرد بود، برای همین چای داغ خوردم.',
    'او هر روز پیاده به دفتر می‌رود.',
    'من ژاپنی صحبت نمی‌کنم.',
    'هیچکس مرا درک نمی‌کند.',
    'به زودی بهار می‌شود.',
    'آنچه را به تو می‌گوید، باور نکن.',
    'با گفتن اشتباه کردم کار درست نمی‌شود.',
    'چند زبان را خوب می‌توانید صحبت کنید؟',
    'معمولاً با او به مدرسه می‌رفتم.',
  ],
  pbu: [
    'نن سهار ډېره یخني وه، نو ما ګرمه چای وڅښله.',
    'هغه هره ورځ پلی دفتر ته ځي.',
  ],
  ckb: [
    'ئەمڕۆ بەیانی زۆر سارد بوو، بۆیە چایەکی گەرمم خواردەوە.',
    'ئەو هەموو ڕۆژێک بە پێ دەچێتە نووسینگە.',
    'گوێی کچەکە گەورەیە!',
    'سامی ژیانی خۆش دەوێت',
    'لەوانەیە تۆم گۆرانی بڵێت بۆ ئێمە',
    'دوێنێ تۆم یارمەتی دایکی دا؟',
    'تۆم بە ئۆتۆمبێل چووە بۆستن بۆ بینینی ماری.',
    'لە کوێ کار دەکەیت.',
    'نا، نا! ئەوە ڕاست نییە.',
  ],
  uig: [
    'بۈگۈن ئەتىگەندە ھاۋا بەك سوغۇق ئىدى، شۇڭا مەن ئىسسىق چاي ئىچتىم.',
    'ئۇ ھەر كۈنى پىيادە ئىشخانىغا بارىدۇ.',
    'ئۇنىڭ ئاكىسى مەندىن ئىككى ياش چوڭ.',
    'ساڭا تېلېڧون كەلدى!',
    'كەچۈرۈڭ، ھازىر مەن بەك ئالدىراش.',
    'بۇ تۈنۈگۈن كەلگەن قىز.',
    'مېنىڭ يەنە بىر سىڭلىم بار.',
    'بۇ ئۆي يېڭى ئەمەس.',
    'ئىككى يۈز پۇل ماڭا كۆپ پۇل بولىدۇ.',
  ],
  rus: [
    'Сегодня утром было очень холодно, поэтому я выпил горячего чаю.',
    'Он каждый день ходит на работу пешком.',
    'Я не знаю, куда ведёт эта дорога.',
    'Это не то, что может сделать каждый.',
    'Сегодня утром мне холодно.',
    'Сегодня понедельник.',
    'Сегодня довольно холодно.',
    'Откуда вы друг друга знаете?',
    'Вот откуда я её знаю.',
    'Сегодня я чувствую себя хорошо.',
  ],
  ukr: [
    'Сьогодні вранці було дуже холодно, тому я випив гарячого чаю.',
    'Він щодня ходить на роботу пішки.',
    'Я не знаю, куди веде ця дорога.',
    'Сьогодні достатньо холодно.',
    'Я запитав, куди йти.',
    'Я не знаю, куди він пішов.',
    'Ти знаєш, куди пішов твій батько?',
    'Сьогодні їй набагато краще, ніж учора.',
    'Він запитав мене куди їхати.',
    'Він запитав мене куди йти.',
  ],
  bul: [
    'Тази сутрин беше много студено, затова изпих горещ чай.',
    'Той ходи на работа пеша всеки ден.',
    'Той беше ядосан, че никой нищо не каза.',
    'Тази работа може да се свърши за седмица.',
    'Той често пише на родителите си.',
    'Той не успя да получи работата.',
    'Той дойде да ме види.',
    'Той реши да отиде в чужбина.',
    'Той обича да гледа телевизия.',
  ],
  srp: [
    'Јутрос је било веома хладно, па сам попио врућ чај.',
    'Он сваки дан иде на посао пешке.',
    'Није знао шта ће рећи.',
    'Он ће доћи ако жели.',
    'Да ли он може доћи сутра?',
    'Да ли је вероватно да ће он доћи?',
    'Ко ће од вас вероватно доћи?',
    'Ја не верујем да ће он доћи.',
    'Не може се тако рећи.',
  ],
  kaz: [
    'Бүгін таңертең өте суық болды, сондықтан мен ыстық шай іштім.',
    'Ол күн сайын жұмысқа жаяу барады.',
    'Жоқ, мен емес, сен!',
    'Бұл маған өте ұнайды.',
    'Ол қайда жұмыс істейді?',
    'Ешқандай менің досым емес.',
    'Кеше өте суық болды.',
    'Осы шай өте жақсы.',
    'Саған қарап отырмын.',
  ],
  mon: [
    'Өнөө өглөө маш хүйтэн байсан тул би халуун цай уусан.',
    'Тэр өдөр бүр ажилдаа явган явдаг.',
    'Тэр худлаа хэлж байна.',
    'Тэр эмэгтэй баяртай харагдаж байна.',
    'Тэр юу хийж байгаа юм бэ?',
    'Өнөөдөр бороо орж байна.',
    'Тэр үед юу өөр байсан бэ?',
    'Тэр эмэгтэй одоо хаана амьдарч байгаа вэ?',
    'Тэр энд амьдардаг уу?',
  ],
  ell: [
    'Σήμερα το πρωί έκανε πολύ κρύο, γι’ αυτό ήπια ζεστό τσάι.',
    'Πηγαίνει στη δουλειά με τα πόδια κάθε μέρα.',
    'Σας είπα ήδη ότι δεν είναι εδώ.',
    'Σ\' αγαπώ, μωρό μου.',
    'Σε λατρεύω μωρό μου.',
    'Σε λατρεύω αγάπη μου.',
    'Σ\' αγαπώ έτσι όπως είσαι.',
    'Στο πάρκο ήταν πολλοί άνθρωποι.',
    'Σου αρέσει η μουσική;',
  ],
  heb: [
    'היה קר מאוד הבוקר, ולכן שתיתי תה חם.',
    'הוא הולך למשרד ברגל כל יום.',
    'מה אתה רוצה לעשות?',
    'אתה חושב יותר מדי.',
    'הוא אוהב לשתות קפה בלי סוכר.',
    'האם אפשר לקבל עזרה?',
    'אינני יודע מתי הוא יבוא לכאן.',
    'פגשתי את טום בדרך.',
    'הכובע הזה קטן מדי בשבילי.',
  ],
  kat: [
    'დღეს დილით ძალიან ცივოდა, ამიტომ ცხელი ჩაი დავლიე.',
    'ის ყოველდღე ფეხით მიდის სამსახურში.',
    'მას ძალიან უყვარს თავისი სკოლა.',
    'შეგიძლია წახვიდე თუ გინდა.',
    'მე ერთი ძმა მყავს.',
    'აი, თქვენი გასაღები.',
    'მე აქ აღარ ვცხოვრობ.',
    'ახლა შეგიძლია წახვიდე.',
    'ძალიან კარგი იქნება.',
  ],
  hye: [
    'Այսօր առավոտյան շատ ցուրտ էր, դրա համար տաք թեյ խմեցի։',
    'Նա ամեն օր ոտքով է գնում աշխատանքի։',
    'Խնդրում եմ, թույլ տվեք օգնել:',
    'Ես երբեք չեմ մոռանա այդ օրը:',
    'Կես ժամ է ինչ սպասում եմ։',
    'Թոմը ասաց, որ կօգնի ինձ:',
    'Ասա ինձ, ինչ ես փնտրում, ու ես կօգնեմ քեզ դա գտնել:',
    'Թոմը այսօր շատ ավելի ուժեղ է:',
    'Ինչ վերջապես մեկը կօգնի՞ թե ո՛չ:',
  ],
  amh: [
    'ዛሬ ጠዋት በጣም ቀዝቃዛ ነበር፣ ስለዚህ ትኩስ ሻይ ጠጣሁ።',
    'እሱ በየቀኑ በእግሩ ወደ ቢሮ ይሄዳል።',
  ],
  tir: [
    'ሎሚ ንግሆ ኣዝዩ ቁሪ ነይሩ፣ ስለዚ ውዑይ ሻሂ ሰቲየ።',
    'ንሱ መዓልቲ መዓልቲ ብእግሩ ናብ ቤት ጽሕፈት ይኸይድ።',
    'እዛ ገረብ፡ ሓምሳ ዓመት ገይራ ኣላ።',
    'ኣብ ትሕቲ ምድሪ እንዳ ዕዳጋ ኣሎ።',
    'ኣቦይ፡ መስሓቕ ነገራት ክዛረብ ይፈቱ።',
    'ኣብ ለንደን፡ ኣዝዩ ብዙሕ ሓደገኛ ቦታታት ኣሎ።',
    'ሃ ሃ ሃ፡ ኣዝዩ መስሓቕ እዩ።',
    'ኣብዚ ኵሉ ሳዕ ገለ ዝግበር ነገር ኣሎ።',
    'እዚ፡ ብሓቂ ኣገዳሲ ኣይኮነን።',
  ],
  tha: [
    'เช้านี้อากาศหนาวมาก ฉันเลยดื่มชาร้อน',
    'เขาเดินไปทำงานทุกวัน',
  ],
  lao: [
    'ເຊົ້ານີ້ອາກາດໜາວຫຼາຍ ຂ້ອຍຈຶ່ງດື່ມຊາຮ້ອນ',
    'ຂ້ອຍຍ່າງໄປເຮັດວຽກທຸກມື້',
  ],
  khm: [
    'ព្រឹកនេះអាកាសធាតុត្រជាក់ណាស់ ដូច្នេះខ្ញុំបានផឹកតែក្តៅ។',
    'គាត់ដើរទៅធ្វើការរាល់ថ្ងៃ។',
    'ទៅ​ជា​មួយ​ខ្ញុំ​បាន​ទេ​?',
    'ថម ស្រលាញ់ ម៉ារី ។',
  ],
  mya: [
    'ဒီမနက် အရမ်းအေးတယ်၊ ဒါကြောင့် ပူပူနွေးနွေး လက်ဖက်ရည် သောက်လိုက်တယ်။',
    'သူ နေ့တိုင်း ရုံးကို လမ်းလျှောက်သွားတယ်။',
  ],
  cmn: [
    '今天早上很冷，所以我喝了一杯热茶。',
    '他每天都走路去上班。',
    '我不知道这条路通向哪里。',
  ],
  jpn: [
    '今朝はとても寒かったので、温かいお茶を飲みました。',
    '彼は毎日歩いて会社に行きます。',
    'この道がどこへ続いているのか分かりません。',
    'こんにちは、お元気ですか、みなさん。',
  ],
  kor: [
    '오늘 아침은 무척 추워서 따뜻한 차를 마셨다.',
    '그는 매일 걸어서 회사에 간다.',
    '이 길이 어디로 이어지는지 모르겠다.',
    '너는 몇 개의 언어를 말할 수 있니?',
    '어제 그는 아무 것도 안 먹었다.',
    '난 네가 보스턴에서 한 일을 알고 있다.',
    '메리가 읽고 싶은 책이 톰에게 있다.',
    '그녀는 나에게 먹을 것을 주었다.',
    '나는 이 편지를 그에게 쓰고 있어.',
    '그녀는 일곱 개의 언어를 말한다.',
  ],
  spa: [
    'Esta mañana hacía mucho frío, así que me tomé un té caliente.',
    'Va andando al trabajo todos los días.',
    'No sé adónde lleva este camino.',
    'Él se quedó hasta diez días.',
    'El tiempo estuvo malo todos los días.',
    'Juego al fútbol todos los días.',
    'Él no viene aquí todos los días.',
    'En una semana hay siete días.',
    'Hace tres días que no le veo.',
    'Buenos días a todos.',
  ],
  por: [
    'Esta manhã estava muito frio, por isso bebi um chá quente.',
    'Ele vai a pé para o trabalho todos os dias.',
    'Não sei aonde leva esta estrada.',
    'Eu gosto muito do meu trabalho.',
    'Tenho muito trabalho a fazer.',
    'Estou muito cansado do trabalho.',
    'Vou escrever uma carta amanhã.',
    'Venha amanhã aqui sem falta.',
    'Agora vamos começar nosso trabalho.',
    'Eu espero que esteja melhor amanhã.',
  ],
  ita: [
    'Stamattina faceva molto freddo, così ho bevuto un tè caldo.',
    'Va a piedi al lavoro tutti i giorni.',
    'Sono così felice per te.',
    'Non posso vivere così.',
    'Mi sento molto solo in questi giorni.',
    'Sono molto occupato in questi giorni.',
    'Gioco a tennis tutti i giorni.',
    'Non voglio aspettare così tanto tempo.',
    'Va a scuola a piedi.',
  ],
  ron: [
    'În această dimineață a fost foarte frig, așa că am băut un ceai fierbinte.',
    'Merge pe jos la muncă în fiecare zi.',
    'Bună dimineața la toată lumea.',
    'Mulțumesc foarte mult!',
    'Bună seara, ce faci?',
    'Bună seara, ce mai faceți?',
    'Astăzi vremea e frumoasă.',
    'Este frumos astăzi.',
    'Îmi face plăcere să merg pe jos.',
  ],
  fra: [
    'Ce matin il faisait très froid, alors j’ai bu un thé chaud.',
    'Il va au bureau à pied tous les jours.',
    'Je ne sais pas où mène cette route.',
    'Mon bureau est fait de bois.',
    'Il faisait chaud la nuit dernière.',
    'Il faisait chaud hier.',
    'Il faisait froid hier.',
    'Il faisait très froid hier matin.',
    'Il faisait très froid ce matin.',
    'Il faisait moins dix ce matin.',
  ],
  cat: [
    'Aquest matí feia molt de fred, així que vaig prendre un te calent.',
    'Va a peu a la feina cada dia.',
    'Em vaig quedar un dia més al llit per si de cas.',
    'Fa dos anys des que vaig venir ací.',
    'Quan va arribar vaig fer cafè.',
    'Qui pot fer aquesta feina?',
    'Li vaig comprar a ella un nou cotxe.',
    'De cop, vaig tenir sort.',
    'Me la vaig trobar de camí cap a l\'escola.',
  ],
  deu: [
    'Heute Morgen war es sehr kalt, deshalb habe ich einen heißen Tee getrunken.',
    'Er geht jeden Tag zu Fuß ins Büro.',
    'Ich weiß nicht, wohin dieser Weg führt.',
    'Ich weiß einfach nicht, was ich sagen soll.',
    'Ich weiß nicht mehr, was ich tun soll.',
    'Ich weiß nicht, ob ich es noch habe.',
    'Wie, du weißt nicht?!',
    'Ich weiß nicht, ob er das für mich getan hätte.',
    'Ich weiß nicht, wo er wohnt.',
    'Weißt du, wer sie ist?',
  ],
  nld: [
    'Vanochtend was het erg koud, dus dronk ik een warme thee.',
    'Hij gaat elke dag lopend naar kantoor.',
    'Hij speelt zeer goed.',
    'Hij heeft een brief geschreven.',
    'Hij is al een man.',
    'Hij zal op je wachten.',
    'Hij wacht wel op je.',
    'Hij weet zeker dat hij komt.',
    'Hij deed zo zijn best dat hij er helemaal rood van werd.',
  ],
  afr: [
    'Vanoggend was dit baie koud, daarom het ek warm tee gedrink.',
    'Hy loop elke dag werk toe.',
    'Hy is \'n onderwyser.',
    'Hy kon nie kom nie, omdat hy siek was.',
    'Ons is baie dronk.',
    'Ek is nou baie moeg.',
    'Hy is trots op sy seun.',
    'Hy is nie siek nie.',
    'Dit was baie mooi.',
  ],
  swe: [
    'I morse var det mycket kallt, så jag drack en kopp varmt te.',
    'Han går till jobbet varje dag.',
    'Idag mår jag mycket bättre.',
    'Jag är mycket hungrig.',
    'Min mor tycker mycket om te.',
    'Hur mycket blir det?',
    'Jag har inte så mycket pengar med mig.',
    'Du pratar för mycket.',
    'Ät så mycket du vill.',
  ],
  dan: [
    'I morges var der meget koldt, så jeg drak en kop varm te.',
    'Han går på arbejde hver dag.',
    'Det er lige meget.',
    'Jeg vil hjælpe dig så meget jeg kan.',
    'Jeg holder meget af hende.',
    'Han kender os meget godt.',
    'Bogen er meget interessant.',
    'Han kan gøre det meget bedre end jeg kan.',
    'En computer er i stand til at regne meget hurtigt.',
  ],
  nob: [
    'I morges var det veldig kaldt, så jeg drakk en kopp varm te.',
    'Han går til jobben hver dag.',
    'Jeg er veldig glad for å se deg igjen.',
    'Jeg var veldig trøtt, så jeg la meg tidlig.',
    'Han liker musikk veldig godt.',
    'Det var så kaldt at jeg ble hjemme hele dagen.',
    'Jeg kan svømme veldig fort.',
    'Hun var veldig stolt av faren sin.',
    'Hvor langt har du kommet med jobben?',
  ],
  isl: [
    'Í morgun var mjög kalt, svo ég drakk heitt te.',
    'Hann gengur í vinnuna á hverjum degi.',
    'Satt að segja elska ég hann ekki.',
    'Ég mun gera allt sem ég get fyrir hana.',
    'Þetta er ekki það sem ég er að leita að.',
    'Segðu mér hvað þú vilt að ég geri.',
    'Ég var næstum búinn með vinnuna mína þegar hún kom.',
    'Það er mjög kalt í dag.',
    'Pabbi minn sagði að ég gæti ekki farið einn til útlanda.',
  ],
  fin: [
    'Tänä aamuna oli hyvin kylmä, joten join kuumaa teetä.',
    'Hän kävelee töihin joka päivä.',
    'Olen ollut kiireinen koko päivän.',
    'Hänellä ei ollut rahaa joten hän ei voinut ostaa ruokaa',
    'Minulla on kiire, joten en voi mennä.',
    'Kaunis päivä, eikö?',
    'Hän on tehnyt töitä koko päivän.',
    'Olen ollut kotona melkein koko päivän.',
    'Hän tuli takaisin kaksi päivää myöhemmin.',
  ],
  est: [
    'Täna hommikul oli väga külm, seetõttu jõin kuuma teed.',
    'Ta käib iga päev jalgsi tööl.',
    'Mine tagasi tööle.',
    'Ma lähen nüüd parem tööle tagasi.',
  ],
  hun: [
    'Ma reggel nagyon hideg volt, ezért forró teát ittam.',
    'Minden nap gyalog megy dolgozni.',
    'Tegnap nem voltam dolgozni.',
    'Senki se akar kint dolgozni, amikor hideg van.',
    'Ma nincs kedvem dolgozni.',
    'Tanulni akarok, ezért iskolába megyek.',
    'Nagyon meleg van ma, ezért nincs kedvem tanulni.',
    'Nem akarok dolgozni.',
    'Azt mondta, hogy fáradt, ezért korán megy haza.',
  ],
  pol: [
    'Dziś rano było bardzo zimno, więc wypiłem gorącą herbatę.',
    'Codziennie chodzi do pracy pieszo.',
    'Proszę bardzo, nie ma za co.',
    'Możesz jechać, gdzie ci się podoba.',
    'Pamiętam pierwszy raz.',
    'Jesteś przy mnie, a więc wszystko dobrze.',
    'Dziękuję, to wszystko.',
    'Musisz więcej pracować.',
    'Bardzo lubię swoją pracę.',
  ],
  ces: [
    'Dnes ráno byla velká zima, tak jsem si dal horký čaj.',
    'Chodí do práce pěšky každý den.',
    'Koupil jsem si nové auto.',
    'Zůstal jsem týden doma.',
    'Asi jsem se ztratil.',
    'Koupil jsem to včera.',
    'Slyšel jsem, že zemřel.',
    'Včera jsem čekal, že přijde.',
    'Četl jsem nějaké knihy.',
  ],
  hrv: [
    'Jutros je bilo vrlo hladno, pa sam popio topli čaj.',
    'Svaki dan ide na posao pješice.',
  ],
  lit: [
    'Šįryt buvo labai šalta, todėl išgėriau karštos arbatos.',
    'Jis kasdien eina į darbą pėsčiomis.',
    'Viskas ką jis pasakė buvo tiesa.',
    'Tas kambarys nėra labai didelis.',
    'Tomas neturi šiandien eiti į mokyklą.',
    'Mano tėvas moka plaukti, bet mano motina ne.',
    'Aš nemėgstu kavos.',
    'Mano tėvas ką tik grįžo namo.',
    'Jis ką tik grįžo namo.',
  ],
  sqi: [
    'Sot në mëngjes ishte shumë ftohtë, prandaj piva një çaj të nxehtë.',
    'Ai shkon në punë në këmbë çdo ditë.',
    'Pse gjithçka po shkon keq?',
    'Flet frëngjisht çdo ditë?',
  ],
  eus: [
    'Gaur goizean oso hotz egiten zuen, beraz te bero bat hartu dut.',
    'Egunero oinez joaten da lanera.',
    'Nork idatzi zuen liburu hau?',
    'Ez duzu entzun zer azkar hitz egiten zuen?',
    'Gorroto nuen, baina zure laguntza behar dugu esaten zuen.',
    'Egunero zerbait ikasten.',
    'Badakizu nork hil zuen?',
    'Egunero korrika egiten du.',
    'Mundu osoa seguru dago berak izan zela egin zuena.',
  ],
  cym: [
    'Roedd hi’n oer iawn y bore yma, felly yfais i de poeth.',
    'Mae’n cerdded i’r gwaith bob dydd.',
    'Roedd hi eisiau bod yn athrawes.',
    'Roedd rhaid i mi aros adre.',
    'Roedd gen\' i gath.',
    'Roedd hi\'n gallu darllen y llyfr.',
  ],
  tur: [
    'Bu sabah hava çok soğuktu, bu yüzden sıcak bir çay içtim.',
    'Her gün işe yürüyerek gidiyor.',
    'Artık seni sevmiyorum.',
    'Çok daha iyi hissediyorum.',
    'Artık çocuk değilim.',
    'Hiç kimse bilmiyor.',
    'Doktor olarak iyi değil.',
    'Seni çok seviyorum.',
    'Yarın burada olacağım.',
  ],
  azj: [
    'Bu səhər hava çox soyuq idi, ona görə isti çay içdim.',
    'O, hər gün işə piyada gedir.',
  ],
  uzn: [
    'Bugun ertalab juda sovuq edi, shuning uchun issiq choy ichdim.',
    'U har kuni ishga piyoda boradi.',
  ],
  vie: [
    'Sáng nay trời rất lạnh, nên tôi đã uống một tách trà nóng.',
    'Anh ấy đi bộ đến chỗ làm mỗi ngày.',
    'Tôi hết lời để nói.',
    'Nếu thế giới không như bây giờ, thì tôi có thể tin ai cũng được.',
    'Một người luôn luôn có thể kiếm thêm thì giờ.',
    'Phần nhiều người ta viết về chuyện cuộc đời hàng ngày.',
    'Có lẽ cũng vậy cho anh ấy luôn.',
    'Tôi ghét những lúc đông người.',
    'Không, anh ấy không phải bạn trai mới của tôi.',
  ],
  ind: [
    'Pagi ini udaranya sangat dingin, jadi saya minum teh hangat.',
    'Dia berjalan kaki ke kantor setiap hari.',
    'Kemarin pagi sangat dingin.',
    'Di rumahku sangat dingin.',
    'Apakah kamu tidak merasa dingin.',
    'Mana yang lebih kamu suka: musim panas atau musim dingin?',
    'Kamu lebih suka musim panas atau musim dingin?',
    'Aku ingin minum sesuatu yang dingin.',
    'Sayang sekali, seperti yang kamu tahu, saya tidak bisa pergi ke kantor polisi.',
  ],
  zsm: [
    'Pagi ini cuaca sangat sejuk, jadi saya minum teh panas.',
    'Dia berjalan kaki ke pejabat setiap hari.',
    'Dalam cuaca yang teruk ini, saya tidak ingin keluar.',
    'Hari ini cuaca sejuk.',
    'Saya tiada di pejabat hari ini.',
    'Saya merasakan angin sejuk di muka saya.',
    'Semalam sangat sejuk, jadi kami tidak keluar dan hanya duduk di rumah.',
    'Ia semakin sejuk di sini.',
    'Hari ini, cuaca sangat baik.',
  ],
  tgl: [
    'Napakalamig ngayong umaga, kaya uminom ako ng mainit na tsaa.',
    'Naglalakad siya papunta sa trabaho araw-araw.',
    'Mas malamig ngayong umaga kaysa sa kahapon.',
    'Nag-aaral ka araw-araw?',
    'Di araw-araw ay linggo.',
    'Umiinom ng gamot ang lolo ko araw-araw.',
    'Dala ng mga batang lalaki ang mga libro nila araw-araw.',
    'Siya ay nagluluto para sa kanyang asawa araw-araw.',
    'Bakit ang laki ng buwan ngayong gabi?',
  ],
  swh: [
    'Asubuhi ya leo kulikuwa na baridi sana, kwa hiyo nilikunywa chai ya moto.',
    'Yeye huenda kazini kwa miguu kila siku.',
    'Yeye ni ndani ya nyumba hii.',
    'Yeye ni mwalimu wangu.',
    'Yeye ni mwanamke mzuri.',
    'Yeye hana bunduki.',
    'Yeye ni msichana wa miaka kumi na mbili.',
    'Yeye ni maarufu kuliko mimi.',
    'Yeye hana moyo hata kidogo.',
  ],
  hau: [
    'Da safiyar yau an yi sanyi sosai, saboda haka na sha shayi mai zafi.',
    'Yana tafiya aiki da ƙafa kowace rana.',
    'Yau sanyi da sauƙi.',
    'Abun da zaka iya yi kawai shine iya ƙoƙarin ka.',
    'Meyasa ka yi ƙoƙarin gudu?',
    'Ina son zuwa ƙasar waje.',
    'Ba a buƙatar sauri.',
    'Na wani abu ya taɓa min ƙafa.',
    'Idan aka kuma wani yaƙi, duk sai an kashe mu.',
  ],
  yor: [
    'Òwúrọ̀ òní tutù gan-an, nítorí náà mo mu tíì gbígbóná.',
    'Ó máa ń rìn lọ sí ibi iṣẹ́ lójoojúmọ́.',
  ],
  som: [
    'Subaxdan aad bay u qabow ahayd, sidaas darteed waxaan cabbay shaah kulul.',
    'Maalin walba lugta ayuu shaqada ku aadaa.',
  ],
  zul: [
    'Namhlanje ekuseni bekubanda kakhulu, ngakho ngiphuze itiye elishisayo.',
    'Uhamba ngezinyawo eya emsebenzini nsuku zonke.',
  ],
  mkd: [
    'Утрово беше многу студено, затоа испив топол чај.',
    'Тој секој ден оди на работа пешки.',
    'Не знам каде води овој пат.',
    'Оди на училиште секој ден за да учи.',
    'Пробај да го направиш како што треба овој пат.',
    'Не го разбирам овој збор.',
    'Само држи се до овој пат.',
    'Нешто се смени овој пат.',
    'Том си ги носи децата на училиште секој ден.',
    'Просто е да се реши овој проблем.',
  ],
  bel: [
    'Сёння раніцай было вельмі холадна, таму я выпіў гарачай гарбаты.',
    'Ён кожны дзень ходзіць на працу пешшу.',
    'Я не ведаю, куды вядзе гэтая дарога.',
    'Я люблю гэтую кнігу больш за ўсё.',
    'Я маю шмат сяброў.',
    'Ён зноў згубіў свой парасон.',
    'Я ведаю, адкуль ён.',
    'А, усё як заўсёды.',
    'Мне шкада, што я туды пайшоў.',
    'Я не ведаю, што мне цяпер рабіць.',
  ],
  tgk: [
    'Имрӯз субҳ ҳаво хеле хунук буд, барои ҳамин чойи гарм нӯшидам.',
    'Ӯ ҳар рӯз пиёда ба идора меравад.',
    'Намедонам, ки ин роҳ ба куҷо мебарад.',
  ],
  kir: [
    'Бүгүн эртең менен абдан суук болду, ошондуктан ысык чай ичтим.',
    'Ал күн сайын жумушка жөө барат.',
    'Бул жол кайда алып барарын билбейм.',
  ],
  slk: [
    'Dnes ráno bola veľká zima, tak som si dal horúci čaj.',
    'Chodí do práce pešo každý deň.',
    'Neviem, kam vedie táto cesta.',
    'Musíš sa veľa učiť.',
    'Neviem, kto to urobil.',
    'Prepáčte, koľko je hodín?',
    'Moja sestra je veľmi pekné dievča.',
    'Neviem, choď spať!',
    'Veľa z toho nerozumiem.',
    'Koľko rokov má tvoj otec?',
  ],
  slv: [
    'Danes zjutraj je bilo zelo mrzlo, zato sem spil topel čaj.',
    'Vsak dan hodi v službo peš.',
    'Ne vem, kam pelje ta cesta.',
  ],
  lav: [
    'Šorīt bija ļoti auksts, tāpēc iedzēru karstu tēju.',
    'Viņš katru dienu iet uz darbu kājām.',
    'Es nezinu, kurp ved šis ceļš.',
  ],
  glg: [
    'Esta mañá facía moito frío, así que tomei un té quente.',
    'Vai andando ao traballo cada día.',
    'Non sei onde leva este camiño.',
    'Se chove mañá non irei.',
    'Temos unha festa mañá pola noite.',
    'Ela sempre traballa moito.',
    'Hai moitos paxaros neste parque.',
    'Dende mañá podemos ir xuntos ao traballo',
    'Temos moito traballo de facer.',
    'Hoxe non, mañá si.',
  ],
  gle: [
    'Bhí sé an-fhuar ar maidin, mar sin d’ól mé tae te.',
    'Siúlann sé chun na hoibre gach lá.',
    'Cá dtéann an bóthar seo?',
    'Bhí sé ag labhairt.',
    'Bhí muid le do mháthair.',
    'Bhí an oíche fuar.',
  ],
  gla: [
    'Bha i glè fhuar sa mhadainn, mar sin dh’òl mi tì theth.',
    'Bidh e a’ coiseachd dhan obair a h-uile latha.',
    'Càite a bheil an rathad seo a’ dol?',
    'Càite a bheil thu ag obair?',
    'Bha mi glè sgìth an-diugh.',
  ],
  mlt: [
    'Dalgħodu kien kiesaħ ħafna, għalhekk xrobt tè sħun.',
    'Kuljum jimxi għax-xogħol.',
    'Ma nafx fejn twassal din it-triq.',
    'Ziri kien dejjem jorqod waħdu.',
  ],
  fao: [
    'Í morgun var sera kalt, so fekk eg mær heitt te.',
    'Hann gongur á arbeiði hvønn dag.',
    'Eg veit ikki, hvar hesin vegurin gongur.',
  ],
  ltz: [
    'De Moien war et ganz kal, dofir hunn ech waarmen Téi gedronk.',
    'Hie geet all Dag zu Fouss op de Büro.',
    'Ech weess net, wouhin dëse Wee féiert.',
    'Ech hunn iech gesinn.',
    'Ech wunnen a schaffen hei.',
  ],
  bre: [
    'Yen-tre e oa ar mintin-mañ, setu m’em eus evet te tomm.',
    'Bemdez ez a da labourat war-droad.',
    'N’ouzon ket pelec’h ez a an hent-mañ.',
    'Bemdez ez an d’ar skol.',
    'Dihun ac\'hanon warc\'hoazh da c\'hwec\'h eur mintin, mar-plij.',
    'Mar-plij, dihun ac\'hanon warc\'hoazh da c\'hwec\'h eur mintin.',
    'Ar mintin-mañ em eus debret bara amanennet.',
    'Debret em eus ar mintin-mañ bara amanennet.',
    'Debret em eus bara amanennet ar mintin-mañ.',
    'Bara amanennet em eus debret ar mintin-mañ.',
  ],
  fry: [
    'Fanmoarn wie it hiel kâld, dêrom naam ik in bakje waarme tee.',
    'Alle dagen rint er nei it wurk.',
    'Ik wit net wêr’t dizze dyk hinne giet.',
  ],
  div: [
    'މިއަދު ހެނދުނު ވަރަށް ފިނި ވި، އެހެންވެ ހޫނު ސައި ބޮއެފިން.',
    'އޭނާ ކޮންމެ ދުވަހަކު ހިނގާފައި އޮފީހަށް ދެއެވެ.',
    'މި މަގު ކޮންތާކަށް ދާކަން އަހަންނަކަށް ނޭނގެ.',
  ],
  bod: [
    'དེ་རིང་ཞོགས་པར་གྲང་མོ་ཧ་ཅང་ཆེན་པོ་འདུག ངས་ཇ་ཚ་པོ་ཞིག་བཏུངས།',
    'ཁོང་ཉིན་ལྟར་རྐང་ཐང་གིས་ལས་ཁུངས་སུ་འགྲོ་གི་ཡོད།',
    'ལམ་འདི་ག་པར་འགྲོ་མིན་ངས་མི་ཤེས།',
  ],
  dzo: [
    'ད་རིས་དྲོ་པ་ཁ་ཤིན་ཏུ་གྲང་མོ་འདུག ཨིན་མི་ང་གིས་ཇ་ཚ་ཏོང་ཏོ་འཐུང་ཡི།',
    'ཁོ་ཉིནམ་བཞིན་དུ་རྐངམ་གིས་ལཱ་གཡོག་ནང་འགྱོཝ་ཨིན།',
    'ལམ་འདི་ག་ཏེ་འགྱོཝ་ཨིན་ན་ང་གིས་མི་ཤེས།',
  ],
  sat: [
    'ᱛᱮᱦᱮᱧ ᱥᱮᱛᱟᱜ ᱯᱩᱨᱟᱹ ᱨᱟᱵᱟᱝ ᱛᱟᱦᱮᱸᱠᱟᱱᱟ, ᱚᱱᱟᱛᱮ ᱤᱧ ᱨᱟᱹᱯᱩᱫ ᱪᱟᱭ ᱧᱩᱭ ᱠᱮᱫᱟ.',
    'ᱩᱱᱤ ᱫᱤᱱ ᱫᱤᱱ ᱛᱟᱞᱟᱛᱮ ᱠᱟᱹᱢᱤ ᱛᱮ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ.',
    'ᱱᱚᱶᱟ ᱦᱚᱨ ᱚᱠᱟ ᱛᱮ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ ᱤᱧ ᱵᱟᱝ ᱵᱟᱰᱟᱭᱟ.',
    'ᱤᱧ ᱫᱚ ᱥᱤᱧᱚᱛ ᱫᱤᱥᱚᱢ ᱨᱮ ᱯᱟᱲᱦᱟᱣᱜ ᱠᱟᱹᱱᱟᱹᱧ ᱾',
    'ᱤᱧ ᱫᱚ ᱵᱷᱟᱨᱚᱛ ᱫᱤᱥᱚᱢ ᱨᱮ ᱯᱟᱲᱦᱟᱣᱜ ᱠᱟᱹᱱᱟᱹᱧ ᱾',
    'ᱤᱧᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ᱴᱚᱢ ᱠᱟᱱᱟ ᱾',
    'ᱴᱚᱢ ᱫᱚ ᱤᱧᱟᱜ ᱧᱩᱛᱩᱢ ᱠᱟᱱᱟ ᱾',
    'ᱩᱱᱤᱭᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ᱴᱚᱢ ᱠᱟᱱᱟ ᱾',
    'ᱡᱚᱦᱟᱨ, ᱤᱧᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ᱴᱚᱢ ᱠᱟᱱᱟ ᱾',
    'ᱥᱟᱹᱨᱤ ᱠᱟᱛᱷᱟ ᱠᱟᱱᱟ ᱾',
  ],
  mni: [
    'ꯉꯁꯤ ꯑꯌꯨꯛ ꯌꯥꯝꯅꯥ ꯏꯡꯏ, ꯃꯗꯨꯅꯥ ꯑꯩꯅꯥ ꯑꯁꯥꯕ ꯆꯥ ꯊꯛꯈꯤ.',
    'ꯃꯍꯥꯛꯅꯥ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯈꯣꯡꯅꯥ ꯑꯣꯐꯤꯁ ꯆꯠꯂꯤ.',
    'ꯂꯝꯕꯤ ꯑꯁꯤ ꯀꯗꯥꯏꯗꯥ ꯆꯠꯂꯤꯕꯅꯣ ꯑꯩꯅꯥ ꯈꯉꯗꯦ.',
  ],
  chr: [
    'ᏑᎾᎴᎢ ᎤᏴᏢ ᎨᏎᎢ, ᎾᏍᎩ ᎢᏳᏍᏗ ᎤᏗᎴᎩ ᎠᏗᏔᏍᏗ ᎠᎩᏗᏔᏅᎩ.',
    'ᏂᏚᎩᏨᏂᏓᏒ ᏚᎳᏍᎬ ᎠᎢᏒ ᏗᎦᎸᏫᏍᏓᏁᏗ.',
    'ᎥᏝ ᏥᎦᏔᎲᎾ ᎯᎠ ᏂᎦᏅᏅ ᎭᏢ ᎠᎢᏒᎢ.',
  ],
  iku: [
    'ᐅᓪᓛᖅ ᓂᓪᓚᓱᒃᑐᖅ, ᑕᐃᒪᐃᒻᒪᑦ ᐅᖅᑰᑦᑐᒥᒃ ᑏᑐᖅᑐᖓ.',
    'ᐅᓪᓗᑕᒫᑦ ᐱᓱᒃᖢᓂ ᐃᖅᑲᓇᐃᔮᒧᑦ ᐱᓱᒃᑐᖅ.',
    'ᖃᐅᔨᒪᖏᑦᑐᖓ ᐊᖅᑯᑎ ᓇᒧᑦ ᐱᓯᒪᖕᒪᖔᑦ.',
  ],
  nqo: [
    'ߓߌ߬ ߛߐ߰ߡߊ߬ ߘߊ߬ ߛߎߡߦߊ ߞߊ߬ ߜߍߟߍ߲߫، ߒ ߞߊ߬ ߘߎ߬ߕߍ߬ ߜߏߟߏ߲߫ ߡߌ߲߬.',
    'ߊ߬ ߦߋ߫ ߕߊ߯ ߓߊ߯ߙߊ ߘߐ߫ ߛߋ߲߬ߠߊ߫ ߟߏ߲߫ ߏ߬ ߟߏ߲߫.',
    'ߒ ߡߊ߫ ߟߐ߲߫ ߛߌߟߊ ߣߌ߲߬ ߦߋ߫ ߕߊ߯ ߦߙߐ ߡߍ߲.',
  ],
  fuf: [
    '𞤖𞤢𞤲𞥋𞤣𞤫 𞤧𞤵𞤩𞤢𞤳𞤢 𞤶𞤢𞤲𞤺𞤵𞤣𞤫 𞤯𞤵𞥅𞤯𞤭, 𞤳𞤢𞤣𞤭 𞤥𞤭 𞤴𞤢𞤪𞤭 𞤷𞤢𞤴 𞤲𞤵𞤤𞥆𞤵𞤲𞤣𞤵.',
    '𞤳𞤢𞤲𞤳𞤮 𞤴𞤢𞤸𞤮 𞤴𞤢𞤸𞤢 𞤲𞤣𞤫𞤪 𞤺𞤮𞤤𞥆𞤫 𞤳𞤢 𞤳𞤵𞤴𞤣𞤫.',
    '𞤥𞤭 𞤢𞤲𞤣𞤢𞥄 𞤼𞤮 𞤤𞤢𞤱𞤮𞤤 𞤲𞤺𞤮𞤤 𞤴𞤢𞤸𞤢𞤼𞤢.',
  ],
  zgh: [
    'ⴰⵙⵙ ⴰⴷ ⵜⵉⴼⴰⵡⵜ ⵜⴳⴰ ⵜⴰⵙⵎⵎⵉⴹⵜ ⴱⴰⵀⵔⴰ, ⵖⵉⴽⴰⵏⵏ ⵙⵡⵉⵖ ⴰⵜⴰⵢ ⵉⵣⵖⴰⵏ.',
    'ⵏⵜⵜⴰ ⵉⵜⴷⴷⵓ ⵙ ⵓⴹⴰⵕ ⵖⵔ ⵜⵡⵡⵓⵔⵉ ⴽⵓ ⴰⵙⵙ.',
    'ⵓⵔ ⵙⵙⵉⵏⵖ ⵎⴰⵏⵉ ⵉⵜⴷⴷⵓ ⵡⴰⴱⵔⵉⴷ ⴰⴷ.',
    'ⵉⵇⵇⴰⵏ ⴽ ⵉⴷ ⴰⴷ ⵜⴷⴷⵓⴷ.',
    'ⵉⵙⵙⵓⵙⵎ ⵉⵢⵉ ⵍⵍⵉⴳ ⴷⴷⵉⵖ ⵙ ⵜⵎⴰⵣⵉⵔⵜ ⵏⵏⵖ.',
    'ⵓⵙⵔⵖ ⴱⴰⵀⵔⴰ ⴽⵔⴰ ⵏ ⵜⵀⵉⵔⵉⵜ.',
    'ⵉⵙ ⵜⵙⵙⵏⴷ ⵉⵎⴰⵣⵉⵖⵏ ?',
    'ⵎⴰ ⵜⵙⵙⵏⴷ ⵅⴼ ⵉⵎⴰⵣⵉⵖⵏ ?',
    'ⵓⵔ ⵥⴹⴰⵕⵖ ⴰⴷ ⵙⴽⵔⵖ ⵢⴰⵜ ⵖⵉⵍⴰⴷ.',
    'ⵉⵏⵏⴰ ⵜⵓⵎ ⵎⴰⵙ ⵔⴰⴷ ⵉⵢⵉ ⵢⴰⵡⵙ ⴰⵔ ⴽⵉⵖ ⵓⴼⵉⵖ ⴰⵢⵍⵍⵉ ⵓⵙⵔⵖ.',
  ],
  gom: [
    'आज सकाळीं खूब थंडी आसली, देखून हांवें गरम चा पियेलों.',
    'तो दर दिसा चलत ऑफिसाक वता.',
    'हो वाठ खंय वता तें म्हाका खबर ना.',
  ],
  doi: [
    'अज्ज सबेरे बड़ी ठंड ही, इस करी मैं गरम चाह पीती.',
    'ओह् हर रोज़ पैदल ई दफ्तर जंदा ऐ.',
    'मिगी नेईं पता जे एह् राह् कुत्थें जंदा ऐ.',
  ],
  awa: [
    'आजु भिनसार बहुत जाड़ रहा, तेहि से हम गरम चाह पियेन.',
    'ऊ रोजु पैदले दफ्तर जात ह.',
    'हमका नाहीं पता कि ई रस्ता कहाँ जात ह.',
  ],
  new: [
    'थौं सुथय् तःधंगु खाउ जुल, अथेहे जिं तातुगु चा त्वना.',
    'वय्कः सकल दिं तुं ल्हाना कार्यालयय् झाइ.',
    'थ्व लँ गन वनी जिं मसिउ.',
  ],
  pnb: [
    'اج سویرے بہوں ٹھنڈ سی، ایس لئی میں گرم چاہ پیتی۔',
    'اوہ ہر روز پیدل ای دفتر جاندا اے۔',
    'مینوں نئیں پتہ کہ ایہہ راہ کتھے جاندا اے۔',
  ],
  prs: [
    'امروز صبح هوا بسیار سرد بود، از همین خاطر چای گرم نوشیدم.',
    'او هر روز پیاده به دفتر میرود.',
    'نمیدانم که این سرک به کجا میرسد.',
  ],
  bal: [
    'مرۏچی صباحا پُر سرد اَت، گڈا من گرم چاہ وارتُن.',
    'آ ھر روچ پیادگ دفتر ءَ شت کنت.',
    'من نزانان کہ ای راہ کجا ءَ شت کنت.',
  ],
  kas: [
    'اَز صُبحَس ژھ ٹھنڈ آسِتھ، تہٕ مےۭ چٲو گرٕم چاے۔',
    'سُہ گژھہِ پرٛتھ دۄہ پیدل دفترَس۔',
    'مےۭ چھُنہٕ پتہ زِ یہٕ وَتھ کۄت گژھان۔',
  ],
  arz: [
    'الصبح النهارده كان برد قوي، عشان كده شربت شاي سخن.',
    'هو بيروح الشغل ماشي كل يوم.',
    'مش عارف الطريق ده بيودي فين.',
  ],
  ary: [
    'هاد الصباح كانت البرد بزاف، علاحقاش شربت أتاي سخون.',
    'كيمشي للخدمة على رجليه كل نهار.',
    'ما عرفتش فين كيمشي هاد الطريق.',
  ],
  tat: [
    'Бүген иртә бик салкын иде, шуңа күрә мин кайнар чәй эчтем.',
    'Ул һәр көн эшкә җәяү бара.',
    'Бу юл кая илтә, мин белмим.',
    'Мин сәгать ничә икәнен белмим.',
    'Синең җавап дөрес.',
    'Бу җавап миңа бик ошый.',
    'Ни әйтергә дә белмим.',
    'Моны эшләргә сине нәрсә мәҗбүр итте?',
    'Ул аңа ни дип җавап бирде?',
    'Көн артык салкын да, ләкин җылы да түгел.',
  ],
  bak: [
    'Бөгөн иртән бик һыуыҡ ине, шуға күрә мин ҡайнар сәй эстем.',
    'Ул һәр көн эшкә йәйәү бара.',
    'Был юл ҡайҙа алып бара, мин белмәйем.',
  ],
  chv: [
    'Паян ирхине питӗ сивӗччӗ, ҫавӑнпа эпӗ вӗри чей ӗҫрӗм.',
    'Вӑл кулленех ӗҫе ҫуран каять.',
    'Ку ҫул ӑҫта каять, эпӗ пӗлместӗп.',
    'Манӑн икӗ кушак пур.',
    'Санӑн икӗ кӗнеке пур.',
    'Эпӗ сана юрататӑп.',
    'Эпӗ паян пушӑ мар.',
    'Эпӗ ыран пушӑ мар.',
    'Вӑл акӑлчанла лайӑх калаҫать.',
    'Акӑлчанла манса кай.',
  ],
  sah: [
    'Бүгүн сарсыарда олус тымныы этэ, онон итии чэйи испитим.',
    'Кини күн аайы үлэтигэр сатыы барар.',
    'Бу суол ханна барарын билбэппин.',
  ],
  oss: [
    'Абон райсом тынг уазал уыд, уымæ гæсгæ æз тæвд цай баназтон.',
    'Уый алы бон дæр куыстмæ фистæгæй цæуы.',
    'Æз нæ зонын, ацы фæндаг кæдæм цæуы.',
    'Дæ зæрдæмæ цы нæ цæуы?',
    'Дæуæн диссаг у, æз дæр адæймаг кæй дæн?',
    'Йæ хъæлæс у тынг рæсугъд.',
    'Уый мæ зæрдæмæ нæ цæуы.',
    'Байрæджы дæн, æмæ мæ бахатыр кæнут.',
    'Ай япойнаг хæринаг у?',
    'Англисаг æвзаг дæ зæрдæмæ цæуы?',
  ],
  che: [
    'Тахана Ӏуьйранна чӀогӀа шело яра, цундела ас мела чай мелира.',
    'Иза массо а де болхе гӀаш воьду.',
    'Суна ца хаьа хӀара некъ мичахьа боьду.',
  ],
  bos: [
    'Jutro je bilo veoma hladno, pa sam skuhao vruć čaj.',
    'On svakodnevno pješke odlazi na posao.',
    'Ne znam kuda vodi ovaj put.',
    'Ko je ovaj čovjek?',
  ],
  oci: [
    'Aqueste matin fasiá plan freg, alara ai begut un te caud.',
    'Va a pè al trabalh cada jorn.',
    'Sabi pas ont mena aqueste camin.',
    'Un jorn de mei qu\'es passat.',
    'Lo men pair que beu cada jorn.',
    'Pendent tota la jornada, es estat en cèrca d\'una letra.',
    'Se pòt totjorn trobat temps.',
    'I a totjorn quauqu\'un que parla.',
    'Los dus jorns van plan.',
    'Estoc totjorn atau.',
  ],
  srd: [
    'Custu manzanu fiat meda fritu, duncas apo bufadu unu te callenti.',
    'Andat a pee a traballare dontzi die.',
    'Non isco ue portat custu caminu.',
  ],
  ast: [
    'Esta mañana facía muncho fríu, asina que tomé un té caliente.',
    'Va andando al trabayu tolos díes.',
    'Nun sé au lleva esti camín.',
  ],
  roh: [
    'Quest damaun faschev fitg fraid, perquai hai jau bavì in te chaud.',
    'El va mintga di a pe al lavur.',
    'Jau na sai betg nua che quest via mena.',
  ],
  fur: [
    'Vuê a buinore al faseve une vore frêt, cussì o ai bevût un tè cjalt.',
    'Al va a pît al lavôr ogni dì.',
    'No sai dulà che al puarte chest troi.',
  ],
  sme: [
    'Odne iđđes lei hui galbmat, danne jugan liekkas deaja.',
    'Son vázzá beaivválaččat bargui.',
    'In dieđe gosa dát geaidnu manná.',
  ],
  hsb: [
    'Dźensa rano bě jara zyma, tuž sym horcy čaj pił.',
    'Wón dźe kóždy dźeń pěši do dźěła.',
    'Njewěm, hdźe tuta puć wjedźe.',
  ],
  ibo: [
    'Ụtụtụ taa oyi na-atụ nke ukwuu, ya mere aṅụrụ m tii ọkụ.',
    'Ọ na-aga ọrụ ije kwa ụbọchị.',
    'Amaghị m ebe okporo ụzọ a na-eje.',
  ],
  aka: [
    'Anɔpa yi awɔw wɔ hɔ paa, enti menom tii a ɛyɛ hyew.',
    'Ɔnantew kɔ adwuma da biara.',
    'Minnim baabi a saa kwan yi kɔ.',
  ],
  wol: [
    'Ci suba si liir na lool, moo tax ma naan attaaya bu tàng.',
    'Dafay dem liggéey ci tànk bés bu nekk.',
    'Xamuma fu yoon wii jëm.',
  ],
  kin: [
    'Uyu munsi mu gitondo hari imbeho nyinshi, ni yo mpamvu nanyoye icyayi gishyushye.',
    'Buri munsi ajya ku kazi n’amaguru.',
    'Sinzi aho uyu muhanda ujya.',
  ],
  nya: [
    'M’mawa muno kunali kuzizira kwambiri, choncho ndinamwa tiyi wotentha.',
    'Amapita kuntchito wapansi tsiku lililonse.',
    'Sindikudziwa kumene msewu uwu ukupita.',
  ],
  sna: [
    'Mangwanani ano kwaitonhora zvikuru, saka ndakanwa tii inopisa.',
    'Anofamba netsoka achienda kubasa zuva rega rega.',
    'Handizivi kwainoenda mugwagwa uyu.',
  ],
  xho: [
    'Kusasa bekubanda kakhulu kakhulu, ngoko ndisele iti eshushu.',
    'Uhamba ngeenyawo esiya emsebenzini yonke imihla.',
    'Andazi ukuba le ndlela iya phi.',
  ],
  sot: [
    'Hoseng ho ne ho bata haholo, kahoo ke ile ka noa tee e chesang.',
    'O tsamaya ka maoto ho ya mosebetsing letsatsi le leng le le leng.',
    'Ha ke tsebe hore na tsela ena e ya kae.',
  ],
  tsn: [
    'Mo mosong go ne go tsidifetse thata, ka jalo ke nwele tee e e mogote.',
    'O tsamaya ka dinao go ya tirong letsatsi le letsatsi.',
    'Ga ke itse gore tsela e e ya kae.',
  ],
  lug: [
    'Ku makya kuno kwali kunnyogoga nnyo, bwentyo nnanywa caayi ayokya.',
    'Atambula n’ebigere okugenda ku mulimu buli lunaku.',
    'Simanyi luwa oluguudo luno gye lugenda.',
  ],
  lin: [
    'Na ntɔngɔ ya lelo malili ezalaki mingi, yango wana namɛlaki tii ya mɔtɔ.',
    'Atambolaka na makolo mpo na kokende na mosala mokolo na mokolo.',
    'Nayebi te epai nzela oyo ekei.',
    'Soki bolingi mpenza koyeba esika moko, bokoki kobima na nzela ya kala.',
    'Nayebi eloko te mpo na yango.',
    'Mikolo ezo ya eza na ba nzela mingi - pona na mayele.',
    'Nayebi ete ozali kobanga te.',
    'Okoki kolakisa ngai nzela ya malamu ?',
    'Nayebi soki mukie te.',
    'Nayebi bana mibali misusu.',
  ],
  bam: [
    'Bi sɔgɔma nɛnɛ tun ka bon kosɛbɛ, o de y’a to ne ye te kalaman min.',
    'A bɛ taa baara la senna don o don.',
    'Ne t’a dɔn sira in be taa yɔrɔ min na.',
  ],
  gaz: [
    'Har ganama bara akkaan qorree ture, kanaafuu shaayii hoʼaa dhuge.',
    'Guyyaa guyyaan miilaan hojiitti deema.',
    'Karaan kun eessa akka geessu hin beeku.',
  ],
  plt: [
    'Nangatsiaka be ny maraina, ka nisotro dite mafana aho.',
    'Mandeha an-tongotra mankany am-piasana isan’andro izy.',
    'Tsy fantatro izay alehan’ity lalana ity.',
  ],
  jav: [
    'Esuk iki hawane adhem banget, mula aku ngombe teh panas.',
    'Dheweke saben dina mlaku menyang kantor.',
    'Aku ora ngerti dalan iki menyang ngendi.',
  ],
  sun: [
    'Isuk ieu hawana tiris pisan, jadi kuring nginum entéh haneut.',
    'Manéhna unggal poé leumpang ka kantor.',
    'Kuring teu nyaho ieu jalan ka mana.',
    'aing teu nyaho manéh bakal ngalakukeun eta poe ieu.',
    'Aing nyaho aing teh bisa ngalakukeun ieu.',
  ],
  ceb: [
    'Bugnaw kaayo ganina buntag, mao nga nag-inom ko ug init nga tsa.',
    'Maglakaw siya padulong sa trabaho matag adlaw.',
    'Wala ko kahibalo asa padulong kini nga dalan.',
  ],
  ilo: [
    'Nalam-ek unay iti bigat, isu a nagin-inumak iti napudot a tsa.',
    'Magmagna a mapan agtrabaho iti inaldaw.',
    'Diak ammo no sadino ti papanan daytoy a dalan.',
    'Para iti ania daytoy?',
    'Sika kadi laeng ti addaan iti tulbek iti daytoy a ridaw?',
    'Dimo kadi kayat daytoy?',
  ],
  kmr: [
    'Vê sibehê pir sar bû, loma min çaya germ vexwar.',
    'Ew her roj bi peyatî diçe kar.',
    'Ez nizanim ev rê diçe ku derê.',
    'Ez nizanim ew çawa kar dike.',
    'Ez nizanim çi dixwazim.',
    'Bawer diçe dibistanê.',
    'Ji bîr neke, serê sibehê em ê biçin kar.',
    'Ez nizanim kî li mala me ye.',
    'Dilê min diçe goşt.',
    'Ez nizanim li vir çi bikim.',
  ],
  tuk: [
    'Bu gün irden howa örän sowukdy, şonuň üçin men gyzgyn çaý içdim.',
    'Ol her gün işe pyýada gidýär.',
    'Bu ýoluň nirä barýanyny bilemok.',
    'Men diýip bilemok.',
    'Men aýdyp bilemok.',
    'Meryñ ony näme üçin edendigini bilemok.',
    'Bu kitaby satyn alyp bilemok.',
  ],
  tet: [
    'Dadeer ohin malirin tebes, tan ne’e ha’u hemu xa manas.',
    'Nia la’o ba serbisu loron-loron.',
    'Ha’u la hatene dalan ne’e ba ne’ebé.',
  ],
  mri: [
    'He tino makariri te ata nei, nō reira i inu au i te tī wera.',
    'Ka hīkoi ia ki te mahi ia rā.',
    'Kāore au i te mōhio ki hea tēnei huarahi.',
    'Kāore au e hiahia ana ki te haere ki te kura.',
    'Kāore tērā i te pai ki a au.',
    'Ko tāku kurī tēnei.',
    'Kāore au e mōhio ki a ia.',
    'Kāore koe i hiahia ki noho ki a au?',
  ],
  smo: [
    'Sa malulu tele le taeao nei, o lea na ou inu ai se lauti vevela.',
    'E savali o ia i le galuega i aso uma.',
    'Ou te le iloa po o fea e alu i ai lenei auala.',
  ],
  ton: [
    'Naʻe momoko ʻaupito ʻa e pongipongi ni, ko ia naʻá ku inu ai ha tī māfana.',
    'ʻOku ʻalu haʻele ia ki he ngāue ʻi he ʻaho kotoa.',
    'ʻOku ʻikai te u ʻilo pe ʻalu ki fē ʻa e hala ni.',
  ],
  fij: [
    'E batabata sara na mataka nikua, o koya au gunuva kina e dua na tī katakata.',
    'E taubale ina cakacaka e veisiga.',
    'Au sega ni kila se lako i vei na gaunisala oqo.',
  ],
  haw: [
    'Ua anu loa kēia kakahiaka, no laila ua inu au i ke kī wela.',
    'Hele wāwae ʻo ia i ka hana i kēlā me kēia lā.',
    'ʻAʻole au i ʻike i hea e hele ai kēia alanui.',
  ],
  tpi: [
    'Long moning nau em i kol tumas, olsem na mi dringim hot ti.',
    'Em i wokabaut i go long wok long olgeta de.',
    'Mi no save rot ia i go we.',
  ],
  que: [
    'Kunan paqarin anchata chirirqan, chayrayku qʼuñi tiyata upyarqani.',
    'Paymi sapa punchaw chakillawan llamkʼaq rin.',
    'Manam yachanichu maytataq kay ñan rin.',
  ],
  aym: [
    'Jichhüru alwaxa wali thayawa, ukatwa juntʼu tiy umtʼawayta.',
    'Jupax sapüru kayuki irnaqawiruw sari.',
    'Janiw yatkti kawksatï aka thakhix sarki.',
  ],
  grn: [
    'Ko pyhareve iporã roʼy, upévare haʼu peteĩ té hakúva.',
    'Haʼe oguata káda ára mbaʼapohápe.',
    'Ndaikuaái moõpa ohoha ko tape.',
    'Mboy mbo\'ehao oĩ nde távape?',
    'Oĩ peteĩ óga guasu che távape.',
    'Upéva piko peteĩ mbarakaja térã peteĩ jagua?',
    'Che róga oĩ ko\'ápe.',
    'Jareko peteĩ jagua.',
    'Jareko peteĩ apañuái.',
    'Jareko peteĩ apañuái piko?',
  ],
  hat: [
    'Maten an te fè frèt anpil, se sa k fè m te bwè yon te cho.',
    'Li mache ale nan travay chak jou.',
    'Mwen pa konnen ki kote wout sa a mennen.',
  ],
  pap: [
    'E mainta aki tabata masha friu, p’esei mi a bebe un te kayente.',
    'E ta kana bai trabou tur dia.',
    'Mi no sa unda e kaminda aki ta bai.',
  ],
  kal: [
    'Ullaaq manna nillernarluinnarpoq, taamaattumik kissartumik teerpallaarpunga.',
    'Ullut tamaasa pisuttuarluni sulisarfimminut pisarpoq.',
    'Naluara aqqut una sumut ingerlasoq.',
  ],
  yue: [
    '今朝好凍，所以我飲咗杯熱茶。',
    '佢每日都行路返工。',
    '我唔知呢條路去邊度。',
  ],

  // Central and East Africa.
  run: [
    'Abantu bose bavuka bishira bakizana kandi bangana mu gateka no mu ngingo zibubahiriza.',
    'Umuntu wese ategerezwa kwubahirizwa n\'ugukingirwa mu buzima bwiwe, akishira akizana.',
    'Nta muntu n\'umwe azokubagurwa canke ngo acurwe bufuni na buhoro.',
    'Umuntu wese ategerezwa kwubahwa akubahirizwa aho ari hose.',
  ],

  // Central, East and Southern Africa.
  lua: [
    'Bantu bonsu badi baledibwa badikadile ne badi ne makokeshi amwe.',
    'Muntu yonso udi ne bukokeshi bwa kwikala ne bwena ditunga dyende.',
    'Muntu nansha umwe kena mwa kunyengibwa cintu cyanana nansha.',
    'Muntu yonsu udi ne bukenji bwa kwela meji ne kwakula mudiye muswe.',
    'Baledi badi ne bukenji bwa kusungula mushindu wa kukolesha bana babu.',
  ],
  kng: [
    'Woso mutu widi mswa kulonga mkanda.',
    'Woso mutu widi luve ayi mswa kudyata ayi kutomba nzo mu yoso-kwa tsi.',
    'Kwisi-ko mutu m’tisu mu ngolo kukota mu kithwadi.',
    'Woso mutu widi mswa kuzinga, ku-yi-yadila na veka mu kimpwanza ayi kuzinga mu lufiatu.',
    'Masya badi na luve lu kusobudila bana bawu phila nzo-mkanda bafwene.',
  ],
  kmb: [
    'O athu woso avwala abhuluka ni kusokela mu kijingu ni mu itekelu.',
    'Muthu woso wala kutokala o kivwaluke kimoxi.',
    'Seku muthu utena kukala ngho kumukatula o wenji we.',
    'Muthu oso wala kutokala o kubuluka mu kubanza, kilunji ni ngeleja.',
    'Muthu oso wala kutokala o kubuluka dya kudyongeka ni dya isangela ya tululuka.',
  ],
  umb: [
    'Omanu vosi valisoka kocihandeleko.',
    'Omunu eye omunu okwete omoko yelilongiso.',
    'Omunu eye omunu okwete omoko yeyovo lyonjango kwenda omunga yunu.',
    'Omunu eye omunu, ndañgo oco ale kowiñgi, okwete omoko yeci mwêle.',
    'Omunu eye omunu okwete omoko yeyovo lyokusokolola, olondunge kwenda etavo.',
  ],
  cjk: [
    'Muthu mweswe kanatela kupwa nyi cifuci cimwikha.',
    'Muthu mweswe, cipwe ukhaweni hanji munji, kanatela kupwa nyi cihela cenyi.',
    'Nyumwe yoze maha kumutambula kuthaci cihela cenyi.',
    'Muthu mweswe kanatela kuhana cyulo nyi kuhanjika liji ali nalyo.',
    'Muthu mweswe watela kulilongesa.',
  ],
  lue: [
    'Vatu vosena vasemuka yapwa hohamwe nakweseka mukuyoya chavo.',
    'Mutu wosena analusesa lwakutanga.',
    'Kala mutu analusesa lwakupwa mutu wamulifuchi kana.',
    'Kakwechi kukapwa kunyanga wupite wamutuko.',
    'Kakwechi kupwa kushinjila mutu kwingila muchikungulwiloko.',
  ],
  lun: [
    'Muntu wejima natweshi kusemukila kwitung\'a kudi kwejima.',
    'Kosi muntu akatambulawu maheta chakadi kuchikeng\'a omweni.',
    'Muntu wejima wenkewa ing\'ovu jakudiwana nawakwawu muyipompelu.',
    'Muntu wejima amwinka ing\'ovu jakuya kushikola nakutang\'a.',
    'Kosi muntu akahembawu chineyi indung\'u hela kwikala indung\'u.',
  ],
  kqn: [
    'Bonse bantu basemwa bakasuluka kabiji baesakena pamo mubuneme.',
    'Yense muntu uji na nsambu ya kwikala na bumi, wakasuluka kabiji wavimbilwa.',
    'Yense wafwainwa kutambula bwina kyalo.',
    'Yense uji na nsambu ya kupwila pamo na bakwabo.',
    'Bansemi baji na luusa lwakusajila bana babo lufunjisho.',
  ],
  bem: [
    'Abantu bonse bafyalwa abalubuka nokulingana mu mucinshi nensambu.',
    'Takuli nangu umo ukuba umusha nangu mu busha.',
    'Onse alikwata insambu yakuba no mutundu.',
    'Onse alikwata insambu yaku sambilila.',
    'Tapali ali nakupokwa ifipe kumaka.',
    'Onse alikwata insambu yakwenda nokwikala konse uko atemwa mu calo aikala.',
  ],
  toi: [
    'Muntu oonse ulaangulukide kubukkale bwabuumi, lwaanguluko alimwi akukwabililwa.',
    'Oonse muntu ulaangulukide kuba munacisi wacisi ncayanda kukkala.',
    'Kunyina weelede kunyonganizyigwa antela kunyangwa lubono lwakwe.',
    'Muntu oonse ulaangulukide kuba mukabunga antela kubungana kwaluumuno.',
    'Kunyina weelede kusungilizyigwa kuba mukabunga nkatayandi.',
  ],
  loz: [
    'Batu kaufela ba pepilwe inge ba lukuluhile ni liswanelo ze swana.',
    'Mang\'i ni mang\'i u na ni swanelo ya ku pila, ku lukuluha ni silelezo.',
    'Ha kuna ya ka amuha mutu libiana za hae.',
    'Mutu kaufela u na ni swanelo ya ku kopana ni batu ba bang\'wi.',
    'Mutu kaufela u na ni swanelo ya ku kena sikolo ni ku ituta.',
  ],
  ndo: [
    'Aantu ayehe oya valwa ye na emanguluko noye na ondilo yi thike pamwe osho wo uuthemba.',
    'Omuntu kehe oku na uuthemba wuukwashigwana.',
    'Omuntu kehe oku na uuthemba wokulongwa.',
    'Hamuntu ta kwatwa owala nenge te edhililwa nenge ta yi muupongekwa pwaa na omatompelo.',
    'Omuntu kehe oku na uuthemba wokuninga iigongi mombili nekwatathano naantu.',
  ],
  sag: [
    'Zo ôko alîngbi tî dutï na gbe tî ngbâa pëpëe.',
    'Amû na zo kûê ngangü tî mändängö mbetï.',
    'Zo kûe ayeke na ngangü tî fonon yamba na yâ tî ködörösêse kûê.',
    'Alîngbi pëpëe tî gbû zo na ngangü tî lï na yâ tî mbênî bôsôngbi.',
    'Amû na zo kûê ngangü tî zarä tî bibê na tî särängö tënë.',
  ],
  suk: [
    'Buli munhu alina Sekge ya gupandika isoma.',
    'Buli munhu alinayo Sekge ya gumanhya na banhu bangi mu lubango.',
    'Buli munhu adadakililwe gutajiwa nsabo jakwe bo gwibonelwa.',
    'Hangi, alinawiyabi bo gushoka hangi mu nsi yakwe.',
    'Buli munhu alina wiyabi bo gupelela nsi yingi atizubulagwa.',
  ],
  nym: [
    'Kila munhu wina haki ya kubi na nsi.',
    'Kila munhu wina haki ya kupelela nsi yingi ulu watulagwa akabulagwe.',
    'Nduhu munhu uyo alagaganiziwe kusanja na bangi.',
    'Kila munhu wina haki ya kutumamilwa na nsi yakwe.',
    'Banhu bose bubyalagwa biyagalulile, n’ikujo haki zilenganelile.',
  ],
  nyn: [
    'Omuntu aine okubaho omu muringo gwari kusiima.',
    'Tihariho muntu oshemereire kukwatirwa omubuhuuku.',
    'Buri muntu ashemereire kutwazibwa nk\'omuntu omu mbuga zebiragiro.',
    'Tihariho muntu nomwe orikukakwa kugyenda omu nkungaana nabandi.',
    'Buri muntu naatekwa kutuunga obwegyese.',
    'Omuntu aine obugabe, kwetungira ebye wenka narishi kubitungira hamwe nabagyenzi be.',
  ],
  vmw: [
    'Wakunla mutthu ohaana edireito yosoma.',
    'Khavo onrowa okhottihiwa etthu yawawe.',
    'Khavo onkelihiya va muthukumano ehitthunale mwanene.',
    'Atthu othene t’olikana variyari va elei, n’atthu othene attitthimihiweke n’elei.',
    'Wakunla pinatamu ohaana edireito ya ekumi, eliberdade ni wakiha erutthu awe.',
  ],
  kde: [
    'Vanu vohevohe vaidile n’chilambo valendene.',
    'Munu avele na wasa wa kutongola palikuwa.',
    'Munu avele na wasa wa kukojana na vanu vanji weka au mmakuwa.',
    'Munu vakampokonyola chihi dimali dyake.',
    'Munu na kaya yake ave na wasa wa umi wa mbone.',
  ],
  yao: [
    'Wandu wosope akasapagwa ni ufulu ni uchimbichimbi wakulandana.',
    'Mundu jwalijose akwete ufulu wakulijinganya.',
    'Mundu akasasumulikwa chipanje chakwe.',
    'Mundu jwalijose awonekwe mpela mundu pa malamusi ga kwinekulikose.',
    'Mundu akasawa kapolo kapena kamulisikwa masengo mpela kapolo.',
  ],
  nso: [
    'Batho ka moka ba belegwe ba lokologile le gona ba na le seriti sa go lekana le ditokelo.',
    'Mang le mang o na le tokelo ya bophelo, tokologo le tšhireletšo ya gagwe.',
    'Ga go motho ya a swanetšego go swarwa bjalo ka lekgoba goba mohlanka.',
    'Mang le mang o na le tokelo ya thuto.',
    'Ga go yo a ka amogwago phahlo ka mabaka a go se kwagale.',
  ],
  tso: [
    'Munhu ni munhu à ni nfanelo ya wutòmi, nkhululeko ni usirhelèli.',
    'Munhu ni munhu à ni nfanele ya ku lumba tiku.',
    'Wihi na wihi à ni nfanelo ya ku kuma ku djondza.',
    'À hava lweyi a fanelaka ku tekeliwa svilo svakwe na svi nga na masungulo.',
    'Wihi na wihi à ni nfanelo ya kuhloniphiwa svanga munhu phambhèni ka nawu.',
  ],
  ssw: [
    'Bonkhe bantfu batalwa bakhululekile balingana ngalokufananako ngesitfunti nangemalungelo.',
    'Wonkhe umuntfu unelilungelo lebuve.',
    'Kute umuntfu longemukwa buve bakhe nobe afuna kubugucula.',
    'Wonkhe umuntfu unelilungelo lekufinyelela emfundvweni.',
    'Kute umuntfu longemukwa imphahla yakhe ngalokungekho emtsetfweni.',
  ],
  ven: [
    'Vhathu vhoṱhe vha bebwa vhe na mbofholowo nahone vha tshi lingana siani ḽa tshirunzi na pfanelo.',
    'Muthu muṅwe na muṅwe u na pfanelo ya vhutshilo, mbofholowo na tsireledzo ya muthu.',
    'A hu na muthu ane a ḓo farwa, u valelwa kana u shakuliswa hu si na tshiitisi.',
    'Muthu muṅwe na muṅwe u na pfanelo ya pfunzo.',
    'A hu na ane a ḓo kombetshedzwa u vha muraḓo wa nyanḓano.',
  ],

  // West Africa.
  pcm: [
    'Nobodi get right to seize di propati of anoda person.',
    'Say dem no go gree at all, at all, no mata how e be.',
    'Na dat, goment go take de rule di people.',
    'Make dem say e no fit change to di kontri wey e like and make e call im own.',
    'Di law of our kontri must to make sure say notin happen to am.',
  ],
  kri: [
    'Evribɔdi fɔ ebul fɔ liv in layf, fɔ fil fri ɛn fɔ fil sɛf se nɔbɔdi ɔ natin nɔ go denja in layf.',
    'Nɔbɔdi nɔ fɔ arɛst, jel ɔ drɛb ɛni pɔsin kɔmɔt na in yon kɔntri jɛs bikɛs i fil fɔ du so.',
    'Wetin di pipul dɛn want nain di gɔvamɛnt fɔ du.',
    'Dɛn fɔ gɛt di sem rayt as maredman ɛn mareduman, ivin if di mared brok sɛf.',
  ],
  kea: [
    'Tudo individe tem drêto di tem sê nacionalidadi.',
    'Tudo péssoa tem drêto pa tem educaçon.',
    'Ninguêm podi ser obrigado pa fazê parte di calquer associaçon.',
    'Salário igual pa trabadjo igual.',
    'Pai co mai tem prioridadi di tem drêto pa scodjê calquer educaçon pâ dâ sês fidjo ô fidja.',
  ],
  ewe: [
    'Woade bubu amesiame ŋu le afisiafi abe amegbetɔ ene le se la nu.',
    'Womatsɔ akpasesẽ axɔ ame aɖeke ƒe nunɔamesi si le esi la o.',
    'Womazi ame aɖeke dzi be woanɔ habɔbɔ aɖe me o.',
    'Mɔnukpɔkpɔ li na amesiame be wòaxɔ hehe.',
    'Wodzi amegbetɔwo katã ablɔɖeviwoe eye wodzena bubu kple gomekpɔkpɔ sɔsɔe.',
  ],
  fon: [
    'Gbɛtɔ ɖokpoɖokpo ɖo na mɔ gbɛ bo nɔ eɖesu si lo bo na lɛ nyi eɖee.',
    'Nǔ é nyi étɔn ɔ mɛɖe sixu tafu i ɖu bo yi ɖo asi tɔn ǎ.',
    'E sixu sɔ mɛɖe do gbɛdemɛ gannu gannu ǎ.',
    'Gbɛtɔ bi ɖo acɛ bo na nyi toɖè sin vi.',
    'Gbɛtɔ ɔ nusisi wɛ ɖo na nyi ɖo fi bi.',
  ],
  gaa: [
    'Mɔ fɛɛ mɔ yɛ hegbɛ akɛ ena skul tsɔsemɔ.',
    'Esaaa akɛ anyɛɔ mɔ ko nɔ koni ekɛ ehe abɔ ku ko.',
    'Esaaa akɛ ashɔ̃ɔ mɔ diɛŋtsɛ nii ni eyɔɔ yɛ edɛŋ bɔ ni mla eŋmɛɛɛ gbɛ.',
    'Mɔ fɛɛ mɔ yɛ hegbɛ akɛ esusuɔ nɔ ko he bɔ ni esumɔɔ, ni ehaa aleɔ hu.',
  ],
  ada: [
    'Nɔ fɛɛ nɔ ngɛ ni kasemi he blɔ.',
    'Nɔ tsuaa nɔ sɔ ngɛ mlaa hɛ mi.',
    'Nɔ fɛɛ nɔ ngɛ he blɔ nɛ e tsuɔ ni tsumi nɛ e suɔ.',
    'Ngɛ mlaa nya a, abu nɔ fɛɛ nɔ kaa adesa ngɛ he fɛɛ he.',
  ],
  bci: [
    'Sran kwlakwla ɔla atin mɔ be kle i fluwa.',
    'Lika kwlakwla nga sran kun wo, ɔ fata kɛ be bu i sran, ɔ fin i mmla su.',
    'Be kwla\'a be mianmian-man sran kun ɔ wlu-man anuanzɛ kun nun.',
    'Be kwla\'a le\'a sran fi i ti bo nun like i sanun.',
    'Sran kwlakwla ɔ le atin mɔ ɔ nyen i auliɛ nvle',
  ],
  nzi: [
    'Sonla biala lɛ adenle sukoa nwoma.',
    'Ɔnle kɛ bɛyɛ awie biala kanra.',
    'Ɔnle kɛ bɛhyɛ sonla bɛmaa ɔkɔ eku nu.',
    'Sonla biala lɛ adenle kɛ ɔyɛ ekulomani.',
    'Ɔwɔ kɛ awie biala nyia ngoane, fanwodi nee sonla nwo banebɔlɛ.',
  ],
  mos: [
    'Ned buud fãa tara sor n tõe n paam kaorengo.',
    'B pa tõe n wõr ned n deeg a sẽn so ye.',
    'B pa tõe n modg ned ab a ye t\'a kẽ lagem-n-taar pʊgẽ ye.',
    'Pa tog n dɩk ninsaal buudã fãa n maan yamb ye bɩ n weoog-a ye.',
  ],
  dag: [
    'Bɛhig\' wuhiya ka dama soli kani ka so tooi bɔbi o kpee.',
    'Talahi n nyɛ li ni sokam tɔhi o bia sikuru.',
    'Soli kani ka so tooi yɛli ni o yu omaŋ n-ti yaɣi.',
    'Zaligu lan wuhi ni bɛ nam bɛhigu la sokam zuɣu.',
    'Suhizɔbo be sokam sani; ka nambɔɣu beni.',
  ],
  tiv: [
    'Hanmaor ngu a ian u nyôron makeranta.',
    'Hanmaor ngu a ian u lun a kwagh sha tseeneke u nan, shin zuan ave a ior mbagenev.',
    'Hanmaor ngu a ian i zan hanpe nan soo cii, man teman ya pe nan soo ken tar u nan.',
    'Makeranta una wase mtem u akuraior sha won cii, ken bem man mcivir-aôndo vev.',
  ],
  ibb: [
    'Owo ekededi enyene unen ndibo ifiok nwed.',
    'Owo inyeneke ndisin owo ndomokiet ke idak ndutuho ye ibak.',
    'Owo kiet kiet enyene unen ndidu uwem, ndiyene uboho ye ukpeme.',
    'Owo ekededi enyene unen ndikere nyun ntin se enye amade.',
  ],
  bin: [
    'Domwande-omwan mween etin ne o ya gha rro, ne o gbare ne o yaan egbe ere ke ugue omwan.',
    'Domwande-omwan mween etin na ya ye ero vbe odaro uhi vbe eheikeihe ne o rhirhi gha ye.',
    'Ai khian ye etin mu omwanikomwan ne o debaa otu okpa.',
    'O kere ne domwande-omwan rue ebe.',
  ],
  sus: [
    'Kankan xa adamaya daxa axa kolon yire birin.',
    'Baloe wayibiya birin bɛ, marafulunyi nun xaxilisa.',
    'Mixi ɲiya mu naxan yama.',
    'Futi mu nɔma sode fo ginɛ nun xamɛ lan fe keren ma.',
    'Ndende mu karaxan ma sofera lanxundɛ nde yama.',
  ],
  emk: [
    'Mɔɔ bɛɛ ka kan ka kɛ jamana dɔ jamanaden di.',
    'Karan saara fɔlɔ ye wajibi le di bɛɛ ye.',
    'A dahani denbatiilu ye ka alu den bila karan na, karan mɛn duman alu ye.',
    'Mɔɔ si bolo fen ma kan ka mina a la fanka bolo ma.',
    'Adamadennu bɛɛ sɔdɔnɲa kakan, hɔrɔya dɔ, fabadenɲa dɔ ani sariya ta fan dɔ.',
  ],
  snk: [
    'Sere su raawa soro kappa me man na fedde taaxundi.',
    'I ra nta sere naabure buusunu a yi xafu kanma.',
    'Sere su nan siri kappa jamaane soron ŋa.',
    'Sariyan nan siri sere su tangana katta kun baqe, ken xa wa kappa sere su taqu.',
  ],
  men: [
    'Nuu gbi lɔnya mia kɔɔ i wote a ndɔlɔlii.',
    'Numu gbi lɔnya mia kɔɔ i kɔlɔ gaa.',
    'Tɛ nuu gbi haaka gbua ngi yeya kia leke ti longɔla.',
    'Maa houngɔ sawei i nuu gbi maawɛɛ yɛɛ kakpamɛi ji bondayeya.',
  ],
  tem: [
    'Wuni o wuni ɔ ba ʌmari ma kʌgbukɛ ɔ kɔ mʌnknɛ rʌ ʌthɔf ʌlɔm, kʌmʌ a te dif kɔ.',
    'Wa ɔ ba ʌmari ma kʌshinkar ʌŋdina ɔ yema, yi mʌlanɛ mɔŋ.',
    'Ɔwa ɔ ba ʌmari ma kʌsɔŋ kɔ ʌlɔkɔ mɔ fothanɛ ʌlɔkɔ o lɔkɔ.',
  ],
  srr: [
    'Oxuu refna a wara jang.',
    'O leng waraanal o fañit o jeg um.',
    'O leng waraand o jibin na fog ni mbokatoor.',
    'Oxuu refna luwaa waraam o maakooy boo baa nandu neen a daawom.',
    'Oxuu refna a waaga sutoox saax a nomtooxiid boo no saax of.',
  ],
  dyo: [
    'Anoosan nababaj druwa ebaj burok básuumoo.',
    'An letuŋoolen ubot fubaj fati ata fo di mée.',
    'An letuŋoolen unoken an di káfa yanamaŋut.',
    'Anoosan nababaj druwa kakaraŋ an awarut acaam kakaraŋ.',
  ],
  fuc: [
    'Neɗɗo kala ina jogii hakke jeyeede e leydi, woni jogaade ngenndi.',
    'Hay gooto fotaani e amdu e waawde haɗeede jeyi mum.',
    'Yimɓe fof poti e laamu ete poti fotde ndeendka e yeeso laamu.',
    'Jaŋde sukaaɓe ina foti wonde alay sago.',
    'Hay gooto fotaani waawneede jeyeede e fedde alay sago.',
  ],

  // South-East Asia, north-east India and the Pacific.
  mad: [
    'Sadajana oreng lahir mardika e sarenge drajat klaban hak-hak se dha-padha.',
    'Tadha\' oreng se kengeng etangkep, etahan otaba ebuang sawenang-wenang.',
    'Sabban oreng agadhuwi hak sala settong kewarganegaraan.',
    'Tadha\' oreng se olle erampas hartaepon secara sawenang-wenang.',
    'Sabban oreng agadhuwi hak olle pandhidhigan.',
  ],
  min: [
    'Sadonyo manusia dilahiakan mardeka dan punyo martabat sarato hak-hak nan samo.',
    'Tiok urang punyo hak untuak iduik, untuak mardeka, dan kasalamatan salaku manusia pribadi.',
    'Indak surang pun buliah ditangkok, ditahan atau diasiangkan sacaro sawenang-wenang.',
    'Indak surang pun buliah dipaso masuak suatu parkumpulan.',
    'Tiok urang punyo hak mandapek pandidikan.',
  ],
  ban: [
    'Sami manusane sane nyruwadi wantah merdeka tur maduwe kautamaan lan hak-hak sane pateh.',
    'Saluiring janma nenten dados kerampas padruwenannyane sakita karep.',
    'Saluiring janma maduwe hak kebebasan mapupul lan ngewangun sekha tanpa ngangge kekerasan.',
    'Saluiring janma nenten dados kapaksa mangda ngiring nyarengin sekha.',
    'Saluiring janma maduwe hak polih pendidikan.',
  ],
  bug: [
    'Degaga seddi tau wedding ri sessa na digaukang pappada olokoloe\'.',
    'Sininna rupa tau nappunai riasengnge kebebasang monro rilalenna seddi negara.',
    'Sininna rupa tauwe nappuna hak mancaji riaseng warga negara.',
    'Degaga seddi tau weddi dipassangangi tama rilalenna seddi assipulungenge.',
    'Sininna rupa tau nappunai hak paneddingi riasengnge massikola.',
  ],
  ace: [
    'Bandum manusia lahee bebah merdeka deungon hak ngon martabat nyang sama.',
    'Ngon akai taseumikee, ngon atee tameurasa bandum geutanyoe lagee syedara.',
    'Hak meukawen ngon meuchree pih hana pandang bangsa, warga neugara ngon agama.',
  ],
  iba: [
    'Semua urang diadai bebas enggau samarata ari segi pemulia enggau hak-hak.',
    'Lemai tu aku deka ngirup teh.',
    'Enti kitai lurus ati, kitai tentu bisi mayuh kaban.',
    'Aku makai diatu laban aku lapar.',
    'Iya nepan perau deka pulai ke rumah.',
    'Bisi siti batu besai antara tanah kitai.',
  ],
  hil: [
    'Ang tanan nga tao ginbun-ag nga hilway kag may pag-alalangay sa dungog kag katarungan.',
    'Ang kada isa may katarungan nga mabuhi, mangin hilway kag seguridad bilang isa ka tao.',
    'Ang tagsa tagsa may katarungan sa pagkabanwahanon.',
    'Wala sing sin-o man ang di matarong nga kuhaan sang mga pagkabutang.',
    'Ang tagsa tagsa may katarungan sa kahilwayan sa malinong nga pagtililipon kag paghiliupod.',
    'Wala sing sin-o man nga dapat piliton nga magpasakop sa isa ka asosasyon.',
  ],
  war: [
    'An paguripon ug an pamaligya o pagpalit hin mga uripon ha bisan ano nga paagi igindidiri gud.',
    'An kada usa may katadungan pagbaya han iya nasud, upod an iya kalugaringon ug pagbalik ngada hito.',
    'Diri mapipirit in usa ka tawo pagpiriton pagbulig hin usa nga kapunungan.',
    'An kada tagsa mayda katadungan ngada hin edukasyon.',
    'An mga kag-anak may katungod pagpili han klase nga edukasyon para han ira mga anak.',
  ],
  pam: [
    'Ding balang metung atin lang karapatang mie kalayan at kaligtasan antimong tau.',
    'Alang ninu man ing mipailalam ya king e makaturlirang pangarakap, pamipakulung o pamipaugse.',
    'Ing balang metung atin iyang karapatan anting memalen.',
    'Alang ninu mang makatuliran para ilako ra ing kayang pibandian.',
    'Ding balang tau atin lang karapatan at kalayan at makiaguman at maki-alu-bilu.',
  ],
  bcl: [
    'An gabos na tawo ipinangaking may katalinkasan asin parantay sa dignidad asin derechos.',
    'An lambang saro igwa nin derecho nin buhay, katalinkasan, asin seguridad nin pagkatawo.',
    'Mayo nin siisay man an ipapasairarom sa basta-bastang pagdakop, pagkulong o pagsobol.',
    'Mayo nin siisay man an basta-bastang kukuanan nin saiyang pagsasadiri.',
    'An lambang saro igwa nin derecho sa educacion.',
  ],
  pag: [
    'Saray tigri et baleg tan mabiskeg nen saray pusa.',
    'Anggapo so arun ya aso so baleg nen saya.',
    'Say gawaen mo labat et nantepet.',
    'Agko amta.',
    'Iner so laen mo?',
  ],
  kha: [
    'Ïa ki bynriew baroh la kha laitluid bad ki ïaryngkat ha ka burom bad ki hok.',
    'Uwei pa kawei ki don ka hok ban im, ban ioh laitluid bad ban ïoh jingïada.',
    'Ym don uwei ne kawei ki ban shah kem, shah set slung ne shah pynryngkangpar be-aiñ.',
    'Uwei pa kawei ki don ïa ka hok jong ka jinglong trai shnong.',
    'Ym don uwei ne kawei ki ban shah pynbor ban long dkhot ha kano kano ka seng.',
    'Uwei pa kawei ki don ka hok ban ïoh ïa ka jingnang jingstad.',
  ],
  lus: [
    'Mitinte hian khawi hmunah pawh dan hmaah chuan mi pangngai anga enkawlna dawn hi kan chanvo a ni.',
    'Mi tu pawhin mahni ram chhungah chuan zalên taka chêttlat leh inbenbel theihna hi a chanvo a ni.',
    'Mi tinin a ram mi leh sa nih theihna chanvo an nei a ni.',
    'Mi tumah a pawng atakin a rosum te hnehchhuh tur a ni lo.',
    'Mi tumah tihluihnain pawlah kan teltîr tur a ni lo.',
    'Zirna hi mitinte chanvo a ni a.',
  ],
  cnh: [
    'A ho paoh mi vialte nunnak nawl, zalong tein umnak le himte le thlaphang lo tein umnak nawl kan ngei dih.',
    'Mi zeihmanh upadi hmai ah minung pakhat a sinak kha theihhngalhpiak ding a si lai.',
    'Ahohmanh upadi ning loin tlaihkhihnak, thongthlaknak le ram chungin chuahternak kha an inter lai lo.',
    'Mi vialte hna cu ram pakhat i ram chungmi sinak nawl a ngei.',
    'Mi vialte hna nih cacawn khawhnak nawl kan ngei dih.',
  ],
  tah: [
    '\'E ti\'amanara\'a to te ta\'ata-tupu ato\'a i te ora, i te ti\'amāra\'a e i te orara\'a pano\'ono\'o \'ore.',
    '\'E ti\'amanara\'a to te ta\'ata-tupu ato\'a i te hō\'ē ti\'ara\'ava\'a\'ai\'a.',
    '\'Eiaha roa te ta\'ata ia fa\'a\'erehia ma te ti\'amā \'ore i to na ti\'ara\'afatu.',
    '\'Eiaha roa te ta\'ata ia fa\'ahepohia no te fa\'ao atu i roto i te hō\'ē pupu-tā\'ātira\'a.',
    '\'E ti\'amanara\'a to te ta\'ata ato\'a i te ha\'api\'ira\'a.',
  ],
  rar: [
    'E tikaanga to te tangata tatakitai i te ora, te tikaanga tamanamanata kore ia e te oraanga paruru ia.',
    'E tikaanga to tetai uatu tangata i te akaruke i tetai uatu enua, ma tona uaorai, e te oki ki tona enua.',
    'Auraka rava tetai uatu tangata kia akangere taukore ia i tana au apinga.',
    'Auraka tetai uatu tangata kia maro ia kia piri ki tetai taokotaianga.',
    'E tikaanga to te katoatoa ki tetai apiianga.',
  ],
  niu: [
    'Monuina e pogipogi.',
    'Ko hai e higoa haau?',
    'Kamata e gahua haau he hola fiha?',
    'Fakaalofa lahi atu!',
  ],
  cha: [
    'Todo mangai derecho pot linala, libertad yan seguridad i persona.',
    'Todo man gai derecho na ufan marecognisa maseha mano como persona gi menan i lai.',
    'Taya sina na sometido nu i arbitrario na inaresta, detension pat destierro.',
    'Taya ni uno sina arbitariomente ma amot nui properdadna.',
    'Taya sina maobliga para uhalong gi un asociasion.',
    'Todo man gai derecho nui educasion.',
  ],
  mah: [
    'Kajojo armij eor an anemkwoj bwe en itoitaik ak jokwe ilo kajojo lol.',
    'Kajojo armij eor an maron bwe en eor an lol.',
    'En ejelok armij en rej boki men ko mweien jen e kin kilan jeb.',
    'En ejelok armij emwij kiele bwe en ber im uaan juon drolul.',
    'Kajojo armij eor an maron in bukot jelalokijen.',
  ],
  pau: [
    'Ar bek \'l chad a ngarngii a llemeltir ra klengar, ma ilmokl, ma budech ra klechad er tir.',
    'Ngdiak a chad el ngidil mudechem ra di diak a uchul, melechub eng mechesimer, malechub eng modik ra beluu.',
    'Ar bek \'l chad a ngarngii a llemeltir \'l mo oubeluu.',
    'Ngdiak a chad el morimel \'l mo chedal a ngidil cheldebechel.',
    'Ar bek \'l chad a ngarngii a llemeltir \'l mora skuul.',
  ],
  bis: [
    'Evri man mo woman i bon fri mo ikwol long respek mo ol raet.',
    'Evriwan i gat raet blong narafala man i luksave hem olsem wan man o woman we i stap anda long loa.',
    'Evriwan i gat raet blong gat wan nasonaliti.',
    'Wan man o woman i no save fosem narafala man o woman blong stap long wan asosiesen.',
    'Evriwan i gat raet blong kasem edukeisen.',
    'Bambae evri pikinini i mas go long wan elementeri skul.',
  ],

  // Regional Europe and the Americas.
  nds: [
    'All de Minschen sünd frie un gliek an Wüürd un Rechten baren.',
    'Elk un een hett dat Recht up Leven, Frieheit un Sekerheit vun de Persoon.',
    'Keeneen dröff ahn Grund sien Egendoom wegnahmen warrn.',
    'All Minschen sünd gliek vör dat Gesett.',
  ],
  sco: [
    'Awbody hes the richt tae life, liberty and security o person.',
    'Naebody shal be gart thole wulsome arrest, detention nor exile.',
    'Awbody hes the richt tae awn gear his lane as weel as in commonty.',
    'Naebody shal be hauden in thirldom or slavery; slavery and the slave trade shal be prohibit in aw their forms.',
  ],
  vec: [
    'Tuti i essari Umani nasse liberi e uguaƚi in teƚa dignità e diriti.',
    'I xe dotai de raxón e de cosiensa e i gà da agire cò spirito de fraternità lun l’altro.',
    'Ogni individuo gà dirito aƚa Vita, aƚa Libertà, e aƚa Sicuressa personaƚe.',
    'Nissun pòl essar arbitrariamente arestà, detenudo, ne esilià.',
    'Nessun pòl essar sotoposto a tortura né a pene o trattamenti crudeƚi, inumani o degradanti.',
  ],
  wln: [
    'Chaskeun\' a l\'dreût a \'ne nacionålité.',
    'Nolu n\'pout-èsse fwèrci dè fé pårtèye d\'ine associåcion.',
    'Chaskeun\' a l\'dreût d\'aler è scole.',
    'On n\'pout r\'prinde sès bins a nolu, sins bone rêzon.',
    'Tot l\'monde, seûye-t-i a lu tot seû ou bin avou dès-ôtes, a l\'dreût d\'aveûr dès bins.',
  ],
  cos: [
    'Hà dirittu ogni persona à a vita, à a libertà è à a sicurezza.',
    'Ugnunu hà dirittu à una naziunalità.',
    'Un’ pò essa nimu arristatu, incarciaratu o esiliatu di modu tirannicu.',
    'Pussedinu a raghjoni è a cuscenza è li tocca ad agiscia trà elli di modu fraternu.',
    'Ogni parsona hà dirittu à a libertà di riunioni è d’associu pacificu.',
  ],
  gag: [
    'Herbir insanın var vatandaşlık hakı.',
    'Herbir insanın yaşamak, serbestlik hem kışiliinä dokunmamak hakı var.',
    'Kimseyin elindän zakonsuz mal diil lääzım alınsın.',
    'Herbir insanın var üürenmäk hakı.',
    'Herbir insanın var hakı mal saabisi olmaa tek başına yada başkasınnan birliktä.',
  ],
  lim: [
    'Ich weit \'t neet!',
    'Ich versjtaon neet.',
    'Ich höb noe get tö doon.',
    'Gelökkige verjaordaag!',
    'Wieveil is dit?',
  ],
  scn: [
    'Mi piaciunu assai i ricordi dû passatu.',
    'Iddu è cuntentu cu so travagghiu.',
    'I cuntadini sunnu mpignati a travagghiari nte tirreni.',
    'Ci sunnu sempri assai dumanni.',
    'Àiu bèni manciàtu.',
  ],
  nap: [
    'Nisciuno è nato mparato.',
    'Chella matina faceva tantu friddo ca m\'aggio avuto accattà nu cappotto.',
    'M\'arricordo quanno ero piccerillo e giocavo cu \'e frate mieje ncoppa \'a spiaggia.',
    '\'O pane cu\' l\'oglio è \'na mangiata assaje sana e economica.',
    '\'E nonne amano vedé \'e nipute \'e jocà e \'e rire.',
  ],
  lij: [
    'Se doman ceuve se ne stemmo in cà.',
    'O tempo perso o no s\'accatta ciù.',
    'No pòsso ciù tegnî e parpelle averte.',
    'Tutta l\'ægua a l\'ammòrta o feugo.',
    'Unna vòtta gh\'ea un figgeu.',
  ],
  pms: [
    'Se doman a pieuv i staroma a cà.',
    'I sai nèn përchè ch\'i dev fé sòn-sì.',
    'A l\'é pròpe na bon-a ideja.',
    'Chiel a l\'é lontan da cà.',
    'I peul nèn ësté sensa cafè dòp mangià.',
  ],
  frr: [
    'Ik weet ek, hur ja sen.',
    'Hi drinkt ark Miaren en Glees Weeter.',
    'Wü haa miaren niin Skuul.',
    'Deling wiar di See wārem.',
    'Ik haa din Breev jüster fingen.',
    'Hi aarbert ark Dai, fuarbüten en Sendaiem.',
  ],
  dsb: [
    'Pódaj mě pšosym cukor.',
    'Myslim se, až maš pšawo.',
    'Mója pśijaśelka móžo derje rejowaś.',
    'Twóje knigły su na bliźe.',
    'Wiźim twóju kócku w zagroźe.',
  ],
  csb: [
    'Mëszlã, że môsz recht.',
    'Jô móm psa a kòta.',
    'Lata chùtkò lecõ.',
    'Më mómë dosc wodë.',
    'Kòscół je wobeszłi lasami a jezorami.',
    'Wona je barzo snôżô.',
  ],
  szl: [
    'Jŏ go niy znōm.',
    'Na śniŏdanie jym chlyb z dżymym.',
    'Barzo piyknie dzisioj wyglōndŏsz.',
    'Jŏ mōm nadziejã, że to je prŏwda.',
    'Wielgie ryby niy jedzōm małych.',
  ],
  yua: [
    'Tuláakal máak sijnal u najmatmajil u kajtal tiʼ jumpʼéel kaaj.',
    'Mixmáak uchak u lukʼsik baʼal u tiʼal máak.',
    'Le yáax kaambaloʼoboʼ kʼanaʼan maʼ u tojoltik.',
    'Le yáax kaambaloʼoboʼ tuláakal máak tzaaj u kʼamik.',
  ],
  quc: [
    'Rajawaxik xuqe\' kakimulij kib\' che utzukuxuk ri loq\'ob\'al pa we uwachulew.',
    'Maj jun winaq ya\'tal ta chech kab\'an k\'ax chech, xuq kupatanij ta ne jun chik winaq we man kaya ta tojb\'al rech.',
    'Ronojel chi winaq ya\'tal chech kub\'ano, kutzukuj ri umeb\'a\'il putukelam xuqe pa junamam.',
    'Xaq xew tojom ri jun eta\'manik ri qas kuk\'iysaj uwach ri k\'aslemal.',
  ],
  cak: [
    'Man jun winäq ri manäq ta ütz nirichinaj jun ramaq\'il.',
    'Man jun winäq ri kan chöj ta xtimaj ri rub\'eyomäl chi re.',
    'Konojel winaqi\' tikirel nikimöl ki\' chuqa\' ütz nikitzob\'ajij ki\' pa rutzil.',
    'Konojel ri winäq k\'atzinel chi nikik\'ül ri tijonïk.',
    'Man jun winäq ri chöj ta nichuq\'ab\'äx roken pan jun moloj ri\'ïl.',
  ],
  kek: [
    'Chijunil li poyanam naru natzolok.',
    'Chijunil li poyanam naru twanq xtenamitul.',
    'Maani tamine\'q chiru waank sa\' junaq ch\'utam.',
    'Maani tamaq\'e\'q li k\'a\'aq ru re chiru chi maak\'a\'aq xyaalal.',
    'Chijunil li poyanam naru twaanq k\'a\'aq ru re, chi xjunesalil ut sa\' komanil.',
  ],
  mam: [
    'Kyaqiil xjaal at tokleen te tk\'u\'j tnam.',
    'Milaay tz\'ok chq\'eet jun xjaal tu\'n took tuj jun chenb\'il.',
    'Mi\'aal jun xjaal jaka tz\'el q\'iit aj teex taq\'umb\'een.',
    'Kyaqiil xjaal b\'a\'n tu\'n taq\'unaan b\'ix b\'a\'n tu\'n tjaaw tjayo\'n taaq\'un tu\'n tanq\'iin.',
    'Kyaqiilqe xjaal at kyokleen ti\'j anq\'ib\'il, kopib\'il b\'ix q\'uqb\'il k\'u\'j ti\'j kyxmilaal.',
  ],
  tzh: [
    'Spisil winiketik ay srerechoik te ya yayik tsobojel yu\'un jich ya xchapik sk\'opika.',
    'Spisil winiketik ay rerecho ya yich\'ik tojel te me pajal nax te yat\'elike.',
    'Spisil te winiketik ay srerecho te ya yich\' bijtesel ta nopjune.',
    'Spisil winiketik pajalme ya stak\' x-och ta ajwalinelil ta slumal k\'inal.',
  ],
  nav: [
    'Tʼáá ajiłtsoh íízhdoołtahgo bee haʼahootʼiʼ.',
    'Tʼáá ajiłtsǫh dooneʼé jílínígíí bee háhazʼą́.',
    'Tʼáá ájíłtsoh tʼáadooleʼé baa ntsíjíkeesgo bee hazdoodzihgo bee háhazʼą́.',
    'Tʼáá héídah éí doo íínízingo doo atah dooltʼeełdah.',
    'Ałchíní yázhí éí tʼáá íyisí tʼáá íídoołtah.',
  ],
  arn: [
    'Kom ce mvley ñi mogeleael, kisugvnew feleael ka yamniegeael.',
    'Iney rume gelay ñi xafkiñtuceael.',
    'Cem ce rume wezakamekegelayay, kupafkamekegelayay.',
    'Kom pu ce mvley kisu ñi gengeael, ka xokiñke ce ñi gengeael cemu rume.',
    'Kom pu ce pepi kimay fij cijkatun, cem ce rume kujilayay tañi kimam.',
  ],
  cab: [
    'Ka gürigia yuti lun gagaira lan.',
    'Siñati bafósurun gürigia lun lebélurun tidaun aban adámuri.',
    'Yuti lun ka gürigia larihin lau le lánibai luma le hánibai sungua luagu.',
    'Sun mutu aban habu tigíbugien lúrudu, ani yuti giñe tun lúrudu taríhin hau.',
    'Siñabai giñe badaürün luagu saragu dan luai le tídanbai lúrudu.',
  ],

  // Russia and the Caucasus.
  tyv: [
    'Кижи бүрүзү амыдырап-чурттаар, хостуг болур болгаш дээп болбас эргелиг.',
    'Кым-даа барымдаа чок хоругдалга, тудуп хоругдаашкынга азы ойладыышкынга таварышпас ужурлуг.',
    'Кижи бүрүзү тайбың чыыш болгаш каттыжыышкыннарның хосталгазынга эргелиг.',
    'Кым-даа кайы-бир каттыжыышкынга киреринге чыгатпас ужурлуг.',
    'Эге өөредилге албан болур ужурлуг.',
  ],
  alt: [
    'Кемди де тууразынаҥ олјолоорго, тударга эмезе сӱрерге јарабас.',
    'Оныҥ таҥынаҥ ла билелик јӱрӱмине тууразынаҥ кем де киришпес учурлу.',
    'Кажы ла кижи кажы ла ороон кеминде јайым јӱрер ле јуртап јадарга јерди талдап алар аргалу.',
    'Кажы ла кижи бойында јайым кӧрӱмдӱ ле оны јайым чыгара айдар тапэриктӱ.',
    'Баштамы ӱредӱлик кыйалтазы јогынаҥ болор учурлу.',
  ],
  kjh: [
    'Олардың сағынғаны паза арығ сағыс пар паза харындастар чіли тудынарға киректер.',
    'Пірдеене хулда поларға чарадылбинча; хул паза хулларны садығ хайдығ даа оңдайлығ чарадылбинча.',
    'Пірдеезін иреелирге алай чабал, кізі нимес чіли, пазынарға постың синін пілінгенін тезірерге чарадылбинча.',
    'Пірдеезіне чарадылбинча пойли аның ниме-ноо пылазарға.',
  ],
  mhr: [
    'Таче йӱштӧ огыл, лум ок лум.',
    'Пӧлемыште ӱдыр-влак шукын улыт.',
    'Мый айдем-влакым пеш йӧратем.',
    'Теҥгече йӱр йӱрын.',
    'Тудо шортын колтыш.',
  ],
  udm: [
    'Мон котькуд нунал султӥсько куатен.',
    'Мон сое яратӥсько, нош со монэ уг яраты.',
    'Кыӵе умой нунал!',
    'Сӥль туж ческыт.',
    'Черепахаослэн пиньёсыз ӧвӧл.',
  ],
  kpv: [
    'Ми олам керкаын.',
    'Сылӧн керкаыс станциясянь зэв ылын.',
    'Сійӧ менам машинаӧс босьтыс.',
    'Ме тіянӧс сэтшӧм регыд эг виччысь.',
    'Кӧні миянӧс автобусыс босьтас?',
  ],
  myv: [
    'Сон ней арась кудосо.',
    'Черепахатнень арасть пейть.',
    'Сон корты минек марто.',
    'Косо тетят важоди?',
    'Монь ули псакам.',
  ],
  xal: [
    'Нанд нег сән толь кергтә.',
    'Ширә деер альмн бәәнә.',
    'Би өдр болһн сурһульд йовһар йовнав.',
    'Эндр цасн орсн.',
    'Мини гер энд бәәнә.',
  ],
  kbd: [
    'Дыгъуасэ Том къыщалъхуа махуэт.',
    'Сэ мыбы сыкъеджэфыркъым.',
    'Кхъуей дапщэ уэ пшхар?',
    'Сэ сыхуейщ мыр сшхыну.',
  ],
  ady: [
    'Сэ еджапӏэм сэкӏо.',
    'Лӏыхэр ӏофшӏапӏэм макӏох.',
    'Зи сшӏагъэп.',
    'Пцӏы сыусыщтэп.',
    'Тэ къетэгъэблагъэгъ тиунэм.',
  ],
  ava: [
    'Гьадай яс дир яц йиго.',
    'Нижер эмен ворхатав вуго.',
    'Гьаб нужер чед буго.',
    'Гьава-бакъ жакъа цӏакъ лъикӏаб буго.',
    'Дица щибаб къоялъ босула чед.',
  ],
  lez: [
    'Зун михьиз адахъ галаз рази я.',
    'Абуруз чизва хьи за гьахъ лугьузва.',
    'И верчери саки гьар юкъуз какаяр гузва.',
    'Чун ина ава квез кюмек ийидайвал.',
    'Йикъа шумудра вуна незва?',
  ],
  krc: [
    'Бу юй тюйюлдю.',
    'Сен къайда джашайса?',
    'Тюнене школгъа къуру мен келдим.',
    'Къызымы кёрдюнгмю?',
    'Эртден ашхы болсун!',
    'Менге джукъларгъа барыргъа керекди.',
  ],
  kum: [
    'Бу уьй тюгюл.',
    'Сен къайда яшайсан?',
    'Тюнегюн школагъа тек мен гелдим.',
    'Мен ашбаз болуп ишлеймен.',
    'Сизге не тарыкъ?',
    'Къызымны гёрдюнгмю?',
  ],
};

/** Every sample for a language, or an empty array if it has none. */
export function samplesFor(code) {
  return SAMPLES[code] || [];
}
