/**
 * The sample sentences a Script round shows.
 *
 * Server only, and that is a rule rather than a habit: if the browser
 * held the whole corpus it could match the text on screen against it and
 * read off the answer before the guess. The round endpoint sends one
 * sentence and a sealed token, the same way the panorama game sends a
 * panorama id and never the coordinate.
 *
 * **Two sources.** The first sentences in each list were written for the
 * game: a cold morning, hot tea, walking to work, the same few meanings
 * in every language so the content could not leak the answer. There
 * were two or three of them per language and that was the whole corpus,
 * which meant anybody who played twice had read all of it.
 *
 * The rest come from **Tatoeba** (CC-BY 2.0 FR), which this file named
 * as the upgrade it wanted before anybody had fetched it: real
 * sentences written by speakers, tagged with the same ISO 639-3 codes
 * the game uses. `scripts/build-script-corpus.js` fetches and filters
 * them, and the filtering is most of the work, because a crowdsourced
 * corpus is not a curated one:
 *
 * - every character has to be in the language's own script, so a
 *   transliteration filed under the wrong code cannot get in;
 * - no digits in any script, no currency, no URLs, no quotes;
 * - every word has to be among the commonest few hundred its language
 *   has, which strips names in scripts with no capital letters to spot
 *   them by, and strips the unusual vocabulary a crowdsourced corpus
 *   collects along with it;
 * - Tatoeba's stock cast, Tom and Mary and the rest, is named and
 *   refused: they are the commonest words in the corpus rather than
 *   rare ones, so frequency alone never catches them;
 * - nothing may name a place, a language or a number, checked against
 *   the same list __tests__/geo/script.test.js checks against;
 * - and it has to carry one of the language's own markers and none of
 *   a rival's, so every sentence still teaches something on the reveal
 *   and no sentence hands a feature to the wrong language.
 *
 * What survives all of that is 461 sentences across 75 languages, on
 * top of the 415 that were here. The other 84 keep what they had:
 * Tatoeba is thin in Wolof and Tetum, and a filter loose enough to find
 * something there would be loose enough to let a place name through
 * somewhere else.
 *
 * **The curation rule, which matters more than the size of the pool:**
 * strip proper nouns. A sentence containing a city name answers itself,
 * and so does a digit, a currency symbol or a flag. Nothing here names a
 * place, a person or a number, and __tests__/geo/script.test.js checks
 * that rather than trusting it.
 */

export const SAMPLES = {
  hin: [
    'आज सुबह बहुत ठंड थी, इसलिए मैंने गरम चाय पी।',
    'वह हर रोज़ पैदल ही दफ़्तर जाता है।',
    'मुझे नहीं पता कि यह रास्ता कहाँ जाता है।',
    'उसके पास बहुत सारी इतिहास की किताबें हैं।',
    'मेरे पास एक कुत्ता है।',
    'यह मेरा कुत्ता है।',
    'मेरे पास ज़्यादा पैसे नहीं हैं।',
    'मेरी बीवी डॉक्टर है।',
    'उसे टीवी पर टेनिस देखना बहुत पसंद है।',
    'कल का मौसम कैसा होगा कहना मुश्किल है।',
  ],
  mar: [
    'आज सकाळी खूप थंडी होती, म्हणून मी गरम चहा घेतला.',
    'तो दररोज चालत ऑफिसला जातो.',
    'मला माहीत नाही की हा रस्ता कुठे जातो.',
    'टॉम काय विचार करत होता मला माहीत नाही.',
    'त्याला ते माहीत नव्हतं.',
    'टॉमला माहीत आहे का?',
    'माझा चहा कुठे आहे?',
    'कोणालाही माहीत नाही.',
    'काय करायचं मला माहीत आहे.',
    'ते मला माहीत नाही.',
  ],
  npi: [
    'आज बिहान धेरै जाडो थियो, त्यसैले मैले तातो चिया खाएँ।',
    'उनी हरेक दिन हिँडेरै कार्यालय जान्छन्।',
    'मलाई थाहा छैन यो बाटो कहाँ जान्छ।',
    'मेरो किताब यहाँ छैन।',
    'म पनि चिया पिउँछु ।',
    'यो काम गाह्रो छैन।',
    'मलाई टम मेरीको प्रेमी थियो भन्ने लाग्यो।',
    'भित्र ठाउँ खाली थियो ।',
    'टम बाहिर कसैलाई पर्खिरहेको थियो।',
    'म धेरै ठाउँ घुम्न चाहन्छु तर मसँग पैसा छैन।',
  ],
  bho: [
    'आज भोरे बहुते जाड़ा रहे, ओहसे हम गरम चाह पिअनी।',
    'ऊ रोज पैदले दफ्तर जाला।',
  ],
  mai: [
    'आइ भोरमे बड़ ठंढ छल, तेँ हम गरम चाह पिलहुँ।',
    'ओ रोज पएरे कार्यालय जाइत छथि।',
  ],
  ben: [
    'আজ সকালে খুব ঠান্ডা ছিল, তাই আমি গরম চা খেয়েছি।',
    'সে প্রতিদিন হেঁটেই অফিসে যায়।',
    'আমি জানি না এই রাস্তা কোথায় যায়।',
    'আমি বুঝতে পারছি না।',
    'এটি গুরুত্বপূর্ণ না।',
    'তোমাকে আমার অনেক কিছু বলার ইচ্ছে আছে।',
    'আমি একজন শিক্ষক ছিলাম।',
    'আমার ঘুমাতে যাওয়া উচিৎ।',
    'আমার থেকে তোমার অবস্থা অনেক ভালো।',
    'এর কারণ তুমি একলা হতে চাও না।',
  ],
  asm: [
    'আজি ৰাতিপুৱা বৰ ঠাণ্ডা আছিল, সেয়েহে মই গৰম চাহ খালোঁ।',
    'তেওঁ প্ৰতিদিনে খোজ কাঢ়িয়েই কাৰ্যালয়লৈ যায়।',
    'মই চিগাৰেট খাব পাৰোঁ নে?',
    'মোৰ কোনো সঁচা পছন্দ নাই।',
    'মই তোমাক ভাল পাওঁ।',
    'মই তোমাক ভাল পাইছিলোঁ।',
    'মই তোমাক বেয়া পাওঁ।',
    'মই আপোনাক বেয়া পাওঁ।',
    'মই তোমাক বেয়া পাওঁ!',
  ],
  pan: [
    'ਅੱਜ ਸਵੇਰੇ ਬਹੁਤ ਠੰਢ ਸੀ, ਇਸ ਲਈ ਮੈਂ ਗਰਮ ਚਾਹ ਪੀਤੀ।',
    'ਉਹ ਹਰ ਰੋਜ਼ ਪੈਦਲ ਹੀ ਦਫ਼ਤਰ ਜਾਂਦਾ ਹੈ।',
  ],
  guj: [
    'આજે સવારે ખૂબ ઠંડી હતી, તેથી મેં ગરમ ચા પીધી.',
    'તે દરરોજ ચાલીને જ ઓફિસ જાય છે.',
  ],
  ory: [
    'ଆଜି ସକାଳେ ବହୁତ ଥଣ୍ଡା ଥିଲା, ତେଣୁ ମୁଁ ଗରମ ଚା ପିଇଲି।',
    'ସେ ପ୍ରତିଦିନ ଚାଲି ଚାଲି ଅଫିସ ଯାଆନ୍ତି।',
  ],
  urd: [
    'آج صبح بہت سردی تھی، اس لیے میں نے گرم چائے پی۔',
    'وہ ہر روز پیدل ہی دفتر جاتا ہے۔',
    'ابھی بہت سارے کام رہتے ہیں۔',
    'میرا خیال ہے کہ ہم نہ ہی کوشش کرے تو بہتر ہے۔',
    'مگر بہت بہت مشکل ہے۔',
    'بہت کم جاپانی صحیح انگریزی بول سکتے ہیں۔',
    'ٹام نے مریم کو بتایا کہ وہ صحیح تھی۔',
    'مجھے اپنی زندگی اور پیسے سے بہت پیار ہے۔',
    'بہت خوبصورت نام ہے تمہارا۔',
  ],
  snd: [
    'اڄ صبح جو تمام سردي هئي، ان ڪري مون گرم چانهه پيتي.',
    'هو هر روز پيدل ئي آفيس ويندو آهي.',
  ],
  tam: [
    'இன்று காலை மிகவும் குளிராக இருந்தது, அதனால் நான் சூடான தேநீர் குடித்தேன்.',
    'அவர் தினமும் நடந்தே அலுவலகத்திற்குச் செல்கிறார்.',
  ],
  tel: [
    'ఈ రోజు ఉదయం చాలా చలిగా ఉంది, అందుకే నేను వేడి టీ తాగాను.',
    'అతను ప్రతిరోజూ నడిచే ఆఫీసుకు వెళ్తాడు.',
  ],
  kan: [
    'ಇಂದು ಬೆಳಿಗ್ಗೆ ತುಂಬಾ ಚಳಿ ಇತ್ತು, ಆದ್ದರಿಂದ ನಾನು ಬಿಸಿ ಚಹಾ ಕುಡಿದೆ.',
    'ಅವನು ಪ್ರತಿದಿನ ನಡೆದುಕೊಂಡೇ ಕಚೇರಿಗೆ ಹೋಗುತ್ತಾನೆ.',
  ],
  mal: [
    'ഇന്ന് രാവിലെ വളരെ തണുപ്പായിരുന്നു, അതുകൊണ്ട് ഞാൻ ചൂടുള്ള ചായ കുടിച്ചു.',
    'അവൻ എല്ലാ ദിവസവും നടന്നാണ് ഓഫീസിൽ പോകുന്നത്.',
  ],
  sin: [
    'අද උදේ හරිම සීතලයි, ඒ නිසා මම උණුසුම් තේ එකක් බිව්වා.',
    'ඔහු හැම දාම පයින්ම කාර්යාලයට යනවා.',
  ],
  arb: [
    'كان الجو باردا جدا هذا الصباح، لذلك شربت شايا ساخنا.',
    'يذهب إلى المكتب سيرا على الأقدام كل يوم.',
    'لا أعرف إلى أين يؤدي هذا الطريق.',
  ],
  pes: [
    'امروز صبح هوا خیلی سرد بود، برای همین چای داغ خوردم.',
    'او هر روز پیاده به دفتر می‌رود.',
    'من ژاپنی صحبت نمی‌کنم.',
    'هیچکس مرا درک نمی‌کند.',
    'به زودی بهار می‌شود.',
    'آنچه را به تو می‌گوید، باور نکن.',
    'با گفتن اشتباه کردم کار درست نمی‌شود.',
    'چند زبان را خوب می‌توانید صحبت کنید؟',
    'معمولاً با او به مدرسه می‌رفتم.',
  ],
  pbu: [
    'نن سهار ډېره یخني وه، نو ما ګرمه چای وڅښله.',
    'هغه هره ورځ پلی دفتر ته ځي.',
  ],
  ckb: [
    'ئەمڕۆ بەیانی زۆر سارد بوو، بۆیە چایەکی گەرمم خواردەوە.',
    'ئەو هەموو ڕۆژێک بە پێ دەچێتە نووسینگە.',
    'گوێی کچەکە گەورەیە!',
    'سامی ژیانی خۆش دەوێت',
    'لەوانەیە تۆم گۆرانی بڵێت بۆ ئێمە',
    'دوێنێ تۆم یارمەتی دایکی دا؟',
    'تۆم بە ئۆتۆمبێل چووە بۆستن بۆ بینینی ماری.',
    'لە کوێ کار دەکەیت.',
    'نا، نا! ئەوە ڕاست نییە.',
  ],
  uig: [
    'بۈگۈن ئەتىگەندە ھاۋا بەك سوغۇق ئىدى، شۇڭا مەن ئىسسىق چاي ئىچتىم.',
    'ئۇ ھەر كۈنى پىيادە ئىشخانىغا بارىدۇ.',
    'ئۇنىڭ ئاكىسى مەندىن ئىككى ياش چوڭ.',
    'ساڭا تېلېڧون كەلدى!',
    'كەچۈرۈڭ، ھازىر مەن بەك ئالدىراش.',
    'بۇ تۈنۈگۈن كەلگەن قىز.',
    'مېنىڭ يەنە بىر سىڭلىم بار.',
    'بۇ ئۆي يېڭى ئەمەس.',
    'ئىككى يۈز پۇل ماڭا كۆپ پۇل بولىدۇ.',
  ],
  rus: [
    'Сегодня утром было очень холодно, поэтому я выпил горячего чаю.',
    'Он каждый день ходит на работу пешком.',
    'Я не знаю, куда ведёт эта дорога.',
    'Это не то, что может сделать каждый.',
    'Сегодня утром мне холодно.',
    'Сегодня понедельник.',
    'Сегодня довольно холодно.',
    'Откуда вы друг друга знаете?',
    'Вот откуда я её знаю.',
    'Сегодня я чувствую себя хорошо.',
  ],
  ukr: [
    'Сьогодні вранці було дуже холодно, тому я випив гарячого чаю.',
    'Він щодня ходить на роботу пішки.',
    'Я не знаю, куди веде ця дорога.',
    'Сьогодні достатньо холодно.',
    'Я запитав, куди йти.',
    'Я не знаю, куди він пішов.',
    'Ти знаєш, куди пішов твій батько?',
    'Сьогодні їй набагато краще, ніж учора.',
    'Він запитав мене куди їхати.',
    'Він запитав мене куди йти.',
  ],
  bul: [
    'Тази сутрин беше много студено, затова изпих горещ чай.',
    'Той ходи на работа пеша всеки ден.',
    'Той беше ядосан, че никой нищо не каза.',
    'Тази работа може да се свърши за седмица.',
    'Той често пише на родителите си.',
    'Той не успя да получи работата.',
    'Той дойде да ме види.',
    'Той реши да отиде в чужбина.',
    'Той обича да гледа телевизия.',
  ],
  srp: [
    'Јутрос је било веома хладно, па сам попио врућ чај.',
    'Он сваки дан иде на посао пешке.',
    'Није знао шта ће рећи.',
    'Он ће доћи ако жели.',
    'Да ли он може доћи сутра?',
    'Да ли је вероватно да ће он доћи?',
    'Ко ће од вас вероватно доћи?',
    'Ја не верујем да ће он доћи.',
    'Не може се тако рећи.',
  ],
  kaz: [
    'Бүгін таңертең өте суық болды, сондықтан мен ыстық шай іштім.',
    'Ол күн сайын жұмысқа жаяу барады.',
    'Жоқ, мен емес, сен!',
    'Бұл маған өте ұнайды.',
    'Ол қайда жұмыс істейді?',
    'Ешқандай менің досым емес.',
    'Кеше өте суық болды.',
    'Осы шай өте жақсы.',
    'Саған қарап отырмын.',
  ],
  mon: [
    'Өнөө өглөө маш хүйтэн байсан тул би халуун цай уусан.',
    'Тэр өдөр бүр ажилдаа явган явдаг.',
    'Тэр худлаа хэлж байна.',
    'Тэр эмэгтэй баяртай харагдаж байна.',
    'Тэр юу хийж байгаа юм бэ?',
    'Өнөөдөр бороо орж байна.',
    'Тэр үед юу өөр байсан бэ?',
    'Тэр эмэгтэй одоо хаана амьдарч байгаа вэ?',
    'Тэр энд амьдардаг уу?',
  ],
  ell: [
    'Σήμερα το πρωί έκανε πολύ κρύο, γι’ αυτό ήπια ζεστό τσάι.',
    'Πηγαίνει στη δουλειά με τα πόδια κάθε μέρα.',
    'Σας είπα ήδη ότι δεν είναι εδώ.',
    'Σ\' αγαπώ, μωρό μου.',
    'Σε λατρεύω μωρό μου.',
    'Σε λατρεύω αγάπη μου.',
    'Σ\' αγαπώ έτσι όπως είσαι.',
    'Στο πάρκο ήταν πολλοί άνθρωποι.',
    'Σου αρέσει η μουσική;',
  ],
  heb: [
    'היה קר מאוד הבוקר, ולכן שתיתי תה חם.',
    'הוא הולך למשרד ברגל כל יום.',
    'מה אתה רוצה לעשות?',
    'אתה חושב יותר מדי.',
    'הוא אוהב לשתות קפה בלי סוכר.',
    'האם אפשר לקבל עזרה?',
    'אינני יודע מתי הוא יבוא לכאן.',
    'פגשתי את טום בדרך.',
    'הכובע הזה קטן מדי בשבילי.',
  ],
  kat: [
    'დღეს დილით ძალიან ცივოდა, ამიტომ ცხელი ჩაი დავლიე.',
    'ის ყოველდღე ფეხით მიდის სამსახურში.',
    'მას ძალიან უყვარს თავისი სკოლა.',
    'შეგიძლია წახვიდე თუ გინდა.',
    'მე ერთი ძმა მყავს.',
    'აი, თქვენი გასაღები.',
    'მე აქ აღარ ვცხოვრობ.',
    'ახლა შეგიძლია წახვიდე.',
    'ძალიან კარგი იქნება.',
  ],
  hye: [
    'Այսօր առավոտյան շատ ցուրտ էր, դրա համար տաք թեյ խմեցի։',
    'Նա ամեն օր ոտքով է գնում աշխատանքի։',
    'Խնդրում եմ, թույլ տվեք օգնել:',
    'Ես երբեք չեմ մոռանա այդ օրը:',
    'Կես ժամ է ինչ սպասում եմ։',
    'Թոմը ասաց, որ կօգնի ինձ:',
    'Ասա ինձ, ինչ ես փնտրում, ու ես կօգնեմ քեզ դա գտնել:',
    'Թոմը այսօր շատ ավելի ուժեղ է:',
    'Ինչ վերջապես մեկը կօգնի՞ թե ո՛չ:',
  ],
  amh: [
    'ዛሬ ጠዋት በጣም ቀዝቃዛ ነበር፣ ስለዚህ ትኩስ ሻይ ጠጣሁ።',
    'እሱ በየቀኑ በእግሩ ወደ ቢሮ ይሄዳል።',
  ],
  tir: [
    'ሎሚ ንግሆ ኣዝዩ ቁሪ ነይሩ፣ ስለዚ ውዑይ ሻሂ ሰቲየ።',
    'ንሱ መዓልቲ መዓልቲ ብእግሩ ናብ ቤት ጽሕፈት ይኸይድ።',
    'እዛ ገረብ፡ ሓምሳ ዓመት ገይራ ኣላ።',
    'ኣብ ትሕቲ ምድሪ እንዳ ዕዳጋ ኣሎ።',
    'ኣቦይ፡ መስሓቕ ነገራት ክዛረብ ይፈቱ።',
    'ኣብ ለንደን፡ ኣዝዩ ብዙሕ ሓደገኛ ቦታታት ኣሎ።',
    'ሃ ሃ ሃ፡ ኣዝዩ መስሓቕ እዩ።',
    'ኣብዚ ኵሉ ሳዕ ገለ ዝግበር ነገር ኣሎ።',
    'እዚ፡ ብሓቂ ኣገዳሲ ኣይኮነን።',
  ],
  tha: [
    'เช้านี้อากาศหนาวมาก ฉันเลยดื่มชาร้อน',
    'เขาเดินไปทำงานทุกวัน',
  ],
  lao: [
    'ເຊົ້ານີ້ອາກາດໜາວຫຼາຍ ຂ້ອຍຈຶ່ງດື່ມຊາຮ້ອນ',
    'ຂ້ອຍຍ່າງໄປເຮັດວຽກທຸກມື້',
  ],
  khm: [
    'ព្រឹកនេះអាកាសធាតុត្រជាក់ណាស់ ដូច្នេះខ្ញុំបានផឹកតែក្តៅ។',
    'គាត់ដើរទៅធ្វើការរាល់ថ្ងៃ។',
    'ទៅ​ជា​មួយ​ខ្ញុំ​បាន​ទេ​?',
    'ថម ស្រលាញ់ ម៉ារី ។',
  ],
  mya: [
    'ဒီမနက် အရမ်းအေးတယ်၊ ဒါကြောင့် ပူပူနွေးနွေး လက်ဖက်ရည် သောက်လိုက်တယ်။',
    'သူ နေ့တိုင်း ရုံးကို လမ်းလျှောက်သွားတယ်။',
  ],
  cmn: [
    '今天早上很冷，所以我喝了一杯热茶。',
    '他每天都走路去上班。',
    '我不知道这条路通向哪里。',
  ],
  jpn: [
    '今朝はとても寒かったので、温かいお茶を飲みました。',
    '彼は毎日歩いて会社に行きます。',
    'この道がどこへ続いているのか分かりません。',
    'こんにちは、お元気ですか、みなさん。',
  ],
  kor: [
    '오늘 아침은 무척 추워서 따뜻한 차를 마셨다.',
    '그는 매일 걸어서 회사에 간다.',
    '이 길이 어디로 이어지는지 모르겠다.',
    '너는 몇 개의 언어를 말할 수 있니?',
    '어제 그는 아무 것도 안 먹었다.',
    '난 네가 보스턴에서 한 일을 알고 있다.',
    '메리가 읽고 싶은 책이 톰에게 있다.',
    '그녀는 나에게 먹을 것을 주었다.',
    '나는 이 편지를 그에게 쓰고 있어.',
    '그녀는 일곱 개의 언어를 말한다.',
  ],
  spa: [
    'Esta mañana hacía mucho frío, así que me tomé un té caliente.',
    'Va andando al trabajo todos los días.',
    'No sé adónde lleva este camino.',
    'Él se quedó hasta diez días.',
    'El tiempo estuvo malo todos los días.',
    'Juego al fútbol todos los días.',
    'Él no viene aquí todos los días.',
    'En una semana hay siete días.',
    'Hace tres días que no le veo.',
    'Buenos días a todos.',
  ],
  por: [
    'Esta manhã estava muito frio, por isso bebi um chá quente.',
    'Ele vai a pé para o trabalho todos os dias.',
    'Não sei aonde leva esta estrada.',
    'Eu gosto muito do meu trabalho.',
    'Tenho muito trabalho a fazer.',
    'Estou muito cansado do trabalho.',
    'Vou escrever uma carta amanhã.',
    'Venha amanhã aqui sem falta.',
    'Agora vamos começar nosso trabalho.',
    'Eu espero que esteja melhor amanhã.',
  ],
  ita: [
    'Stamattina faceva molto freddo, così ho bevuto un tè caldo.',
    'Va a piedi al lavoro tutti i giorni.',
    'Sono così felice per te.',
    'Non posso vivere così.',
    'Mi sento molto solo in questi giorni.',
    'Sono molto occupato in questi giorni.',
    'Gioco a tennis tutti i giorni.',
    'Non voglio aspettare così tanto tempo.',
    'Va a scuola a piedi.',
  ],
  ron: [
    'În această dimineață a fost foarte frig, așa că am băut un ceai fierbinte.',
    'Merge pe jos la muncă în fiecare zi.',
    'Bună dimineața la toată lumea.',
    'Mulțumesc foarte mult!',
    'Bună seara, ce faci?',
    'Bună seara, ce mai faceți?',
    'Astăzi vremea e frumoasă.',
    'Este frumos astăzi.',
    'Îmi face plăcere să merg pe jos.',
  ],
  fra: [
    'Ce matin il faisait très froid, alors j’ai bu un thé chaud.',
    'Il va au bureau à pied tous les jours.',
    'Je ne sais pas où mène cette route.',
    'Mon bureau est fait de bois.',
    'Il faisait chaud la nuit dernière.',
    'Il faisait chaud hier.',
    'Il faisait froid hier.',
    'Il faisait très froid hier matin.',
    'Il faisait très froid ce matin.',
    'Il faisait moins dix ce matin.',
  ],
  cat: [
    'Aquest matí feia molt de fred, així que vaig prendre un te calent.',
    'Va a peu a la feina cada dia.',
    'Em vaig quedar un dia més al llit per si de cas.',
    'Fa dos anys des que vaig venir ací.',
    'Quan va arribar vaig fer cafè.',
    'Qui pot fer aquesta feina?',
    'Li vaig comprar a ella un nou cotxe.',
    'De cop, vaig tenir sort.',
    'Me la vaig trobar de camí cap a l\'escola.',
  ],
  deu: [
    'Heute Morgen war es sehr kalt, deshalb habe ich einen heißen Tee getrunken.',
    'Er geht jeden Tag zu Fuß ins Büro.',
    'Ich weiß nicht, wohin dieser Weg führt.',
    'Ich weiß einfach nicht, was ich sagen soll.',
    'Ich weiß nicht mehr, was ich tun soll.',
    'Ich weiß nicht, ob ich es noch habe.',
    'Wie, du weißt nicht?!',
    'Ich weiß nicht, ob er das für mich getan hätte.',
    'Ich weiß nicht, wo er wohnt.',
    'Weißt du, wer sie ist?',
  ],
  nld: [
    'Vanochtend was het erg koud, dus dronk ik een warme thee.',
    'Hij gaat elke dag lopend naar kantoor.',
    'Hij speelt zeer goed.',
    'Hij heeft een brief geschreven.',
    'Hij is al een man.',
    'Hij zal op je wachten.',
    'Hij wacht wel op je.',
    'Hij weet zeker dat hij komt.',
    'Hij deed zo zijn best dat hij er helemaal rood van werd.',
  ],
  afr: [
    'Vanoggend was dit baie koud, daarom het ek warm tee gedrink.',
    'Hy loop elke dag werk toe.',
    'Hy is \'n onderwyser.',
    'Hy kon nie kom nie, omdat hy siek was.',
    'Ons is baie dronk.',
    'Ek is nou baie moeg.',
    'Hy is trots op sy seun.',
    'Hy is nie siek nie.',
    'Dit was baie mooi.',
  ],
  swe: [
    'I morse var det mycket kallt, så jag drack en kopp varmt te.',
    'Han går till jobbet varje dag.',
    'Idag mår jag mycket bättre.',
    'Jag är mycket hungrig.',
    'Min mor tycker mycket om te.',
    'Hur mycket blir det?',
    'Jag har inte så mycket pengar med mig.',
    'Du pratar för mycket.',
    'Ät så mycket du vill.',
  ],
  dan: [
    'I morges var der meget koldt, så jeg drak en kop varm te.',
    'Han går på arbejde hver dag.',
    'Det er lige meget.',
    'Jeg vil hjælpe dig så meget jeg kan.',
    'Jeg holder meget af hende.',
    'Han kender os meget godt.',
    'Bogen er meget interessant.',
    'Han kan gøre det meget bedre end jeg kan.',
    'En computer er i stand til at regne meget hurtigt.',
  ],
  nob: [
    'I morges var det veldig kaldt, så jeg drakk en kopp varm te.',
    'Han går til jobben hver dag.',
    'Jeg er veldig glad for å se deg igjen.',
    'Jeg var veldig trøtt, så jeg la meg tidlig.',
    'Han liker musikk veldig godt.',
    'Det var så kaldt at jeg ble hjemme hele dagen.',
    'Jeg kan svømme veldig fort.',
    'Hun var veldig stolt av faren sin.',
    'Hvor langt har du kommet med jobben?',
  ],
  isl: [
    'Í morgun var mjög kalt, svo ég drakk heitt te.',
    'Hann gengur í vinnuna á hverjum degi.',
    'Satt að segja elska ég hann ekki.',
    'Ég mun gera allt sem ég get fyrir hana.',
    'Þetta er ekki það sem ég er að leita að.',
    'Segðu mér hvað þú vilt að ég geri.',
    'Ég var næstum búinn með vinnuna mína þegar hún kom.',
    'Það er mjög kalt í dag.',
    'Pabbi minn sagði að ég gæti ekki farið einn til útlanda.',
  ],
  fin: [
    'Tänä aamuna oli hyvin kylmä, joten join kuumaa teetä.',
    'Hän kävelee töihin joka päivä.',
    'Olen ollut kiireinen koko päivän.',
    'Hänellä ei ollut rahaa joten hän ei voinut ostaa ruokaa',
    'Minulla on kiire, joten en voi mennä.',
    'Kaunis päivä, eikö?',
    'Hän on tehnyt töitä koko päivän.',
    'Olen ollut kotona melkein koko päivän.',
    'Hän tuli takaisin kaksi päivää myöhemmin.',
  ],
  est: [
    'Täna hommikul oli väga külm, seetõttu jõin kuuma teed.',
    'Ta käib iga päev jalgsi tööl.',
    'Mine tagasi tööle.',
    'Ma lähen nüüd parem tööle tagasi.',
  ],
  hun: [
    'Ma reggel nagyon hideg volt, ezért forró teát ittam.',
    'Minden nap gyalog megy dolgozni.',
    'Tegnap nem voltam dolgozni.',
    'Senki se akar kint dolgozni, amikor hideg van.',
    'Ma nincs kedvem dolgozni.',
    'Tanulni akarok, ezért iskolába megyek.',
    'Nagyon meleg van ma, ezért nincs kedvem tanulni.',
    'Nem akarok dolgozni.',
    'Azt mondta, hogy fáradt, ezért korán megy haza.',
  ],
  pol: [
    'Dziś rano było bardzo zimno, więc wypiłem gorącą herbatę.',
    'Codziennie chodzi do pracy pieszo.',
    'Proszę bardzo, nie ma za co.',
    'Możesz jechać, gdzie ci się podoba.',
    'Pamiętam pierwszy raz.',
    'Jesteś przy mnie, a więc wszystko dobrze.',
    'Dziękuję, to wszystko.',
    'Musisz więcej pracować.',
    'Bardzo lubię swoją pracę.',
  ],
  ces: [
    'Dnes ráno byla velká zima, tak jsem si dal horký čaj.',
    'Chodí do práce pěšky každý den.',
    'Koupil jsem si nové auto.',
    'Zůstal jsem týden doma.',
    'Asi jsem se ztratil.',
    'Koupil jsem to včera.',
    'Slyšel jsem, že zemřel.',
    'Včera jsem čekal, že přijde.',
    'Četl jsem nějaké knihy.',
  ],
  hrv: [
    'Jutros je bilo vrlo hladno, pa sam popio topli čaj.',
    'Svaki dan ide na posao pješice.',
  ],
  lit: [
    'Šįryt buvo labai šalta, todėl išgėriau karštos arbatos.',
    'Jis kasdien eina į darbą pėsčiomis.',
    'Viskas ką jis pasakė buvo tiesa.',
    'Tas kambarys nėra labai didelis.',
    'Tomas neturi šiandien eiti į mokyklą.',
    'Mano tėvas moka plaukti, bet mano motina ne.',
    'Aš nemėgstu kavos.',
    'Mano tėvas ką tik grįžo namo.',
    'Jis ką tik grįžo namo.',
  ],
  sqi: [
    'Sot në mëngjes ishte shumë ftohtë, prandaj piva një çaj të nxehtë.',
    'Ai shkon në punë në këmbë çdo ditë.',
    'Pse gjithçka po shkon keq?',
    'Flet frëngjisht çdo ditë?',
  ],
  eus: [
    'Gaur goizean oso hotz egiten zuen, beraz te bero bat hartu dut.',
    'Egunero oinez joaten da lanera.',
    'Nork idatzi zuen liburu hau?',
    'Ez duzu entzun zer azkar hitz egiten zuen?',
    'Gorroto nuen, baina zure laguntza behar dugu esaten zuen.',
    'Egunero zerbait ikasten.',
    'Badakizu nork hil zuen?',
    'Egunero korrika egiten du.',
    'Mundu osoa seguru dago berak izan zela egin zuena.',
  ],
  cym: [
    'Roedd hi’n oer iawn y bore yma, felly yfais i de poeth.',
    'Mae’n cerdded i’r gwaith bob dydd.',
    'Roedd hi eisiau bod yn athrawes.',
    'Roedd rhaid i mi aros adre.',
    'Roedd gen\' i gath.',
    'Roedd hi\'n gallu darllen y llyfr.',
  ],
  tur: [
    'Bu sabah hava çok soğuktu, bu yüzden sıcak bir çay içtim.',
    'Her gün işe yürüyerek gidiyor.',
    'Artık seni sevmiyorum.',
    'Çok daha iyi hissediyorum.',
    'Artık çocuk değilim.',
    'Hiç kimse bilmiyor.',
    'Doktor olarak iyi değil.',
    'Seni çok seviyorum.',
    'Yarın burada olacağım.',
  ],
  azj: [
    'Bu səhər hava çox soyuq idi, ona görə isti çay içdim.',
    'O, hər gün işə piyada gedir.',
  ],
  uzn: [
    'Bugun ertalab juda sovuq edi, shuning uchun issiq choy ichdim.',
    'U har kuni ishga piyoda boradi.',
  ],
  vie: [
    'Sáng nay trời rất lạnh, nên tôi đã uống một tách trà nóng.',
    'Anh ấy đi bộ đến chỗ làm mỗi ngày.',
    'Tôi hết lời để nói.',
    'Nếu thế giới không như bây giờ, thì tôi có thể tin ai cũng được.',
    'Một người luôn luôn có thể kiếm thêm thì giờ.',
    'Phần nhiều người ta viết về chuyện cuộc đời hàng ngày.',
    'Có lẽ cũng vậy cho anh ấy luôn.',
    'Tôi ghét những lúc đông người.',
    'Không, anh ấy không phải bạn trai mới của tôi.',
  ],
  ind: [
    'Pagi ini udaranya sangat dingin, jadi saya minum teh hangat.',
    'Dia berjalan kaki ke kantor setiap hari.',
    'Kemarin pagi sangat dingin.',
    'Di rumahku sangat dingin.',
    'Apakah kamu tidak merasa dingin.',
    'Mana yang lebih kamu suka: musim panas atau musim dingin?',
    'Kamu lebih suka musim panas atau musim dingin?',
    'Aku ingin minum sesuatu yang dingin.',
    'Sayang sekali, seperti yang kamu tahu, saya tidak bisa pergi ke kantor polisi.',
  ],
  zsm: [
    'Pagi ini cuaca sangat sejuk, jadi saya minum teh panas.',
    'Dia berjalan kaki ke pejabat setiap hari.',
    'Dalam cuaca yang teruk ini, saya tidak ingin keluar.',
    'Hari ini cuaca sejuk.',
    'Saya tiada di pejabat hari ini.',
    'Saya merasakan angin sejuk di muka saya.',
    'Semalam sangat sejuk, jadi kami tidak keluar dan hanya duduk di rumah.',
    'Ia semakin sejuk di sini.',
    'Hari ini, cuaca sangat baik.',
  ],
  tgl: [
    'Napakalamig ngayong umaga, kaya uminom ako ng mainit na tsaa.',
    'Naglalakad siya papunta sa trabaho araw-araw.',
    'Mas malamig ngayong umaga kaysa sa kahapon.',
    'Nag-aaral ka araw-araw?',
    'Di araw-araw ay linggo.',
    'Umiinom ng gamot ang lolo ko araw-araw.',
    'Dala ng mga batang lalaki ang mga libro nila araw-araw.',
    'Siya ay nagluluto para sa kanyang asawa araw-araw.',
    'Bakit ang laki ng buwan ngayong gabi?',
  ],
  swh: [
    'Asubuhi ya leo kulikuwa na baridi sana, kwa hiyo nilikunywa chai ya moto.',
    'Yeye huenda kazini kwa miguu kila siku.',
    'Yeye ni ndani ya nyumba hii.',
    'Yeye ni mwalimu wangu.',
    'Yeye ni mwanamke mzuri.',
    'Yeye hana bunduki.',
    'Yeye ni msichana wa miaka kumi na mbili.',
    'Yeye ni maarufu kuliko mimi.',
    'Yeye hana moyo hata kidogo.',
  ],
  hau: [
    'Da safiyar yau an yi sanyi sosai, saboda haka na sha shayi mai zafi.',
    'Yana tafiya aiki da ƙafa kowace rana.',
    'Yau sanyi da sauƙi.',
    'Abun da zaka iya yi kawai shine iya ƙoƙarin ka.',
    'Meyasa ka yi ƙoƙarin gudu?',
    'Ina son zuwa ƙasar waje.',
    'Ba a buƙatar sauri.',
    'Na wani abu ya taɓa min ƙafa.',
    'Idan aka kuma wani yaƙi, duk sai an kashe mu.',
  ],
  yor: [
    'Òwúrọ̀ òní tutù gan-an, nítorí náà mo mu tíì gbígbóná.',
    'Ó máa ń rìn lọ sí ibi iṣẹ́ lójoojúmọ́.',
  ],
  som: [
    'Subaxdan aad bay u qabow ahayd, sidaas darteed waxaan cabbay shaah kulul.',
    'Maalin walba lugta ayuu shaqada ku aadaa.',
  ],
  zul: [
    'Namhlanje ekuseni bekubanda kakhulu, ngakho ngiphuze itiye elishisayo.',
    'Uhamba ngezinyawo eya emsebenzini nsuku zonke.',
  ],
  mkd: [
    'Утрово беше многу студено, затоа испив топол чај.',
    'Тој секој ден оди на работа пешки.',
    'Не знам каде води овој пат.',
    'Оди на училиште секој ден за да учи.',
    'Пробај да го направиш како што треба овој пат.',
    'Не го разбирам овој збор.',
    'Само држи се до овој пат.',
    'Нешто се смени овој пат.',
    'Том си ги носи децата на училиште секој ден.',
    'Просто е да се реши овој проблем.',
  ],
  bel: [
    'Сёння раніцай было вельмі холадна, таму я выпіў гарачай гарбаты.',
    'Ён кожны дзень ходзіць на працу пешшу.',
    'Я не ведаю, куды вядзе гэтая дарога.',
    'Я люблю гэтую кнігу больш за ўсё.',
    'Я маю шмат сяброў.',
    'Ён зноў згубіў свой парасон.',
    'Я ведаю, адкуль ён.',
    'А, усё як заўсёды.',
    'Мне шкада, што я туды пайшоў.',
    'Я не ведаю, што мне цяпер рабіць.',
  ],
  tgk: [
    'Имрӯз субҳ ҳаво хеле хунук буд, барои ҳамин чойи гарм нӯшидам.',
    'Ӯ ҳар рӯз пиёда ба идора меравад.',
    'Намедонам, ки ин роҳ ба куҷо мебарад.',
  ],
  kir: [
    'Бүгүн эртең менен абдан суук болду, ошондуктан ысык чай ичтим.',
    'Ал күн сайын жумушка жөө барат.',
    'Бул жол кайда алып барарын билбейм.',
  ],
  slk: [
    'Dnes ráno bola veľká zima, tak som si dal horúci čaj.',
    'Chodí do práce pešo každý deň.',
    'Neviem, kam vedie táto cesta.',
    'Musíš sa veľa učiť.',
    'Neviem, kto to urobil.',
    'Prepáčte, koľko je hodín?',
    'Moja sestra je veľmi pekné dievča.',
    'Neviem, choď spať!',
    'Veľa z toho nerozumiem.',
    'Koľko rokov má tvoj otec?',
  ],
  slv: [
    'Danes zjutraj je bilo zelo mrzlo, zato sem spil topel čaj.',
    'Vsak dan hodi v službo peš.',
    'Ne vem, kam pelje ta cesta.',
  ],
  lav: [
    'Šorīt bija ļoti auksts, tāpēc iedzēru karstu tēju.',
    'Viņš katru dienu iet uz darbu kājām.',
    'Es nezinu, kurp ved šis ceļš.',
  ],
  glg: [
    'Esta mañá facía moito frío, así que tomei un té quente.',
    'Vai andando ao traballo cada día.',
    'Non sei onde leva este camiño.',
    'Se chove mañá non irei.',
    'Temos unha festa mañá pola noite.',
    'Ela sempre traballa moito.',
    'Hai moitos paxaros neste parque.',
    'Dende mañá podemos ir xuntos ao traballo',
    'Temos moito traballo de facer.',
    'Hoxe non, mañá si.',
  ],
  gle: [
    'Bhí sé an-fhuar ar maidin, mar sin d’ól mé tae te.',
    'Siúlann sé chun na hoibre gach lá.',
    'Cá dtéann an bóthar seo?',
    'Bhí sé ag labhairt.',
    'Bhí muid le do mháthair.',
    'Bhí an oíche fuar.',
  ],
  gla: [
    'Bha i glè fhuar sa mhadainn, mar sin dh’òl mi tì theth.',
    'Bidh e a’ coiseachd dhan obair a h-uile latha.',
    'Càite a bheil an rathad seo a’ dol?',
    'Càite a bheil thu ag obair?',
    'Bha mi glè sgìth an-diugh.',
  ],
  mlt: [
    'Dalgħodu kien kiesaħ ħafna, għalhekk xrobt tè sħun.',
    'Kuljum jimxi għax-xogħol.',
    'Ma nafx fejn twassal din it-triq.',
    'Ziri kien dejjem jorqod waħdu.',
  ],
  fao: [
    'Í morgun var sera kalt, so fekk eg mær heitt te.',
    'Hann gongur á arbeiði hvønn dag.',
    'Eg veit ikki, hvar hesin vegurin gongur.',
  ],
  ltz: [
    'De Moien war et ganz kal, dofir hunn ech waarmen Téi gedronk.',
    'Hie geet all Dag zu Fouss op de Büro.',
    'Ech weess net, wouhin dëse Wee féiert.',
    'Ech hunn iech gesinn.',
    'Ech wunnen a schaffen hei.',
  ],
  bre: [
    'Yen-tre e oa ar mintin-mañ, setu m’em eus evet te tomm.',
    'Bemdez ez a da labourat war-droad.',
    'N’ouzon ket pelec’h ez a an hent-mañ.',
    'Bemdez ez an d’ar skol.',
    'Dihun ac\'hanon warc\'hoazh da c\'hwec\'h eur mintin, mar-plij.',
    'Mar-plij, dihun ac\'hanon warc\'hoazh da c\'hwec\'h eur mintin.',
    'Ar mintin-mañ em eus debret bara amanennet.',
    'Debret em eus ar mintin-mañ bara amanennet.',
    'Debret em eus bara amanennet ar mintin-mañ.',
    'Bara amanennet em eus debret ar mintin-mañ.',
  ],
  fry: [
    'Fanmoarn wie it hiel kâld, dêrom naam ik in bakje waarme tee.',
    'Alle dagen rint er nei it wurk.',
    'Ik wit net wêr’t dizze dyk hinne giet.',
  ],
  div: [
    'މިއަދު ހެނދުނު ވަރަށް ފިނި ވި، އެހެންވެ ހޫނު ސައި ބޮއެފިން.',
    'އޭނާ ކޮންމެ ދުވަހަކު ހިނގާފައި އޮފީހަށް ދެއެވެ.',
    'މި މަގު ކޮންތާކަށް ދާކަން އަހަންނަކަށް ނޭނގެ.',
  ],
  bod: [
    'དེ་རིང་ཞོགས་པར་གྲང་མོ་ཧ་ཅང་ཆེན་པོ་འདུག ངས་ཇ་ཚ་པོ་ཞིག་བཏུངས།',
    'ཁོང་ཉིན་ལྟར་རྐང་ཐང་གིས་ལས་ཁུངས་སུ་འགྲོ་གི་ཡོད།',
    'ལམ་འདི་ག་པར་འགྲོ་མིན་ངས་མི་ཤེས།',
  ],
  dzo: [
    'ད་རིས་དྲོ་པ་ཁ་ཤིན་ཏུ་གྲང་མོ་འདུག ཨིན་མི་ང་གིས་ཇ་ཚ་ཏོང་ཏོ་འཐུང་ཡི།',
    'ཁོ་ཉིནམ་བཞིན་དུ་རྐངམ་གིས་ལཱ་གཡོག་ནང་འགྱོཝ་ཨིན།',
    'ལམ་འདི་ག་ཏེ་འགྱོཝ་ཨིན་ན་ང་གིས་མི་ཤེས།',
  ],
  sat: [
    'ᱛᱮᱦᱮᱧ ᱥᱮᱛᱟᱜ ᱯᱩᱨᱟᱹ ᱨᱟᱵᱟᱝ ᱛᱟᱦᱮᱸᱠᱟᱱᱟ, ᱚᱱᱟᱛᱮ ᱤᱧ ᱨᱟᱹᱯᱩᱫ ᱪᱟᱭ ᱧᱩᱭ ᱠᱮᱫᱟ.',
    'ᱩᱱᱤ ᱫᱤᱱ ᱫᱤᱱ ᱛᱟᱞᱟᱛᱮ ᱠᱟᱹᱢᱤ ᱛᱮ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ.',
    'ᱱᱚᱶᱟ ᱦᱚᱨ ᱚᱠᱟ ᱛᱮ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ ᱤᱧ ᱵᱟᱝ ᱵᱟᱰᱟᱭᱟ.',
    'ᱤᱧ ᱫᱚ ᱥᱤᱧᱚᱛ ᱫᱤᱥᱚᱢ ᱨᱮ ᱯᱟᱲᱦᱟᱣᱜ ᱠᱟᱹᱱᱟᱹᱧ ᱾',
    'ᱤᱧ ᱫᱚ ᱵᱷᱟᱨᱚᱛ ᱫᱤᱥᱚᱢ ᱨᱮ ᱯᱟᱲᱦᱟᱣᱜ ᱠᱟᱹᱱᱟᱹᱧ ᱾',
    'ᱤᱧᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ᱴᱚᱢ ᱠᱟᱱᱟ ᱾',
    'ᱴᱚᱢ ᱫᱚ ᱤᱧᱟᱜ ᱧᱩᱛᱩᱢ ᱠᱟᱱᱟ ᱾',
    'ᱩᱱᱤᱭᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ᱴᱚᱢ ᱠᱟᱱᱟ ᱾',
    'ᱡᱚᱦᱟᱨ, ᱤᱧᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ᱴᱚᱢ ᱠᱟᱱᱟ ᱾',
    'ᱥᱟᱹᱨᱤ ᱠᱟᱛᱷᱟ ᱠᱟᱱᱟ ᱾',
  ],
  mni: [
    'ꯉꯁꯤ ꯑꯌꯨꯛ ꯌꯥꯝꯅꯥ ꯏꯡꯏ, ꯃꯗꯨꯅꯥ ꯑꯩꯅꯥ ꯑꯁꯥꯕ ꯆꯥ ꯊꯛꯈꯤ.',
    'ꯃꯍꯥꯛꯅꯥ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯈꯣꯡꯅꯥ ꯑꯣꯐꯤꯁ ꯆꯠꯂꯤ.',
    'ꯂꯝꯕꯤ ꯑꯁꯤ ꯀꯗꯥꯏꯗꯥ ꯆꯠꯂꯤꯕꯅꯣ ꯑꯩꯅꯥ ꯈꯉꯗꯦ.',
  ],
  chr: [
    'ᏑᎾᎴᎢ ᎤᏴᏢ ᎨᏎᎢ, ᎾᏍᎩ ᎢᏳᏍᏗ ᎤᏗᎴᎩ ᎠᏗᏔᏍᏗ ᎠᎩᏗᏔᏅᎩ.',
    'ᏂᏚᎩᏨᏂᏓᏒ ᏚᎳᏍᎬ ᎠᎢᏒ ᏗᎦᎸᏫᏍᏓᏁᏗ.',
    'ᎥᏝ ᏥᎦᏔᎲᎾ ᎯᎠ ᏂᎦᏅᏅ ᎭᏢ ᎠᎢᏒᎢ.',
  ],
  iku: [
    'ᐅᓪᓛᖅ ᓂᓪᓚᓱᒃᑐᖅ, ᑕᐃᒪᐃᒻᒪᑦ ᐅᖅᑰᑦᑐᒥᒃ ᑏᑐᖅᑐᖓ.',
    'ᐅᓪᓗᑕᒫᑦ ᐱᓱᒃᖢᓂ ᐃᖅᑲᓇᐃᔮᒧᑦ ᐱᓱᒃᑐᖅ.',
    'ᖃᐅᔨᒪᖏᑦᑐᖓ ᐊᖅᑯᑎ ᓇᒧᑦ ᐱᓯᒪᖕᒪᖔᑦ.',
  ],
  nqo: [
    'ߓߌ߬ ߛߐ߰ߡߊ߬ ߘߊ߬ ߛߎߡߦߊ ߞߊ߬ ߜߍߟߍ߲߫، ߒ ߞߊ߬ ߘߎ߬ߕߍ߬ ߜߏߟߏ߲߫ ߡߌ߲߬.',
    'ߊ߬ ߦߋ߫ ߕߊ߯ ߓߊ߯ߙߊ ߘߐ߫ ߛߋ߲߬ߠߊ߫ ߟߏ߲߫ ߏ߬ ߟߏ߲߫.',
    'ߒ ߡߊ߫ ߟߐ߲߫ ߛߌߟߊ ߣߌ߲߬ ߦߋ߫ ߕߊ߯ ߦߙߐ ߡߍ߲.',
  ],
  fuf: [
    '𞤖𞤢𞤲𞥋𞤣𞤫 𞤧𞤵𞤩𞤢𞤳𞤢 𞤶𞤢𞤲𞤺𞤵𞤣𞤫 𞤯𞤵𞥅𞤯𞤭, 𞤳𞤢𞤣𞤭 𞤥𞤭 𞤴𞤢𞤪𞤭 𞤷𞤢𞤴 𞤲𞤵𞤤𞥆𞤵𞤲𞤣𞤵.',
    '𞤳𞤢𞤲𞤳𞤮 𞤴𞤢𞤸𞤮 𞤴𞤢𞤸𞤢 𞤲𞤣𞤫𞤪 𞤺𞤮𞤤𞥆𞤫 𞤳𞤢 𞤳𞤵𞤴𞤣𞤫.',
    '𞤥𞤭 𞤢𞤲𞤣𞤢𞥄 𞤼𞤮 𞤤𞤢𞤱𞤮𞤤 𞤲𞤺𞤮𞤤 𞤴𞤢𞤸𞤢𞤼𞤢.',
  ],
  zgh: [
    'ⴰⵙⵙ ⴰⴷ ⵜⵉⴼⴰⵡⵜ ⵜⴳⴰ ⵜⴰⵙⵎⵎⵉⴹⵜ ⴱⴰⵀⵔⴰ, ⵖⵉⴽⴰⵏⵏ ⵙⵡⵉⵖ ⴰⵜⴰⵢ ⵉⵣⵖⴰⵏ.',
    'ⵏⵜⵜⴰ ⵉⵜⴷⴷⵓ ⵙ ⵓⴹⴰⵕ ⵖⵔ ⵜⵡⵡⵓⵔⵉ ⴽⵓ ⴰⵙⵙ.',
    'ⵓⵔ ⵙⵙⵉⵏⵖ ⵎⴰⵏⵉ ⵉⵜⴷⴷⵓ ⵡⴰⴱⵔⵉⴷ ⴰⴷ.',
    'ⵉⵇⵇⴰⵏ ⴽ ⵉⴷ ⴰⴷ ⵜⴷⴷⵓⴷ.',
    'ⵉⵙⵙⵓⵙⵎ ⵉⵢⵉ ⵍⵍⵉⴳ ⴷⴷⵉⵖ ⵙ ⵜⵎⴰⵣⵉⵔⵜ ⵏⵏⵖ.',
    'ⵓⵙⵔⵖ ⴱⴰⵀⵔⴰ ⴽⵔⴰ ⵏ ⵜⵀⵉⵔⵉⵜ.',
    'ⵉⵙ ⵜⵙⵙⵏⴷ ⵉⵎⴰⵣⵉⵖⵏ ?',
    'ⵎⴰ ⵜⵙⵙⵏⴷ ⵅⴼ ⵉⵎⴰⵣⵉⵖⵏ ?',
    'ⵓⵔ ⵥⴹⴰⵕⵖ ⴰⴷ ⵙⴽⵔⵖ ⵢⴰⵜ ⵖⵉⵍⴰⴷ.',
    'ⵉⵏⵏⴰ ⵜⵓⵎ ⵎⴰⵙ ⵔⴰⴷ ⵉⵢⵉ ⵢⴰⵡⵙ ⴰⵔ ⴽⵉⵖ ⵓⴼⵉⵖ ⴰⵢⵍⵍⵉ ⵓⵙⵔⵖ.',
  ],
  gom: [
    'आज सकाळीं खूब थंडी आसली, देखून हांवें गरम चा पियेलों.',
    'तो दर दिसा चलत ऑफिसाक वता.',
    'हो वाठ खंय वता तें म्हाका खबर ना.',
  ],
  doi: [
    'अज्ज सबेरे बड़ी ठंड ही, इस करी मैं गरम चाह पीती.',
    'ओह् हर रोज़ पैदल ई दफ्तर जंदा ऐ.',
    'मिगी नेईं पता जे एह् राह् कुत्थें जंदा ऐ.',
  ],
  awa: [
    'आजु भिनसार बहुत जाड़ रहा, तेहि से हम गरम चाह पियेन.',
    'ऊ रोजु पैदले दफ्तर जात ह.',
    'हमका नाहीं पता कि ई रस्ता कहाँ जात ह.',
  ],
  new: [
    'थौं सुथय् तःधंगु खाउ जुल, अथेहे जिं तातुगु चा त्वना.',
    'वय्कः सकल दिं तुं ल्हाना कार्यालयय् झाइ.',
    'थ्व लँ गन वनी जिं मसिउ.',
  ],
  pnb: [
    'اج سویرے بہوں ٹھنڈ سی، ایس لئی میں گرم چاہ پیتی۔',
    'اوہ ہر روز پیدل ای دفتر جاندا اے۔',
    'مینوں نئیں پتہ کہ ایہہ راہ کتھے جاندا اے۔',
  ],
  prs: [
    'امروز صبح هوا بسیار سرد بود، از همین خاطر چای گرم نوشیدم.',
    'او هر روز پیاده به دفتر میرود.',
    'نمیدانم که این سرک به کجا میرسد.',
  ],
  bal: [
    'مرۏچی صباحا پُر سرد اَت، گڈا من گرم چاہ وارتُن.',
    'آ ھر روچ پیادگ دفتر ءَ شت کنت.',
    'من نزانان کہ ای راہ کجا ءَ شت کنت.',
  ],
  kas: [
    'اَز صُبحَس ژھ ٹھنڈ آسِتھ، تہٕ مےۭ چٲو گرٕم چاے۔',
    'سُہ گژھہِ پرٛتھ دۄہ پیدل دفترَس۔',
    'مےۭ چھُنہٕ پتہ زِ یہٕ وَتھ کۄت گژھان۔',
  ],
  arz: [
    'الصبح النهارده كان برد قوي، عشان كده شربت شاي سخن.',
    'هو بيروح الشغل ماشي كل يوم.',
    'مش عارف الطريق ده بيودي فين.',
  ],
  ary: [
    'هاد الصباح كانت البرد بزاف، علاحقاش شربت أتاي سخون.',
    'كيمشي للخدمة على رجليه كل نهار.',
    'ما عرفتش فين كيمشي هاد الطريق.',
  ],
  tat: [
    'Бүген иртә бик салкын иде, шуңа күрә мин кайнар чәй эчтем.',
    'Ул һәр көн эшкә җәяү бара.',
    'Бу юл кая илтә, мин белмим.',
    'Мин сәгать ничә икәнен белмим.',
    'Синең җавап дөрес.',
    'Бу җавап миңа бик ошый.',
    'Ни әйтергә дә белмим.',
    'Моны эшләргә сине нәрсә мәҗбүр итте?',
    'Ул аңа ни дип җавап бирде?',
    'Көн артык салкын да, ләкин җылы да түгел.',
  ],
  bak: [
    'Бөгөн иртән бик һыуыҡ ине, шуға күрә мин ҡайнар сәй эстем.',
    'Ул һәр көн эшкә йәйәү бара.',
    'Был юл ҡайҙа алып бара, мин белмәйем.',
  ],
  chv: [
    'Паян ирхине питӗ сивӗччӗ, ҫавӑнпа эпӗ вӗри чей ӗҫрӗм.',
    'Вӑл кулленех ӗҫе ҫуран каять.',
    'Ку ҫул ӑҫта каять, эпӗ пӗлместӗп.',
    'Манӑн икӗ кушак пур.',
    'Санӑн икӗ кӗнеке пур.',
    'Эпӗ сана юрататӑп.',
    'Эпӗ паян пушӑ мар.',
    'Эпӗ ыран пушӑ мар.',
    'Вӑл акӑлчанла лайӑх калаҫать.',
    'Акӑлчанла манса кай.',
  ],
  sah: [
    'Бүгүн сарсыарда олус тымныы этэ, онон итии чэйи испитим.',
    'Кини күн аайы үлэтигэр сатыы барар.',
    'Бу суол ханна барарын билбэппин.',
  ],
  oss: [
    'Абон райсом тынг уазал уыд, уымæ гæсгæ æз тæвд цай баназтон.',
    'Уый алы бон дæр куыстмæ фистæгæй цæуы.',
    'Æз нæ зонын, ацы фæндаг кæдæм цæуы.',
    'Дæ зæрдæмæ цы нæ цæуы?',
    'Дæуæн диссаг у, æз дæр адæймаг кæй дæн?',
    'Йæ хъæлæс у тынг рæсугъд.',
    'Уый мæ зæрдæмæ нæ цæуы.',
    'Байрæджы дæн, æмæ мæ бахатыр кæнут.',
    'Ай япойнаг хæринаг у?',
    'Англисаг æвзаг дæ зæрдæмæ цæуы?',
  ],
  che: [
    'Тахана Ӏуьйранна чӀогӀа шело яра, цундела ас мела чай мелира.',
    'Иза массо а де болхе гӀаш воьду.',
    'Суна ца хаьа хӀара некъ мичахьа боьду.',
  ],
  bos: [
    'Jutro je bilo veoma hladno, pa sam skuhao vruć čaj.',
    'On svakodnevno pješke odlazi na posao.',
    'Ne znam kuda vodi ovaj put.',
    'Ko je ovaj čovjek?',
  ],
  oci: [
    'Aqueste matin fasiá plan freg, alara ai begut un te caud.',
    'Va a pè al trabalh cada jorn.',
    'Sabi pas ont mena aqueste camin.',
    'Un jorn de mei qu\'es passat.',
    'Lo men pair que beu cada jorn.',
    'Pendent tota la jornada, es estat en cèrca d\'una letra.',
    'Se pòt totjorn trobat temps.',
    'I a totjorn quauqu\'un que parla.',
    'Los dus jorns van plan.',
    'Estoc totjorn atau.',
  ],
  srd: [
    'Custu manzanu fiat meda fritu, duncas apo bufadu unu te callenti.',
    'Andat a pee a traballare dontzi die.',
    'Non isco ue portat custu caminu.',
  ],
  ast: [
    'Esta mañana facía muncho fríu, asina que tomé un té caliente.',
    'Va andando al trabayu tolos díes.',
    'Nun sé au lleva esti camín.',
  ],
  roh: [
    'Quest damaun faschev fitg fraid, perquai hai jau bavì in te chaud.',
    'El va mintga di a pe al lavur.',
    'Jau na sai betg nua che quest via mena.',
  ],
  fur: [
    'Vuê a buinore al faseve une vore frêt, cussì o ai bevût un tè cjalt.',
    'Al va a pît al lavôr ogni dì.',
    'No sai dulà che al puarte chest troi.',
  ],
  sme: [
    'Odne iđđes lei hui galbmat, danne jugan liekkas deaja.',
    'Son vázzá beaivválaččat bargui.',
    'In dieđe gosa dát geaidnu manná.',
  ],
  hsb: [
    'Dźensa rano bě jara zyma, tuž sym horcy čaj pił.',
    'Wón dźe kóždy dźeń pěši do dźěła.',
    'Njewěm, hdźe tuta puć wjedźe.',
  ],
  ibo: [
    'Ụtụtụ taa oyi na-atụ nke ukwuu, ya mere aṅụrụ m tii ọkụ.',
    'Ọ na-aga ọrụ ije kwa ụbọchị.',
    'Amaghị m ebe okporo ụzọ a na-eje.',
  ],
  aka: [
    'Anɔpa yi awɔw wɔ hɔ paa, enti menom tii a ɛyɛ hyew.',
    'Ɔnantew kɔ adwuma da biara.',
    'Minnim baabi a saa kwan yi kɔ.',
  ],
  wol: [
    'Ci suba si liir na lool, moo tax ma naan attaaya bu tàng.',
    'Dafay dem liggéey ci tànk bés bu nekk.',
    'Xamuma fu yoon wii jëm.',
  ],
  kin: [
    'Uyu munsi mu gitondo hari imbeho nyinshi, ni yo mpamvu nanyoye icyayi gishyushye.',
    'Buri munsi ajya ku kazi n’amaguru.',
    'Sinzi aho uyu muhanda ujya.',
  ],
  nya: [
    'M’mawa muno kunali kuzizira kwambiri, choncho ndinamwa tiyi wotentha.',
    'Amapita kuntchito wapansi tsiku lililonse.',
    'Sindikudziwa kumene msewu uwu ukupita.',
  ],
  sna: [
    'Mangwanani ano kwaitonhora zvikuru, saka ndakanwa tii inopisa.',
    'Anofamba netsoka achienda kubasa zuva rega rega.',
    'Handizivi kwainoenda mugwagwa uyu.',
  ],
  xho: [
    'Kusasa bekubanda kakhulu kakhulu, ngoko ndisele iti eshushu.',
    'Uhamba ngeenyawo esiya emsebenzini yonke imihla.',
    'Andazi ukuba le ndlela iya phi.',
  ],
  sot: [
    'Hoseng ho ne ho bata haholo, kahoo ke ile ka noa tee e chesang.',
    'O tsamaya ka maoto ho ya mosebetsing letsatsi le leng le le leng.',
    'Ha ke tsebe hore na tsela ena e ya kae.',
  ],
  tsn: [
    'Mo mosong go ne go tsidifetse thata, ka jalo ke nwele tee e e mogote.',
    'O tsamaya ka dinao go ya tirong letsatsi le letsatsi.',
    'Ga ke itse gore tsela e e ya kae.',
  ],
  lug: [
    'Ku makya kuno kwali kunnyogoga nnyo, bwentyo nnanywa caayi ayokya.',
    'Atambula n’ebigere okugenda ku mulimu buli lunaku.',
    'Simanyi luwa oluguudo luno gye lugenda.',
  ],
  lin: [
    'Na ntɔngɔ ya lelo malili ezalaki mingi, yango wana namɛlaki tii ya mɔtɔ.',
    'Atambolaka na makolo mpo na kokende na mosala mokolo na mokolo.',
    'Nayebi te epai nzela oyo ekei.',
    'Soki bolingi mpenza koyeba esika moko, bokoki kobima na nzela ya kala.',
    'Nayebi eloko te mpo na yango.',
    'Mikolo ezo ya eza na ba nzela mingi - pona na mayele.',
    'Nayebi ete ozali kobanga te.',
    'Okoki kolakisa ngai nzela ya malamu ?',
    'Nayebi soki mukie te.',
    'Nayebi bana mibali misusu.',
  ],
  bam: [
    'Bi sɔgɔma nɛnɛ tun ka bon kosɛbɛ, o de y’a to ne ye te kalaman min.',
    'A bɛ taa baara la senna don o don.',
    'Ne t’a dɔn sira in be taa yɔrɔ min na.',
  ],
  gaz: [
    'Har ganama bara akkaan qorree ture, kanaafuu shaayii hoʼaa dhuge.',
    'Guyyaa guyyaan miilaan hojiitti deema.',
    'Karaan kun eessa akka geessu hin beeku.',
  ],
  plt: [
    'Nangatsiaka be ny maraina, ka nisotro dite mafana aho.',
    'Mandeha an-tongotra mankany am-piasana isan’andro izy.',
    'Tsy fantatro izay alehan’ity lalana ity.',
  ],
  jav: [
    'Esuk iki hawane adhem banget, mula aku ngombe teh panas.',
    'Dheweke saben dina mlaku menyang kantor.',
    'Aku ora ngerti dalan iki menyang ngendi.',
  ],
  sun: [
    'Isuk ieu hawana tiris pisan, jadi kuring nginum entéh haneut.',
    'Manéhna unggal poé leumpang ka kantor.',
    'Kuring teu nyaho ieu jalan ka mana.',
    'aing teu nyaho manéh bakal ngalakukeun eta poe ieu.',
    'Aing nyaho aing teh bisa ngalakukeun ieu.',
  ],
  ceb: [
    'Bugnaw kaayo ganina buntag, mao nga nag-inom ko ug init nga tsa.',
    'Maglakaw siya padulong sa trabaho matag adlaw.',
    'Wala ko kahibalo asa padulong kini nga dalan.',
  ],
  ilo: [
    'Nalam-ek unay iti bigat, isu a nagin-inumak iti napudot a tsa.',
    'Magmagna a mapan agtrabaho iti inaldaw.',
    'Diak ammo no sadino ti papanan daytoy a dalan.',
    'Para iti ania daytoy?',
    'Sika kadi laeng ti addaan iti tulbek iti daytoy a ridaw?',
    'Dimo kadi kayat daytoy?',
  ],
  kmr: [
    'Vê sibehê pir sar bû, loma min çaya germ vexwar.',
    'Ew her roj bi peyatî diçe kar.',
    'Ez nizanim ev rê diçe ku derê.',
    'Ez nizanim ew çawa kar dike.',
    'Ez nizanim çi dixwazim.',
    'Bawer diçe dibistanê.',
    'Ji bîr neke, serê sibehê em ê biçin kar.',
    'Ez nizanim kî li mala me ye.',
    'Dilê min diçe goşt.',
    'Ez nizanim li vir çi bikim.',
  ],
  tuk: [
    'Bu gün irden howa örän sowukdy, şonuň üçin men gyzgyn çaý içdim.',
    'Ol her gün işe pyýada gidýär.',
    'Bu ýoluň nirä barýanyny bilemok.',
    'Men diýip bilemok.',
    'Men aýdyp bilemok.',
    'Meryñ ony näme üçin edendigini bilemok.',
    'Bu kitaby satyn alyp bilemok.',
  ],
  tet: [
    'Dadeer ohin malirin tebes, tan ne’e ha’u hemu xa manas.',
    'Nia la’o ba serbisu loron-loron.',
    'Ha’u la hatene dalan ne’e ba ne’ebé.',
  ],
  mri: [
    'He tino makariri te ata nei, nō reira i inu au i te tī wera.',
    'Ka hīkoi ia ki te mahi ia rā.',
    'Kāore au i te mōhio ki hea tēnei huarahi.',
    'Kāore au e hiahia ana ki te haere ki te kura.',
    'Kāore tērā i te pai ki a au.',
    'Ko tāku kurī tēnei.',
    'Kāore au e mōhio ki a ia.',
    'Kāore koe i hiahia ki noho ki a au?',
  ],
  smo: [
    'Sa malulu tele le taeao nei, o lea na ou inu ai se lauti vevela.',
    'E savali o ia i le galuega i aso uma.',
    'Ou te le iloa po o fea e alu i ai lenei auala.',
  ],
  ton: [
    'Naʻe momoko ʻaupito ʻa e pongipongi ni, ko ia naʻá ku inu ai ha tī māfana.',
    'ʻOku ʻalu haʻele ia ki he ngāue ʻi he ʻaho kotoa.',
    'ʻOku ʻikai te u ʻilo pe ʻalu ki fē ʻa e hala ni.',
  ],
  fij: [
    'E batabata sara na mataka nikua, o koya au gunuva kina e dua na tī katakata.',
    'E taubale ina cakacaka e veisiga.',
    'Au sega ni kila se lako i vei na gaunisala oqo.',
  ],
  haw: [
    'Ua anu loa kēia kakahiaka, no laila ua inu au i ke kī wela.',
    'Hele wāwae ʻo ia i ka hana i kēlā me kēia lā.',
    'ʻAʻole au i ʻike i hea e hele ai kēia alanui.',
  ],
  tpi: [
    'Long moning nau em i kol tumas, olsem na mi dringim hot ti.',
    'Em i wokabaut i go long wok long olgeta de.',
    'Mi no save rot ia i go we.',
  ],
  que: [
    'Kunan paqarin anchata chirirqan, chayrayku qʼuñi tiyata upyarqani.',
    'Paymi sapa punchaw chakillawan llamkʼaq rin.',
    'Manam yachanichu maytataq kay ñan rin.',
  ],
  aym: [
    'Jichhüru alwaxa wali thayawa, ukatwa juntʼu tiy umtʼawayta.',
    'Jupax sapüru kayuki irnaqawiruw sari.',
    'Janiw yatkti kawksatï aka thakhix sarki.',
  ],
  grn: [
    'Ko pyhareve iporã roʼy, upévare haʼu peteĩ té hakúva.',
    'Haʼe oguata káda ára mbaʼapohápe.',
    'Ndaikuaái moõpa ohoha ko tape.',
    'Mboy mbo\'ehao oĩ nde távape?',
    'Oĩ peteĩ óga guasu che távape.',
    'Upéva piko peteĩ mbarakaja térã peteĩ jagua?',
    'Che róga oĩ ko\'ápe.',
    'Jareko peteĩ jagua.',
    'Jareko peteĩ apañuái.',
    'Jareko peteĩ apañuái piko?',
  ],
  hat: [
    'Maten an te fè frèt anpil, se sa k fè m te bwè yon te cho.',
    'Li mache ale nan travay chak jou.',
    'Mwen pa konnen ki kote wout sa a mennen.',
  ],
  pap: [
    'E mainta aki tabata masha friu, p’esei mi a bebe un te kayente.',
    'E ta kana bai trabou tur dia.',
    'Mi no sa unda e kaminda aki ta bai.',
  ],
  kal: [
    'Ullaaq manna nillernarluinnarpoq, taamaattumik kissartumik teerpallaarpunga.',
    'Ullut tamaasa pisuttuarluni sulisarfimminut pisarpoq.',
    'Naluara aqqut una sumut ingerlasoq.',
  ],
  yue: [
    '今朝好凍，所以我飲咗杯熱茶。',
    '佢每日都行路返工。',
    '我唔知呢條路去邊度。',
  ],
};

/** Every sample for a language, or an empty array if it has none. */
export function samplesFor(code) {
  return SAMPLES[code] || [];
}
