'use client';

import { useState } from 'react';
import Link from 'next/link';
import { getAdvice } from '../lib/petAdvice';
import { theme } from '../lib/theme';

export default function AdvicePage() {
  const [step, setStep] = useState(1);
  const [petType, setPetType] = useState('');
  const [timeElapsed, setTimeElapsed] = useState('');
  const [scenario, setScenario] = useState('');
  const [advice, setAdvice] = useState(null);
  const [copied, setCopied] = useState(false);

  const scenarios = {
    dog: [
      { value: 'jumped_fence', label: 'Jumped Fence' },
      { value: 'door_left_open', label: 'Door Left Open' },
      { value: 'got_spooked', label: 'Got Spooked / Scared' },
      { value: 'unknown', label: 'Unknown / Not Sure' }
    ],
    cat: [
      { value: 'indoor_cat_escaped', label: 'Indoor Cat Escaped' },
      { value: 'outdoor_cat_missing', label: 'Outdoor Cat Missing' }
    ],
    bird: [
      { value: 'flew_away', label: 'Flew Away' }
    ],
    other: [
      { value: 'escaped', label: 'Escaped' }
    ]
  };

  const handlePetTypeSelect = (type) => {
    setPetType(type);
    setStep(2);
  };

  const handleTimeSelect = (time) => {
    setTimeElapsed(time);
    setStep(3);
  };

  const handleScenarioSelect = (scene) => {
    setScenario(scene);
    const result = getAdvice(petType, scene, timeElapsed);
    setAdvice(result);
    setStep(4);
  };

  const handleCopyToClipboard = () => {
    let text = '🚨 PET RECOVERY ACTION PLAN 🚨\n\n';
    text += '⚠️ IMMEDIATE ACTIONS:\n';
    advice.priority.forEach((action, i) => {
      text += `${i + 1}. ${action}\n`;
    });
    text += '\n✅ CHECKLIST:\n';
    advice.checklist.forEach((item, i) => {
      text += `☐ ${item}\n`;
    });
    if (advice.tips && advice.tips.length > 0) {
      text += '\n❌ AVOID THESE MISTAKES:\n';
      advice.tips.forEach((tip, i) => {
        text += `• ${tip}\n`;
      });
    }
    text += `\n💙 ${advice.reassurance}\n`;
    text += '\nGenerated by ReunitePets.org';

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    });
  };

  const handleReset = () => {
    setStep(1);
    setPetType('');
    setTimeElapsed('');
    setScenario('');
    setAdvice(null);
    setCopied(false);
  };

  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(to bottom, #f8fafc 0%, #eef2f7 100%)',
      fontFamily: theme.fonts.sans,
    }}>
      {/* Header */}
      <div style={{
        background: 'rgba(255, 255, 255, 0.95)',
        backdropFilter: 'blur(10px)',
        padding: '1.5rem 2rem',
        boxShadow: theme.shadows.sm,
      }}>
        <div style={{
          maxWidth: '900px',
          margin: '0 auto',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}>
          <Link
            href="/"
            style={{
              fontSize: '1.75rem',
              fontWeight: '800',
              color: '#0f172a',
              textDecoration: 'none',
            }}
          >
            ← ReunitePets
          </Link>
        </div>
      </div>

      <div style={{
        maxWidth: '900px',
        margin: '0 auto',
        padding: '2rem 1rem',
      }}>
        {/* Header */}
        <div style={{
          textAlign: 'center',
          marginBottom: '2rem',
        }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>💡</div>
          <h1 style={{
            fontSize: '2.5rem',
            fontWeight: '900',
            color: '#0f172a',
            marginBottom: '0.5rem',
          }}>
            What To Do If Your Pet Is Lost
          </h1>
          <p style={{
            fontSize: '1.1rem',
            color: theme.colors.gray[700],
          }}>
            Proven recovery strategies tailored to your situation—no account needed
          </p>
        </div>

        {/* Step 1: Pet Type */}
        {step === 1 && (
          <div style={{
            background: 'white',
            borderRadius: theme.radius.xl,
            padding: '3rem 2rem',
            boxShadow: theme.shadows.lg,
          }}>
            <h2 style={{
              fontSize: '1.75rem',
              fontWeight: '800',
              marginBottom: '2rem',
              textAlign: 'center',
              color: theme.colors.gray[900],
            }}>
              What type of pet?
            </h2>
            <div style={{
              display: 'grid',
              gap: '1rem',
            }}>
              {[
                { type: 'dog', emoji: '🐕', label: 'Dog', accent: '#3b82f6' },
                { type: 'cat', emoji: '🐈', label: 'Cat', accent: '#8b5cf6' },
                { type: 'bird', emoji: '🦜', label: 'Bird', accent: '#10b981' },
                { type: 'other', emoji: '🐰', label: 'Other Pet', accent: '#f59e0b' },
              ].map(({ type, emoji, label, accent }) => (
                <button
                  key={type}
                  onClick={() => handlePetTypeSelect(type)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '1rem',
                    width: '100%',
                    padding: '1.1rem 1.25rem',
                    background: '#ffffff',
                    color: '#0f172a', // midnight-900
                    border: '2px solid #e2e8f0', // midnight-200
                    borderRadius: '1rem',
                    fontSize: '1.15rem',
                    fontWeight: '700',
                    textAlign: 'left',
                    cursor: 'pointer',
                    transition: 'border-color 0.18s ease, box-shadow 0.18s ease, transform 0.18s ease',
                    boxShadow: '0 1px 2px rgba(15,23,42,0.04)',
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.borderColor = '#facc15'; // flash-400
                    e.currentTarget.style.boxShadow = '0 6px 18px rgba(15,23,42,0.10)';
                    e.currentTarget.style.transform = 'translateY(-2px)';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.borderColor = '#e2e8f0';
                    e.currentTarget.style.boxShadow = '0 1px 2px rgba(15,23,42,0.04)';
                    e.currentTarget.style.transform = 'none';
                  }}
                  onFocus={(e) => { e.currentTarget.style.borderColor = '#facc15'; }}
                  onBlur={(e) => { e.currentTarget.style.borderColor = '#e2e8f0'; }}
                >
                  <span style={{
                    width: '44px',
                    height: '44px',
                    flexShrink: 0,
                    display: 'inline-flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    borderRadius: '0.75rem',
                    background: `${accent}1a`, // ~10% tint, keeps per-type recognition
                    fontSize: '1.5rem',
                  }}>
                    {emoji}
                  </span>
                  <span style={{ flex: 1 }}>{label}</span>
                  <span style={{ color: '#94a3b8', fontSize: '1.4rem', lineHeight: 1 }} aria-hidden="true">›</span>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Step 2: Time Elapsed */}
        {step === 2 && (
          <div style={{
            background: 'white',
            borderRadius: theme.radius.xl,
            padding: '3rem 2rem',
            boxShadow: theme.shadows.lg,
          }}>
            <h2 style={{
              fontSize: '1.75rem',
              fontWeight: '800',
              marginBottom: '2rem',
              textAlign: 'center',
              color: theme.colors.gray[900],
            }}>
              When did they go missing?
            </h2>
            <div style={{
              display: 'grid',
              gap: '1rem',
            }}>
              {[
                { value: 'less_than_day', label: 'Less Than 24 Hours Ago', color: '#dc2626' },
                { value: 'one_to_three_days', label: '1-3 Days Ago', color: '#ea580c' },
                { value: 'three_to_seven_days', label: '3-7 Days Ago', color: '#f59e0b' },
                { value: 'one_to_two_weeks', label: '1-2 Weeks Ago', color: '#84cc16' },
                { value: 'more_than_two_weeks', label: 'More Than 2 Weeks Ago', color: '#0ea5e9' },
              ].map(({ value, label, color }) => (
                <button
                  key={value}
                  onClick={() => handleTimeSelect(value)}
                  style={{
                    padding: '1.5rem',
                    background: color,
                    color: 'white',
                    border: 'none',
                    borderRadius: theme.radius.lg,
                    fontSize: '1.1rem',
                    fontWeight: '700',
                    cursor: 'pointer',
                    boxShadow: theme.shadows.md,
                    transition: 'transform 0.2s',
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.transform = 'translateY(-4px)'}
                  onMouseLeave={(e) => e.currentTarget.style.transform = 'translateY(0)'}
                >
                  {label}
                </button>
              ))}
            </div>
            <button
              onClick={() => setStep(1)}
              style={{
                marginTop: '2rem',
                padding: '0.75rem',
                background: 'transparent',
                border: 'none',
                color: theme.colors.gray[600],
                cursor: 'pointer',
                fontSize: '1rem',
                fontWeight: '600',
                width: '100%',
              }}
            >
              ← Go Back
            </button>
          </div>
        )}

        {/* Step 3: Scenario */}
        {step === 3 && (
          <div style={{
            background: 'white',
            borderRadius: theme.radius.xl,
            padding: '3rem 2rem',
            boxShadow: theme.shadows.lg,
          }}>
            <h2 style={{
              fontSize: '1.75rem',
              fontWeight: '800',
              marginBottom: '2rem',
              textAlign: 'center',
              color: theme.colors.gray[900],
            }}>
              How did they get out?
            </h2>
            <div style={{
              display: 'grid',
              gap: '1rem',
            }}>
              {scenarios[petType]?.map((scene) => (
                <button
                  key={scene.value}
                  onClick={() => handleScenarioSelect(scene.value)}
                  style={{
                    padding: '1.5rem',
                    background: theme.gradients.ocean,
                    color: 'white',
                    border: 'none',
                    borderRadius: theme.radius.lg,
                    fontSize: '1.1rem',
                    fontWeight: '700',
                    cursor: 'pointer',
                    boxShadow: theme.shadows.md,
                    transition: 'transform 0.2s',
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.transform = 'translateY(-4px)'}
                  onMouseLeave={(e) => e.currentTarget.style.transform = 'translateY(0)'}
                >
                  {scene.label}
                </button>
              ))}
            </div>
            <button
              onClick={() => setStep(2)}
              style={{
                marginTop: '2rem',
                padding: '0.75rem',
                background: 'transparent',
                border: 'none',
                color: theme.colors.gray[600],
                cursor: 'pointer',
                fontSize: '1rem',
                fontWeight: '600',
                width: '100%',
              }}
            >
              ← Go Back
            </button>
          </div>
        )}

        {/* Step 4: Advice Display */}
        {step === 4 && advice && (
          <div>
            {/* Immediate Actions */}
            <div style={{
              background: 'white',
              borderRadius: theme.radius.xl,
              padding: '2rem',
              marginBottom: '1.5rem',
              border: `3px solid ${theme.colors.status.active}`,
              boxShadow: theme.shadows.lg,
            }}>
              <h2 style={{
                fontSize: '1.75rem',
                fontWeight: '800',
                color: theme.colors.status.active,
                marginBottom: '1.5rem',
                display: 'flex',
                alignItems: 'center',
                gap: '0.75rem',
              }}>
                ⚠️ IMMEDIATE ACTIONS
              </h2>
              <ol style={{
                marginLeft: '1.5rem',
                fontSize: '1.05rem',
                lineHeight: '1.8',
                color: theme.colors.gray[800],
              }}>
                {advice.priority.map((action, index) => (
                  <li key={index} style={{ marginBottom: '1rem', fontWeight: '600' }}>
                    {action}
                  </li>
                ))}
              </ol>
            </div>

            {/* Checklist */}
            {advice.checklist && advice.checklist.length > 0 && (
              <div style={{
                background: 'white',
                borderRadius: theme.radius.xl,
                padding: '2rem',
                marginBottom: '1.5rem',
                boxShadow: theme.shadows.md,
              }}>
                <h2 style={{
                  fontSize: '1.75rem',
                  fontWeight: '800',
                  color: theme.colors.patrol.primary,
                  marginBottom: '1.5rem',
                }}>
                  ✅ CHECKLIST
                </h2>
                <div style={{
                  fontSize: '1.05rem',
                  lineHeight: '1.8',
                  color: theme.colors.gray[800],
                }}>
                  {advice.checklist.map((item, index) => (
                    <div key={index} style={{
                      marginBottom: '1rem',
                      display: 'flex',
                      alignItems: 'flex-start',
                      gap: '1rem',
                    }}>
                      <input
                        type="checkbox"
                        style={{
                          width: '24px',
                          height: '24px',
                          marginTop: '0.25rem',
                          cursor: 'pointer',
                          flexShrink: 0,
                        }}
                      />
                      <span>{item}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Mistakes to Avoid */}
            {advice.tips && advice.tips.length > 0 && (
              <div style={{
                background: 'white',
                borderRadius: theme.radius.xl,
                padding: '2rem',
                marginBottom: '1.5rem',
                boxShadow: theme.shadows.md,
              }}>
                <h2 style={{
                  fontSize: '1.75rem',
                  fontWeight: '800',
                  color: theme.colors.warning,
                  marginBottom: '1.5rem',
                }}>
                  ❌ AVOID THESE MISTAKES
                </h2>
                <ul style={{
                  marginLeft: '1.5rem',
                  fontSize: '1.05rem',
                  lineHeight: '1.8',
                  color: theme.colors.gray[800],
                }}>
                  {advice.tips.map((tip, index) => (
                    <li key={index} style={{ marginBottom: '1rem' }}>
                      {tip}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Reassurance */}
            <div style={{
              background: theme.gradients.hope,
              borderRadius: theme.radius.xl,
              padding: '2rem',
              marginBottom: '2rem',
              textAlign: 'center',
              color: 'white',
              boxShadow: theme.shadows.lg,
            }}>
              <p style={{
                fontSize: '1.25rem',
                fontWeight: '600',
                lineHeight: '1.6',
              }}>
                💙 {advice.reassurance}
              </p>
            </div>

            {/* Action Buttons */}
            <div style={{
              display: 'grid',
              gap: '1rem',
            }}>
              <Link
                href="/report/new"
                style={{
                  padding: '1.5rem',
                  background: '#dc2626',
                  color: 'white',
                  border: 'none',
                  borderRadius: theme.radius.lg,
                  fontSize: '1.2rem',
                  fontWeight: '800',
                  textDecoration: 'none',
                  display: 'block',
                  textAlign: 'center',
                  boxShadow: '0 4px 12px rgba(220, 38, 38, 0.3)',
                }}
              >
                🚨 Report Lost Pet & Alert Community
              </Link>

              <button
                onClick={handleCopyToClipboard}
                style={{
                  padding: '1rem',
                  background: copied ? '#10b981' : '#f1f5f9',
                  color: copied ? 'white' : '#64748b',
                  border: '2px solid #e2e8f0',
                  borderRadius: theme.radius.lg,
                  fontSize: '0.95rem',
                  fontWeight: '600',
                  cursor: 'pointer',
                  boxShadow: 'none',
                }}
              >
                {copied ? '✓ Copied!' : 'Copy Info'}
              </button>

              <button
                onClick={handleReset}
                style={{
                  padding: '1.25rem',
                  background: 'white',
                  color: theme.colors.gray[700],
                  border: `2px solid ${theme.colors.gray[300]}`,
                  borderRadius: theme.radius.lg,
                  fontSize: '1.1rem',
                  fontWeight: '700',
                  cursor: 'pointer',
                }}
              >
                🔄 Start Over
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
