// Comprehensive breed lists for different species

export const DOG_BREEDS = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog",
  "American Eskimo Dog",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Boston Terrier",
  "Boxer",
  "Brittany",
  "Brussels Griffon",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chinese Crested",
  "Chow Chow",
  "Cocker Spaniel",
  "Collie",
  "Corgi (Cardigan Welsh)",
  "Corgi (Pembroke Welsh)",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "Dogo Argentino",
  "English Bulldog",
  "English Setter",
  "English Springer Spaniel",
  "French Bulldog",
  "German Shepherd",
  "German Shorthaired Pointer",
  "Golden Retriever",
  "Great Dane",
  "Great Pyrenees",
  "Greyhound",
  "Havanese",
  "Husky (Siberian)",
  "Irish Setter",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Labrador Retriever",
  "Lhasa Apso",
  "Maltese",
  "Mastiff",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Mixed Breed",
  "Newfoundland",
  "Old English Sheepdog",
  "Papillon",
  "Pekingese",
  "Pit Bull",
  "Pointer",
  "Pomeranian",
  "Poodle (Miniature)",
  "Poodle (Standard)",
  "Poodle (Toy)",
  "Pug",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saint Bernard",
  "Samoyed",
  "Schnauzer (Giant)",
  "Schnauzer (Miniature)",
  "Schnauzer (Standard)",
  "Scottish Terrier",
  "Shar Pei",
  "Shiba Inu",
  "Shih Tzu",
  "Staffordshire Bull Terrier",
  "Vizsla",
  "Weimaraner",
  "West Highland White Terrier",
  "Whippet",
  "Yorkshire Terrier",
];

export const CAT_BREEDS = [
  "Abyssinian",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "Balinese",
  "Bengal",
  "Birman",
  "Bombay",
  "British Shorthair",
  "Burmese",
  "Calico",
  "Chartreux",
  "Cornish Rex",
  "Devon Rex",
  "Domestic Longhair",
  "Domestic Shorthair",
  "Egyptian Mau",
  "Exotic Shorthair",
  "Havana Brown",
  "Himalayan",
  "Japanese Bobtail",
  "Korat",
  "Maine Coon",
  "Manx",
  "Mixed Breed",
  "Munchkin",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental",
  "Persian",
  "Ragdoll",
  "Russian Blue",
  "Scottish Fold",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Somali",
  "Sphynx",
  "Tabby",
  "Tonkinese",
  "Tortoiseshell",
  "Turkish Angora",
  "Turkish Van",
];

export const BIRD_BREEDS = [
  "African Grey Parrot",
  "Amazon Parrot",
  "Budgerigar (Budgie)",
  "Canary",
  "Cockatiel",
  "Cockatoo",
  "Conure",
  "Dove",
  "Eclectus Parrot",
  "Finch",
  "Lovebird",
  "Macaw",
  "Parakeet",
  "Parrot",
  "Pigeon",
  "Quaker Parrot",
  "Senegal Parrot",
];

export const RABBIT_BREEDS = [
  "American",
  "Angora",
  "Belgian Hare",
  "Californian",
  "Checkered Giant",
  "Dutch",
  "Flemish Giant",
  "French Lop",
  "Harlequin",
  "Havana",
  "Holland Lop",
  "Lionhead",
  "Mini Lop",
  "Mini Rex",
  "Mixed Breed",
  "Netherland Dwarf",
  "New Zealand",
  "Polish",
  "Rex",
  "Satin",
  "Silver",
];

export function getBreedsForSpecies(species) {
  const speciesMap = {
    'DOG': DOG_BREEDS,
    'CAT': CAT_BREEDS,
    'BIRD': BIRD_BREEDS,
    'RABBIT': RABBIT_BREEDS,
    'OTHER': [],
  };
  return speciesMap[species] || [];
}
