'use client';

import { useState } from 'react';
import { getAdvice } from '../../lib/petAdvice';

export default function ReportLostPet() {
  const [step, setStep] = useState(1);
  const [petType, setPetType] = useState('');
  const [timeElapsed, setTimeElapsed] = useState('');
  const [scenario, setScenario] = useState('');
  const [advice, setAdvice] = useState(null);
  const [copied, setCopied] = useState(false);

  const scenarios = {
    dog: [
      { value: 'jumped_fence', label: 'Jumped Fence' },
      { value: 'door_left_open', label: 'Door Left Open' },
      { value: 'got_spooked', label: 'Got Spooked / Scared' },
      { value: 'unknown', label: 'Unknown / Not Sure' }
    ],
    cat: [
      { value: 'indoor_cat_escaped', label: 'Indoor Cat Escaped' },
      { value: 'outdoor_cat_missing', label: 'Outdoor Cat Missing' }
    ],
    bird: [
      { value: 'flew_away', label: 'Flew Away' }
    ],
    other: [
      { value: 'escaped', label: 'Escaped' }
    ]
  };

  const handlePetTypeSelect = (type) => {
    setPetType(type);
    setStep(2);
  };

  const handleTimeSelect = (time) => {
    setTimeElapsed(time);
    setStep(3);
  };

  const handleScenarioSelect = (scene) => {
    setScenario(scene);
    const result = getAdvice(petType, scene, timeElapsed);
    setAdvice(result);
    setStep(4);
  };

  const handleCopyToClipboard = () => {
    let text = '🚨 PET RECOVERY ACTION PLAN 🚨\n\n';

    text += '⚠️ IMMEDIATE ACTIONS:\n';
    advice.priority.forEach((action, i) => {
      text += `${i + 1}. ${action}\n`;
    });

    text += '\n✅ CHECKLIST:\n';
    advice.checklist.forEach((item, i) => {
      text += `☐ ${item}\n`;
    });

    if (advice.tips && advice.tips.length > 0) {
      text += '\n❌ AVOID THESE MISTAKES:\n';
      advice.tips.forEach((tip, i) => {
        text += `• ${tip}\n`;
      });
    }

    text += `\n💙 ${advice.reassurance}\n`;
    text += '\nGenerated by PetRecovery.org';

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    });
  };

  const handleReset = () => {
    setStep(1);
    setPetType('');
    setTimeElapsed('');
    setScenario('');
    setAdvice(null);
    setCopied(false);
  };

  const buttonStyle = {
    padding: '1.25rem 2rem',
    fontSize: '1.125rem',
    fontWeight: '600',
    borderRadius: '0.75rem',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
    maxWidth: '400px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.2s',
    marginBottom: '1rem',
    minHeight: '60px',
    touchAction: 'manipulation',
  };

  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(to bottom, #fef3c7, #fde68a)',
      padding: '1rem',
      fontFamily: 'system-ui, -apple-system, sans-serif',
    }}>
      <div style={{
        maxWidth: '800px',
        margin: '0 auto',
        paddingTop: '2rem',
      }}>
        {/* Header */}
        <div style={{
          textAlign: 'center',
          marginBottom: '2rem',
        }}>
          <h1 style={{
            fontSize: '2rem',
            fontWeight: 'bold',
            color: '#b91c1c',
            marginBottom: '0.5rem',
          }}>
            🚨 Lost Pet Emergency
          </h1>
          <p style={{
            fontSize: '1rem',
            color: '#78350f',
          }}>
            Get immediate, expert advice for your situation
          </p>
        </div>

        {/* Step 1: Pet Type */}
        {step === 1 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '1.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              What type of pet is missing?
            </h2>
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '0.75rem',
            }}>
              <button
                onClick={() => handlePetTypeSelect('dog')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#3b82f6',
                  color: 'white',
                }}
              >
                🐕 Dog
              </button>
              <button
                onClick={() => handlePetTypeSelect('cat')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#8b5cf6',
                  color: 'white',
                }}
              >
                🐈 Cat
              </button>
              <button
                onClick={() => handlePetTypeSelect('bird')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#10b981',
                  color: 'white',
                }}
              >
                🦜 Bird
              </button>
              <button
                onClick={() => handlePetTypeSelect('other')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#f59e0b',
                  color: 'white',
                }}
              >
                🐰 Other Pet
              </button>
            </div>
          </div>
        )}

        {/* Step 2: Time Elapsed */}
        {step === 2 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '1.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              When did they go missing?
            </h2>
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '0.75rem',
            }}>
              <button
                onClick={() => handleTimeSelect('just_now')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#dc2626',
                  color: 'white',
                }}
              >
                ⏰ Just Now (within last hour)
              </button>
              <button
                onClick={() => handleTimeSelect('hours_ago')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#ea580c',
                  color: 'white',
                }}
              >
                🕐 Hours Ago (1-12 hours)
              </button>
              <button
                onClick={() => handleTimeSelect('yesterday')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#f59e0b',
                  color: 'white',
                }}
              >
                📅 Yesterday (12-48 hours)
              </button>
              <button
                onClick={() => handleTimeSelect('days_ago')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#84cc16',
                  color: 'white',
                }}
              >
                📆 Days Ago (2+ days)
              </button>
            </div>
            <button
              onClick={() => setStep(1)}
              style={{
                marginTop: '1.5rem',
                padding: '0.75rem',
                backgroundColor: 'transparent',
                border: 'none',
                color: '#6b7280',
                cursor: 'pointer',
                width: '100%',
                fontSize: '0.875rem',
              }}
            >
              ← Go Back
            </button>
          </div>
        )}

        {/* Step 3: Scenario */}
        {step === 3 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '1.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              How did they get out?
            </h2>
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '0.75rem',
            }}>
              {scenarios[petType]?.map((scene) => (
                <button
                  key={scene.value}
                  onClick={() => handleScenarioSelect(scene.value)}
                  style={{
                    ...buttonStyle,
                    backgroundColor: '#6366f1',
                    color: 'white',
                  }}
                >
                  {scene.label}
                </button>
              ))}
            </div>
            <button
              onClick={() => setStep(2)}
              style={{
                marginTop: '1.5rem',
                padding: '0.75rem',
                backgroundColor: 'transparent',
                border: 'none',
                color: '#6b7280',
                cursor: 'pointer',
                width: '100%',
                fontSize: '0.875rem',
              }}
            >
              ← Go Back
            </button>
          </div>
        )}

        {/* Step 4: Advice Display */}
        {step === 4 && advice && (
          <div>
            {/* Immediate Actions */}
            <div style={{
              backgroundColor: '#fee2e2',
              borderRadius: '1rem',
              padding: '1.5rem',
              marginBottom: '1rem',
              border: '3px solid #dc2626',
            }}>
              <h2 style={{
                fontSize: '1.5rem',
                fontWeight: 'bold',
                color: '#dc2626',
                marginBottom: '1rem',
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem',
              }}>
                ⚠️ IMMEDIATE ACTIONS
              </h2>
              <ol style={{
                marginLeft: '1.5rem',
                fontSize: '1rem',
                lineHeight: '1.8',
                color: '#7f1d1d',
              }}>
                {advice.priority.map((action, index) => (
                  <li key={index} style={{ marginBottom: '0.75rem', fontWeight: '600' }}>
                    {action}
                  </li>
                ))}
              </ol>
            </div>

            {/* Checklist */}
            {advice.checklist && advice.checklist.length > 0 && (
              <div style={{
                backgroundColor: 'white',
                borderRadius: '1rem',
                padding: '1.5rem',
                marginBottom: '1rem',
                border: '2px solid #3b82f6',
              }}>
                <h2 style={{
                  fontSize: '1.5rem',
                  fontWeight: 'bold',
                  color: '#1e40af',
                  marginBottom: '1rem',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                }}>
                  ✅ CHECKLIST
                </h2>
                <div style={{
                  fontSize: '1rem',
                  lineHeight: '1.8',
                  color: '#1f2937',
                }}>
                  {advice.checklist.map((item, index) => (
                    <div key={index} style={{
                      marginBottom: '0.75rem',
                      display: 'flex',
                      alignItems: 'flex-start',
                      gap: '0.75rem',
                    }}>
                      <input
                        type="checkbox"
                        style={{
                          width: '20px',
                          height: '20px',
                          marginTop: '0.25rem',
                          cursor: 'pointer',
                          flexShrink: 0,
                        }}
                      />
                      <span>{item}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Mistakes to Avoid */}
            {advice.tips && advice.tips.length > 0 && (
              <div style={{
                backgroundColor: '#fef3c7',
                borderRadius: '1rem',
                padding: '1.5rem',
                marginBottom: '1rem',
                border: '2px solid #f59e0b',
              }}>
                <h2 style={{
                  fontSize: '1.5rem',
                  fontWeight: 'bold',
                  color: '#92400e',
                  marginBottom: '1rem',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                }}>
                  ❌ AVOID THESE MISTAKES
                </h2>
                <ul style={{
                  marginLeft: '1.5rem',
                  fontSize: '1rem',
                  lineHeight: '1.8',
                  color: '#78350f',
                }}>
                  {advice.tips.map((tip, index) => (
                    <li key={index} style={{ marginBottom: '0.75rem' }}>
                      {tip}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Reassurance */}
            <div style={{
              backgroundColor: '#dbeafe',
              borderRadius: '1rem',
              padding: '1.5rem',
              marginBottom: '1rem',
              border: '2px solid #3b82f6',
              textAlign: 'center',
            }}>
              <p style={{
                fontSize: '1.125rem',
                fontWeight: '600',
                color: '#1e40af',
                lineHeight: '1.6',
              }}>
                💙 {advice.reassurance}
              </p>
            </div>

            {/* Action Buttons */}
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '1rem',
              marginTop: '2rem',
            }}>
              <button
                onClick={handleCopyToClipboard}
                style={{
                  ...buttonStyle,
                  backgroundColor: copied ? '#10b981' : '#8b5cf6',
                  color: 'white',
                  maxWidth: '100%',
                }}
              >
                {copied ? '✓ Copied!' : '📱 Text This To Me'}
              </button>
              <button
                onClick={handleReset}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#6b7280',
                  color: 'white',
                  maxWidth: '100%',
                }}
              >
                🔄 Start Over
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
