'use client';

import { useState } from 'react';
import { getAdvice } from '../../lib/petAdvice';

export default function ReportLostPet() {
  const [step, setStep] = useState(1);
  const [petType, setPetType] = useState('');
  const [timeElapsed, setTimeElapsed] = useState('');
  const [scenario, setScenario] = useState('');
  const [advice, setAdvice] = useState(null);
  const [copied, setCopied] = useState(false);

  // Report submission data
  const [reportData, setReportData] = useState({
    // User info
    email: '',
    phone: '',
    firstName: '',
    // Pet info
    petName: '',
    breed: '',
    color: '',
    size: 'MEDIUM',
    age: '',
    sex: 'UNKNOWN',
    distinctiveMarks: '',
    microchipId: '',
    // Location
    lastSeenAddress: '',
    lastSeenDetails: '',
    // Photos
    photos: [],
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState(null);
  const [reportId, setReportId] = useState(null);

  const scenarios = {
    dog: [
      { value: 'jumped_fence', label: 'Jumped Fence' },
      { value: 'door_left_open', label: 'Door Left Open' },
      { value: 'got_spooked', label: 'Got Spooked / Scared' },
      { value: 'unknown', label: 'Unknown / Not Sure' }
    ],
    cat: [
      { value: 'indoor_cat_escaped', label: 'Indoor Cat Escaped' },
      { value: 'outdoor_cat_missing', label: 'Outdoor Cat Missing' }
    ],
    bird: [
      { value: 'flew_away', label: 'Flew Away' }
    ],
    other: [
      { value: 'escaped', label: 'Escaped' }
    ]
  };

  const handlePetTypeSelect = (type) => {
    setPetType(type);
    setStep(2);
  };

  const handleTimeSelect = (time) => {
    setTimeElapsed(time);
    setStep(3);
  };

  const handleScenarioSelect = (scene) => {
    setScenario(scene);
    const result = getAdvice(petType, scene, timeElapsed);
    setAdvice(result);
    setStep(4);
  };

  const handleCopyToClipboard = () => {
    let text = '🚨 PET RECOVERY ACTION PLAN 🚨\n\n';

    text += '⚠️ IMMEDIATE ACTIONS:\n';
    advice.priority.forEach((action, i) => {
      text += `${i + 1}. ${action}\n`;
    });

    text += '\n✅ CHECKLIST:\n';
    advice.checklist.forEach((item, i) => {
      text += `☐ ${item}\n`;
    });

    if (advice.tips && advice.tips.length > 0) {
      text += '\n❌ AVOID THESE MISTAKES:\n';
      advice.tips.forEach((tip, i) => {
        text += `• ${tip}\n`;
      });
    }

    text += `\n💙 ${advice.reassurance}\n`;
    text += '\nGenerated by PetRecovery.org';

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    });
  };

  const handleReset = () => {
    setStep(1);
    setPetType('');
    setTimeElapsed('');
    setScenario('');
    setAdvice(null);
    setCopied(false);
  };

  const buttonStyle = {
    padding: '1.25rem 2rem',
    fontSize: '1.125rem',
    fontWeight: '600',
    borderRadius: '0.75rem',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
    maxWidth: '400px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.2s',
    marginBottom: '1rem',
    minHeight: '60px',
    touchAction: 'manipulation',
  };

  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(to bottom, #fef3c7, #fde68a)',
      padding: '1rem',
      fontFamily: 'system-ui, -apple-system, sans-serif',
    }}>
      <div style={{
        maxWidth: '800px',
        margin: '0 auto',
        paddingTop: '2rem',
      }}>
        {/* Header */}
        <div style={{
          textAlign: 'center',
          marginBottom: '2rem',
        }}>
          <h1 style={{
            fontSize: '2rem',
            fontWeight: 'bold',
            color: '#b91c1c',
            marginBottom: '0.5rem',
          }}>
            🚨 Lost Pet Emergency
          </h1>
          <p style={{
            fontSize: '1rem',
            color: '#78350f',
          }}>
            Get immediate, expert advice for your situation
          </p>
        </div>

        {/* Step 1: Pet Type */}
        {step === 1 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '1.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              What type of pet is missing?
            </h2>
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '0.75rem',
            }}>
              <button
                onClick={() => handlePetTypeSelect('dog')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#3b82f6',
                  color: 'white',
                }}
              >
                🐕 Dog
              </button>
              <button
                onClick={() => handlePetTypeSelect('cat')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#8b5cf6',
                  color: 'white',
                }}
              >
                🐈 Cat
              </button>
              <button
                onClick={() => handlePetTypeSelect('bird')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#10b981',
                  color: 'white',
                }}
              >
                🦜 Bird
              </button>
              <button
                onClick={() => handlePetTypeSelect('other')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#f59e0b',
                  color: 'white',
                }}
              >
                🐰 Other Pet
              </button>
            </div>
          </div>
        )}

        {/* Step 2: Time Elapsed */}
        {step === 2 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '1.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              When did they go missing?
            </h2>
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '0.75rem',
            }}>
              <button
                onClick={() => handleTimeSelect('less_than_day')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#dc2626',
                  color: 'white',
                }}
              >
                ⏰ Less Than 24 Hours Ago
              </button>
              <button
                onClick={() => handleTimeSelect('one_to_three_days')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#ea580c',
                  color: 'white',
                }}
              >
                📅 1-3 Days Ago
              </button>
              <button
                onClick={() => handleTimeSelect('three_to_seven_days')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#f59e0b',
                  color: 'white',
                }}
              >
                📆 3-7 Days Ago
              </button>
              <button
                onClick={() => handleTimeSelect('one_to_two_weeks')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#84cc16',
                  color: 'white',
                }}
              >
                🗓️ 1-2 Weeks Ago
              </button>
              <button
                onClick={() => handleTimeSelect('more_than_two_weeks')}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#0ea5e9',
                  color: 'white',
                }}
              >
                📊 More Than 2 Weeks Ago
              </button>
            </div>
            <button
              onClick={() => setStep(1)}
              style={{
                marginTop: '1.5rem',
                padding: '0.75rem',
                backgroundColor: 'transparent',
                border: 'none',
                color: '#6b7280',
                cursor: 'pointer',
                width: '100%',
                fontSize: '0.875rem',
              }}
            >
              ← Go Back
            </button>
          </div>
        )}

        {/* Step 3: Scenario */}
        {step === 3 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '1.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              How did they get out?
            </h2>
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '0.75rem',
            }}>
              {scenarios[petType]?.map((scene) => (
                <button
                  key={scene.value}
                  onClick={() => handleScenarioSelect(scene.value)}
                  style={{
                    ...buttonStyle,
                    backgroundColor: '#6366f1',
                    color: 'white',
                  }}
                >
                  {scene.label}
                </button>
              ))}
            </div>
            <button
              onClick={() => setStep(2)}
              style={{
                marginTop: '1.5rem',
                padding: '0.75rem',
                backgroundColor: 'transparent',
                border: 'none',
                color: '#6b7280',
                cursor: 'pointer',
                width: '100%',
                fontSize: '0.875rem',
              }}
            >
              ← Go Back
            </button>
          </div>
        )}

        {/* Step 4: Advice Display */}
        {step === 4 && advice && (
          <div>
            {/* Immediate Actions */}
            <div style={{
              backgroundColor: '#fee2e2',
              borderRadius: '1rem',
              padding: '1.5rem',
              marginBottom: '1rem',
              border: '3px solid #dc2626',
            }}>
              <h2 style={{
                fontSize: '1.5rem',
                fontWeight: 'bold',
                color: '#dc2626',
                marginBottom: '1rem',
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem',
              }}>
                ⚠️ IMMEDIATE ACTIONS
              </h2>
              <ol style={{
                marginLeft: '1.5rem',
                fontSize: '1rem',
                lineHeight: '1.8',
                color: '#7f1d1d',
              }}>
                {advice.priority.map((action, index) => (
                  <li key={index} style={{ marginBottom: '0.75rem', fontWeight: '600' }}>
                    {action}
                  </li>
                ))}
              </ol>
            </div>

            {/* Checklist */}
            {advice.checklist && advice.checklist.length > 0 && (
              <div style={{
                backgroundColor: 'white',
                borderRadius: '1rem',
                padding: '1.5rem',
                marginBottom: '1rem',
                border: '2px solid #3b82f6',
              }}>
                <h2 style={{
                  fontSize: '1.5rem',
                  fontWeight: 'bold',
                  color: '#1e40af',
                  marginBottom: '1rem',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                }}>
                  ✅ CHECKLIST
                </h2>
                <div style={{
                  fontSize: '1rem',
                  lineHeight: '1.8',
                  color: '#1f2937',
                }}>
                  {advice.checklist.map((item, index) => (
                    <div key={index} style={{
                      marginBottom: '0.75rem',
                      display: 'flex',
                      alignItems: 'flex-start',
                      gap: '0.75rem',
                    }}>
                      <input
                        type="checkbox"
                        style={{
                          width: '20px',
                          height: '20px',
                          marginTop: '0.25rem',
                          cursor: 'pointer',
                          flexShrink: 0,
                        }}
                      />
                      <span>{item}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Mistakes to Avoid */}
            {advice.tips && advice.tips.length > 0 && (
              <div style={{
                backgroundColor: '#fef3c7',
                borderRadius: '1rem',
                padding: '1.5rem',
                marginBottom: '1rem',
                border: '2px solid #f59e0b',
              }}>
                <h2 style={{
                  fontSize: '1.5rem',
                  fontWeight: 'bold',
                  color: '#92400e',
                  marginBottom: '1rem',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                }}>
                  ❌ AVOID THESE MISTAKES
                </h2>
                <ul style={{
                  marginLeft: '1.5rem',
                  fontSize: '1rem',
                  lineHeight: '1.8',
                  color: '#78350f',
                }}>
                  {advice.tips.map((tip, index) => (
                    <li key={index} style={{ marginBottom: '0.75rem' }}>
                      {tip}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Reassurance */}
            <div style={{
              backgroundColor: '#dbeafe',
              borderRadius: '1rem',
              padding: '1.5rem',
              marginBottom: '1rem',
              border: '2px solid #3b82f6',
              textAlign: 'center',
            }}>
              <p style={{
                fontSize: '1.125rem',
                fontWeight: '600',
                color: '#1e40af',
                lineHeight: '1.6',
              }}>
                💙 {advice.reassurance}
              </p>
            </div>

            {/* Action Buttons */}
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '1rem',
              marginTop: '2rem',
            }}>
              <button
                onClick={handleCopyToClipboard}
                style={{
                  ...buttonStyle,
                  backgroundColor: copied ? '#10b981' : '#8b5cf6',
                  color: 'white',
                  maxWidth: '100%',
                }}
              >
                {copied ? '✓ Copied!' : '📱 Text This To Me'}
              </button>

              <button
                onClick={() => setStep(5)}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#dc2626',
                  color: 'white',
                  maxWidth: '100%',
                }}
              >
                🚨 Alert My Community
              </button>

              <button
                onClick={handleReset}
                style={{
                  ...buttonStyle,
                  backgroundColor: '#6b7280',
                  color: 'white',
                  maxWidth: '100%',
                }}
              >
                🔄 Start Over
              </button>
            </div>
          </div>
        )}

        {/* Step 5: Contact Info */}
        {step === 5 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '0.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              Your Contact Information
            </h2>
            <p style={{
              textAlign: 'center',
              color: '#6b7280',
              marginBottom: '2rem',
            }}>
              So community members can reach you if they spot your pet
            </p>

            {submitError && (
              <div style={{
                backgroundColor: '#fee2e2',
                border: '1px solid #fecaca',
                color: '#991b1b',
                padding: '1rem',
                borderRadius: '0.5rem',
                marginBottom: '1.5rem',
              }}>
                {submitError}
              </div>
            )}

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Your First Name *
              </label>
              <input
                type="text"
                value={reportData.firstName}
                onChange={(e) => setReportData({ ...reportData, firstName: e.target.value })}
                placeholder="Jane"
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                }}
                required
              />
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Email Address *
              </label>
              <input
                type="email"
                value={reportData.email}
                onChange={(e) => setReportData({ ...reportData, email: e.target.value })}
                placeholder="jane@example.com"
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                }}
                required
              />
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Phone Number *
              </label>
              <input
                type="tel"
                value={reportData.phone}
                onChange={(e) => setReportData({ ...reportData, phone: e.target.value })}
                placeholder="555-0100"
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                }}
                required
              />
              <p style={{ fontSize: '0.875rem', color: '#6b7280', marginTop: '0.5rem' }}>
                Community members will call/text if they spot your pet
              </p>
            </div>

            <div style={{ display: 'flex', gap: '1rem', marginTop: '2rem' }}>
              <button
                onClick={() => setStep(4)}
                style={{
                  flex: 1,
                  padding: '1rem',
                  backgroundColor: '#e5e7eb',
                  color: '#1f2937',
                  border: 'none',
                  borderRadius: '0.5rem',
                  fontSize: '1.125rem',
                  fontWeight: '600',
                  cursor: 'pointer',
                }}
              >
                Back
              </button>
              <button
                onClick={() => setStep(6)}
                disabled={!reportData.firstName || !reportData.email || !reportData.phone}
                style={{
                  flex: 1,
                  padding: '1rem',
                  backgroundColor: (!reportData.firstName || !reportData.email || !reportData.phone) ? '#9ca3af' : '#2563eb',
                  color: 'white',
                  border: 'none',
                  borderRadius: '0.5rem',
                  fontSize: '1.125rem',
                  fontWeight: '600',
                  cursor: (!reportData.firstName || !reportData.email || !reportData.phone) ? 'not-allowed' : 'pointer',
                }}
              >
                Continue
              </button>
            </div>
          </div>
        )}

        {/* Step 6: Pet Details */}
        {step === 6 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '0.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              About Your Pet
            </h2>
            <p style={{
              textAlign: 'center',
              color: '#6b7280',
              marginBottom: '2rem',
            }}>
              Details help people identify your pet
            </p>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Pet's Name *
              </label>
              <input
                type="text"
                value={reportData.petName}
                onChange={(e) => setReportData({ ...reportData, petName: e.target.value })}
                placeholder="Max"
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                }}
                required
              />
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
              <div>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                  Breed
                </label>
                <input
                  type="text"
                  value={reportData.breed}
                  onChange={(e) => setReportData({ ...reportData, breed: e.target.value })}
                  placeholder="Golden Retriever"
                  style={{
                    width: '100%',
                    padding: '0.75rem',
                    border: '2px solid #e5e7eb',
                    borderRadius: '0.5rem',
                    fontSize: '1rem',
                  }}
                />
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                  Age
                </label>
                <input
                  type="number"
                  value={reportData.age}
                  onChange={(e) => setReportData({ ...reportData, age: e.target.value })}
                  placeholder="3"
                  style={{
                    width: '100%',
                    padding: '0.75rem',
                    border: '2px solid #e5e7eb',
                    borderRadius: '0.5rem',
                    fontSize: '1rem',
                  }}
                />
              </div>
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Primary Color/Markings *
              </label>
              <input
                type="text"
                value={reportData.color}
                onChange={(e) => setReportData({ ...reportData, color: e.target.value })}
                placeholder="Golden with white chest"
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                }}
                required
              />
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Size
              </label>
              <select
                value={reportData.size}
                onChange={(e) => setReportData({ ...reportData, size: e.target.value })}
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                }}
              >
                {petType === 'bird' ? (
                  <>
                    <option value="TINY">Small (Parakeet, Finch)</option>
                    <option value="SMALL">Medium (Cockatiel, Conure)</option>
                    <option value="MEDIUM">Large (African Grey, Amazon)</option>
                    <option value="LARGE">Very Large (Macaw, Cockatoo)</option>
                  </>
                ) : petType === 'cat' ? (
                  <>
                    <option value="TINY">Small (&lt; 8 lbs)</option>
                    <option value="SMALL">Medium (8-12 lbs)</option>
                    <option value="MEDIUM">Large (12-18 lbs)</option>
                    <option value="LARGE">Very Large (&gt; 18 lbs)</option>
                  </>
                ) : (
                  <>
                    <option value="TINY">Tiny (&lt; 10 lbs)</option>
                    <option value="SMALL">Small (10-25 lbs)</option>
                    <option value="MEDIUM">Medium (25-60 lbs)</option>
                    <option value="LARGE">Large (60-90 lbs)</option>
                    <option value="GIANT">Giant (&gt; 90 lbs)</option>
                  </>
                )}
              </select>
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Distinctive Marks or Features
              </label>
              <textarea
                value={reportData.distinctiveMarks}
                onChange={(e) => setReportData({ ...reportData, distinctiveMarks: e.target.value })}
                placeholder="Black spot on left ear, scar on right paw, very friendly..."
                rows={3}
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                  fontFamily: 'inherit',
                }}
              />
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Microchip ID (if applicable)
              </label>
              <input
                type="text"
                value={reportData.microchipId}
                onChange={(e) => setReportData({ ...reportData, microchipId: e.target.value })}
                placeholder="123456789012345"
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                }}
              />
            </div>

            <div style={{ display: 'flex', gap: '1rem', marginTop: '2rem' }}>
              <button
                onClick={() => setStep(5)}
                style={{
                  flex: 1,
                  padding: '1rem',
                  backgroundColor: '#e5e7eb',
                  color: '#1f2937',
                  border: 'none',
                  borderRadius: '0.5rem',
                  fontSize: '1.125rem',
                  fontWeight: '600',
                  cursor: 'pointer',
                }}
              >
                Back
              </button>
              <button
                onClick={() => setStep(7)}
                disabled={!reportData.petName || !reportData.color}
                style={{
                  flex: 1,
                  padding: '1rem',
                  backgroundColor: (!reportData.petName || !reportData.color) ? '#9ca3af' : '#2563eb',
                  color: 'white',
                  border: 'none',
                  borderRadius: '0.5rem',
                  fontSize: '1.125rem',
                  fontWeight: '600',
                  cursor: (!reportData.petName || !reportData.color) ? 'not-allowed' : 'pointer',
                }}
              >
                Continue
              </button>
            </div>
          </div>
        )}

        {/* Step 7: Location Details */}
        {step === 7 && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
          }}>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              marginBottom: '0.5rem',
              textAlign: 'center',
              color: '#1f2937',
            }}>
              Where Was Your Pet Last Seen?
            </h2>
            <p style={{
              textAlign: 'center',
              color: '#6b7280',
              marginBottom: '2rem',
            }}>
              This helps us alert people in the right area
            </p>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Address or Intersection *
              </label>
              <input
                type="text"
                value={reportData.lastSeenAddress}
                onChange={(e) => setReportData({ ...reportData, lastSeenAddress: e.target.value })}
                placeholder="123 Main St, Chicago, IL or Main St & Oak Ave"
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                }}
                required
              />
              <p style={{ fontSize: '0.875rem', color: '#6b7280', marginTop: '0.5rem' }}>
                We'll show approximate area to protect your privacy
              </p>
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '600' }}>
                Additional Details About Last Sighting
              </label>
              <textarea
                value={reportData.lastSeenDetails}
                onChange={(e) => setReportData({ ...reportData, lastSeenDetails: e.target.value })}
                placeholder="Was in the backyard, jumped fence near the gate. Heading toward the park..."
                rows={4}
                style={{
                  width: '100%',
                  padding: '0.75rem',
                  border: '2px solid #e5e7eb',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                  fontFamily: 'inherit',
                }}
              />
            </div>

            <div style={{ display: 'flex', gap: '1rem', marginTop: '2rem' }}>
              <button
                onClick={() => setStep(6)}
                style={{
                  flex: 1,
                  padding: '1rem',
                  backgroundColor: '#e5e7eb',
                  color: '#1f2937',
                  border: 'none',
                  borderRadius: '0.5rem',
                  fontSize: '1.125rem',
                  fontWeight: '600',
                  cursor: 'pointer',
                }}
              >
                Back
              </button>
              <button
                onClick={async () => {
                  // TODO: Submit to API
                  setIsSubmitting(true);
                  // Simulate API call
                  await new Promise(resolve => setTimeout(resolve, 1000));
                  setReportId('temp-report-id');
                  setStep(8);
                  setIsSubmitting(false);
                }}
                disabled={!reportData.lastSeenAddress || isSubmitting}
                style={{
                  flex: 1,
                  padding: '1rem',
                  backgroundColor: (!reportData.lastSeenAddress || isSubmitting) ? '#9ca3af' : '#10b981',
                  color: 'white',
                  border: 'none',
                  borderRadius: '0.5rem',
                  fontSize: '1.125rem',
                  fontWeight: '600',
                  cursor: (!reportData.lastSeenAddress || isSubmitting) ? 'not-allowed' : 'pointer',
                }}
              >
                {isSubmitting ? 'Creating Alert...' : '🚨 Create Community Alert'}
              </button>
            </div>
          </div>
        )}

        {/* Step 8: Success */}
        {step === 8 && reportId && (
          <div style={{
            backgroundColor: 'white',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
            textAlign: 'center',
          }}>
            <div style={{ fontSize: '4rem', marginBottom: '1rem' }}>✅</div>
            <h2 style={{
              fontSize: '2rem',
              fontWeight: 'bold',
              marginBottom: '1rem',
              color: '#10b981',
            }}>
              Community Alert Created!
            </h2>
            <p style={{
              fontSize: '1.125rem',
              color: '#4b5563',
              marginBottom: '2rem',
              lineHeight: '1.6',
            }}>
              Your alert for <strong>{reportData.petName}</strong> has been sent to community members in your area.
              You'll be notified immediately if anyone spots them.
            </p>

            <div style={{
              backgroundColor: '#f0fdf4',
              border: '2px solid #10b981',
              borderRadius: '0.75rem',
              padding: '1.5rem',
              marginBottom: '2rem',
              textAlign: 'left',
            }}>
              <h3 style={{ fontWeight: '600', marginBottom: '1rem', color: '#047857' }}>
                What Happens Next:
              </h3>
              <ul style={{ marginLeft: '1.5rem', color: '#065f46', lineHeight: '1.8' }}>
                <li>Nearby community members are being alerted right now</li>
                <li>They'll keep an eye out while going about their day</li>
                <li>If anyone spots {reportData.petName}, they'll contact you directly</li>
                <li>You can update or close this alert anytime</li>
              </ul>
            </div>

            <div style={{
              backgroundColor: '#fef3c7',
              border: '2px solid #f59e0b',
              borderRadius: '0.75rem',
              padding: '1.5rem',
              marginBottom: '2rem',
              textAlign: 'left',
            }}>
              <h3 style={{ fontWeight: '600', marginBottom: '1rem', color: '#92400e' }}>
                Continue Following the Advice:
              </h3>
              <p style={{ color: '#78350f', lineHeight: '1.6' }}>
                Remember to follow the recovery advice we showed you earlier. Community alerts work best
                when combined with active searching in your area.
              </p>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <button
                onClick={() => window.location.href = '/'}
                style={{
                  padding: '1rem',
                  backgroundColor: '#2563eb',
                  color: 'white',
                  border: 'none',
                  borderRadius: '0.5rem',
                  fontSize: '1.125rem',
                  fontWeight: '600',
                  cursor: 'pointer',
                }}
              >
                View My Alert
              </button>
              <button
                onClick={handleReset}
                style={{
                  padding: '1rem',
                  backgroundColor: '#e5e7eb',
                  color: '#1f2937',
                  border: 'none',
                  borderRadius: '0.5rem',
                  fontSize: '1rem',
                  fontWeight: '600',
                  cursor: 'pointer',
                }}
              >
                Report Another Pet
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
